Repository aws/jsii, pull requests merged in 2019-11, with the labels that each got.

#928 fix(pacmak): put package README into the right Python module
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/_jsii/__init__.py
Labels: do-not-merge

#944 chore: drop dotnet-sdk 2.2
  superchain/Dockerfile
  superchain/README.md
Labels: ready-to-merge

#951 fix(runtime): make kernel 'load' operation synchronous
  packages/jsii-kernel/lib/kernel.ts
  packages/jsii-kernel/test/kernel.test.ts
  packages/jsii-runtime/.gitignore
  packages/jsii-runtime/.npmignore
  packages/jsii-runtime/lib/host.ts
  packages/jsii-runtime/lib/index.ts
  packages/jsii-runtime/package.json
  packages/jsii-runtime/test/__snapshots__/kernel-host.test.js.snap
  packages/jsii-runtime/test/kernel-host.test.ts
  packages/jsii-runtime/test/playback-test.sh
  packages/jsii-runtime/test/playback.test.ts
  packages/jsii-runtime/test/stress.test.ts
Labels: ready-to-merge

#953 fix(dotnet): fix callback issues
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-dotnet-jsonmodel/src/Amazon.JSII.JsonModel/Api/Request/CreateRequest.cs
  packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs
  packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/ReflectionUtils.cs
  packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/Client.cs
  packages/jsii-dotnet-runtime/src/Amazon.JSII.Runtime/Services/IClient.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/OptionalArgumentInvoker.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/VariadicInvoker.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/OptionalArgumentInvoker.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/VariadicInvoker.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: ready-to-merge

#955 chore: stop asking `yarn` to ignore engine mismatch
  .yarnrc
Labels: ready-to-merge

#712 feat(python): add license & classifiers to generated packages
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
Labels: ready-to-merge

#968 fix(kernel): correctly de-serialize mappings as JSON
  packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/jsii-kernel/lib/serialization.ts
  packages/jsii-kernel/test/kernel.test.ts
  packages/jsii-python-runtime/tests/test_compliance.py
Labels: bug, effort/small, module/kernel

#973 fix(python): correctly handle nested structs-as-dict
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-kernel/lib/serialization.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/INestedStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IRootStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/NestedStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/NestedStructProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RootStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RootStructProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/RootStructValidator.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NestedStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RootStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RootStructValidator.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-python-runtime/tests/test_compliance.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: ready-to-merge

#970 chore: add @typescript-eslint/semi rule
  eslint-config.yaml
  packages/codemaker/lib/filebuff.ts
  packages/codemaker/lib/index.ts
  packages/jsii-kernel/test/kernel.test.ts
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-runtime/lib/host.ts
  packages/jsii-runtime/lib/in-out.ts
  packages/jsii-runtime/lib/sync-stdio.ts
Labels: ready-to-merge

#987 fix(java): remove Jackson confusion with certain patterns
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectMapper.java
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJackson.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJacksonStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJacksonStructProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IConfusingToJacksonStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJackson.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJacksonStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-python-runtime/tests/test_compliance.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: ready-to-merge

#986 fix(java): handle null-able collections correctly
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJackson.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/DisappointingCollectionSource.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJackson.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DisappointingCollectionSource.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Statics.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-python-runtime/tests/test_compliance.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: ready-to-merge

#995 fix(jsii): unable to depend on modules with private declarations
  packages/jsii/lib/compiler.ts
Labels: ready-to-merge

#981 feat(jsii-config): jsii-config
  docs/configuration.md
  packages/jsii-config/.eslintrc.yaml
  packages/jsii-config/.gitignore
  packages/jsii-config/.npmignore
  packages/jsii-config/LICENSE
  packages/jsii-config/README.md
  packages/jsii-config/bin/jsii-config
  packages/jsii-config/bin/jsii-config.ts
  packages/jsii-config/demo.gif
  packages/jsii-config/lib/index.ts
  packages/jsii-config/lib/prompt.ts
  packages/jsii-config/lib/questions.ts
  packages/jsii-config/lib/schema.ts
  packages/jsii-config/lib/util.ts
  packages/jsii-config/lib/validate.ts
  packages/jsii-config/package.json
  packages/jsii-config/test/index.test.ts
  packages/jsii-config/test/util.ts
  packages/jsii-config/tsconfig.json
  packages/jsii-spec/lib/configuration.ts
  packages/jsii-spec/lib/index.ts
  yarn.lock
Labels: feature-request

#1010 chore(rosetta): remove 'commonmark' from public API
  packages/jsii-rosetta/lib/markdown/extract-snippets.ts
  packages/jsii-rosetta/lib/markdown/replace-code-renderer.ts
  packages/jsii-rosetta/lib/markdown/replace-typescript-transform.ts
  packages/jsii-rosetta/lib/markdown/types.ts
  packages/jsii-rosetta/lib/rosetta.ts
Labels: ready-to-merge

#1032 fix: Move jsii-spec to Dependencies in jsii-config
  packages/jsii-config/package.json
Labels: bug, dependencies

#1047 fix: Allow Missing Dotnet Version Suffix
  docs/configuration.md
  packages/jsii-config/README.md
  packages/jsii-config/bin/jsii-config.ts
  packages/jsii-config/lib/prompt.ts
  packages/jsii-config/lib/schema.ts
  packages/jsii-config/lib/util.ts
  packages/jsii-config/test/index.test.ts
Labels: bug, documentation

#1061 chore: update dependabot config to match with new label names
  .dependabot/config.yml
Labels: ready-to-merge

#1071 fix(dotnet/roslyn): analyzer target framework
  packages/jsii-dotnet-analyzers/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj
Labels: ready-to-merge

#1070 fix(java): remove Jackson confusion with certain patterns
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectMapper.java
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJackson.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJacksonStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConfusingToJacksonStructProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IConfusingToJacksonStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJackson.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJacksonStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-python-runtime/tests/test_compliance.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: ready-to-merge

#1009 fix(python): correctly handle structs out of callbacks
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/JsiiClientTest.java
  packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiClient.java
  packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java
  packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/api/CreateRequest.java
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/ConsumePureInterface.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IStructReturningDelegate.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IStructReturningDelegateProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConsumePureInterface.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/IStructReturningDelegate.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-python-runtime/setup.py
  packages/jsii-python-runtime/src/jsii/_kernel/__init__.py
  packages/jsii-python-runtime/tests/test_compliance.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: ready-to-merge
