Repository aws/jsii, pull requests merged in 2020-10, with the labels that each got.

#2065 chore(pacmak/go): indent using tabs instead of spaces
  packages/codemaker/lib/codemaker.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, effort/small, language/go, module/pacmak, pr/ready-to-merge

#2066 feat(go): embed jsii runtime application
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/jsii-calc-test/main.go
  packages/@jsii/go-runtime/jsii-experimental/client.go
  packages/@jsii/go-runtime/jsii-experimental/client_test.go
  packages/@jsii/go-runtime/jsii-experimental/embedded/.gitkeep
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
  packages/@jsii/go-runtime/package.json
Labels: contribution/core, effort/small, language/go, module/runtime, pr/ready-to-merge

#2074 chore(java): mockito 3.5.13
  packages/@jsii/java-runtime/pom.xml.t.js
Labels: pr/ready-to-merge

#2073 chore(java): maven-surefire-plugin 3.0.0-M5
  packages/@jsii/java-runtime/pom.xml.t.js
Labels: pr/ready-to-merge

#2061 fix(dotnet): abundant nullability warnings in generated code
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetruntimegenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
Labels: contribution/core, effort/small, language/dotnet, module/pacmak, module/runtime, pr/ready-to-merge

#2067 feat(go): dynamically load npm packages as needed
  packages/@jsii/go-runtime/jsii-experimental/api.go
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
Labels: contribution/core, effort/small, language/go, module/pacmak, module/runtime, pr/ready-to-merge

#2070 fix(jsii-diff): external structs returned from methods cannot be changed
  packages/jsii-diff/lib/classes-ifaces.ts
  packages/jsii-diff/lib/enums.ts
  packages/jsii-diff/lib/index.ts
  packages/jsii-diff/lib/stability.ts
  packages/jsii-diff/lib/type-analysis.ts
  packages/jsii-diff/lib/type-comparison.ts
  packages/jsii-diff/lib/types.ts
  packages/jsii-diff/lib/util.ts
  packages/jsii-diff/lib/validations.ts
  packages/jsii-diff/test/classes.test.ts
  packages/jsii-diff/test/diagnostics.test.ts
  packages/jsii-diff/test/structs.test.ts
  packages/jsii-diff/test/util.ts
Labels: contribution/core, pr/ready-to-merge

#2077 chore: add closed issue message github action
  .github/workflows/closed-issue-message.yml
Labels: contribution/core

#2089 docs: set up "All Contributors"
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: contribution/core, documentation, effort/small

#2097 chore: fix jsii-pacmak test failure on Windows
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/generated-code/all-targets-tested.test.ts
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/target-python.test.ts
Labels: contribution/core, pr/ready-to-merge

#2112 chore(runtime/java): apply tighter pin on Jackson
  packages/@jsii/java-runtime/pom.xml.t.js
Labels: contribution/core, pr/ready-to-merge

#2059 chore: publish Docker image from GitHub actions instead of Travis
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  .github/workflows/superchain.yml
  .mergify/config.yml
  .travis.yml
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Helpers/DiagnosticResult.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/JsiiOptionalAnalyzerTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.Helper.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.cs
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Jsii.java
Labels: contribution/core, management/devenv, ops-excellence

#2115 fix(go): runtime api json invalid tags
  packages/@jsii/go-runtime/jsii-experimental/api.go
Labels: contribution/core

#2100 fix(python): leftover jsii-kernel-* directories in TMPDIR
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
Labels: bug, contribution/core, effort/small, language/python, module/runtime, p2

#2126 chore: npm-check-updates && yarn upgrade
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: contribution/core, dependencies

#2125 chore(tests/dotnet): update tests to .NET 5.0.0-rc2
  .github/workflows/main.yml
Labels: contribution/core

#2117 feat(go): runtime object creation
  packages/@jsii/go-runtime/README.md
  packages/@jsii/go-runtime/jsii-experimental/api.go
  packages/@jsii/go-runtime/jsii-experimental/client.go
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime/class-constructor.ts
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/index.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/util.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core

#2131 chore(rosetta): streamline TypeScript compiler API usage
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
Labels: contribution/core

#2136 chore: attempt to increase node VM heap in integ test
  .github/workflows/main.yml
Labels: contribution/core

#2130 fix(rosetta): duplicated problem markers
  packages/jsii-rosetta/lib/util.ts
Labels: contribution/core, pr/ready-to-merge

#2147 fix(go): Submodule File Paths
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, language/go, pr/ready-to-merge

#2144 chore(dotnet): stop shipping copy of .jsii assembly
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2124 docs(whitepaper): high-level jsii overrides and callbacks
  docs/.prettierrc.yaml
  docs/whitepapers/callbacks.md
  docs/whitepapers/callbacks.monopic
Labels: contribution/core, documentation

#2092 chore: removes unused software from superchain to reduce image size
  superchain/Dockerfile
  superchain/README.md
Labels: breaking-change

#2153 chore: increase concurrency of integration test
  .github/workflows/main.yml
Labels: contribution/core

#2145 feat(go): Runtime method and static invoke support
  packages/@jsii/go-runtime/jsii-experimental/api.go
  packages/@jsii/go-runtime/jsii-experimental/client.go
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core

#2133 fix(go): fix generation of readonly and static properties
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: language/go, pr/ready-to-merge

#2076 feat(pacmak/java): emit default interface implementations
  packages/@jsii/java-runtime-test/pom.xml.t.js
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Internal.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiClient.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiModule.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiObject.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectMapper.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectRef.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiSerializable.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Kernel.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/NativeType.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/api/Callback.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/api/CreateRequest.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/api/GetRequest.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/api/InvokeRequest.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/api/JsiiOverride.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/api/SetRequest.java
  packages/@jsii/java-runtime/project/src/test/java/software/amazon/jsii/JsiiObjectTest.java
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetruntimegenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii/lib/project-info.ts
Labels: contribution/core, effort/large, language/java, module/pacmak, pr/ready-to-merge

#2148 chore: add parameter dependencies
  packages/jsii-calc/lib/submodule/index.ts
  packages/jsii-calc/lib/submodule/my-class.ts
  packages/jsii-calc/lib/submodule/param/index.ts
  packages/jsii-calc/lib/submodule/returns-param/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: language/go

#2154 chore(tests): migrate jest config to jest.config.ts
  eslint-config.yaml
  jest.config.ts
  package.json
  packages/@jsii/integ-test/jest.config.ts
  packages/@jsii/integ-test/package.json
  packages/@jsii/integ-test/tsconfig.json
  packages/@jsii/kernel/jest.config.ts
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/tsconfig.json
  packages/@jsii/runtime/jest.config.ts
  packages/@jsii/runtime/package.json
  packages/@jsii/runtime/tsconfig.json
  packages/@jsii/spec/jest.config.ts
  packages/@jsii/spec/package.json
  packages/@jsii/spec/tsconfig.json
  packages/codemaker/jest.config.ts
  packages/codemaker/package.json
  packages/codemaker/tsconfig.json
  packages/jsii-config/jest.config.ts
  packages/jsii-config/package.json
  packages/jsii-config/tsconfig.json
  packages/jsii-diff/generate.sh
  packages/jsii-diff/jest.config.ts
  packages/jsii-diff/package.json
  packages/jsii-diff/tsconfig.json
  packages/jsii-pacmak/generate.sh
  packages/jsii-pacmak/jest.config.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/tsconfig.json
  packages/jsii-reflect/jest.config.ts
  packages/jsii-reflect/package.json
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
  packages/jsii-reflect/tsconfig.json
  packages/jsii-rosetta/jest.config.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/tsconfig.json
  packages/jsii/generate.sh
  packages/jsii/jest.config.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/package.json
  packages/jsii/tsconfig.json
  packages/oo-ascii-tree/jest.config.ts
  packages/oo-ascii-tree/package.json
  packages/oo-ascii-tree/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: contribution/core, pr/ready-to-merge

#2165 chore: tune diff-test for superchain build test
  .github/workflows/docker-images.yml
Labels: contribution/core

#2163 fix(jsii): TypeError: Cannot read property 'getJsDocTags' of undefined
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/test/quirks.test.ts
Labels: bug, contribution/core, effort/small, module/compiler, pr/ready-to-merge

#2138 fix(pacmak/python): escape character escapes in python docs
  packages/jsii-pacmak/lib/markdown.ts
  packages/jsii-pacmak/test/python.test.ts
Labels: pr/ready-to-merge

#2174 chore: add blog posts to README & contributors list
  .all-contributorsrc
  .prettierrc.yaml
  README.md
Labels: contribution/core

#2170 build: do not publish test directory
  packages/jsii-pacmak/.npmignore
Labels: pr/ready-to-merge

#2172 fix(jsii): annotation '@internal' causes missing type declarations downstream
  packages/jsii/lib/compiler.ts
Labels: contribution/core, effort/small, module/compiler, pr/ready-to-merge

#2176 chore: stop using symlinks for jest config
  packages/@jsii/kernel/jest.config.ts
  packages/codemaker/jest.config.ts
  packages/jsii-config/jest.config.ts
  packages/jsii-diff/jest.config.ts
  packages/jsii-rosetta/jest.config.ts
  packages/jsii/jest.config.ts
  packages/oo-ascii-tree/jest.config.ts
Labels: contribution/core

#2168 chore(docs): fix typos
  docs/assembly.md
  docs/configuration.md
  docs/specifications/3-kernel-api.md
  docs/whitepapers/callbacks.md
Labels: pr/ready-to-merge

#2167 chore: in-process generated code regression tests
  jest.config.ts
  packages/@jsii/go-runtime/jsii-calc-test/main.go
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/jest.config.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/index.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/all-targets-tested.test.ts
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/target-dotnet.test.ts
  packages/jsii-pacmak/test/generated-code/target-go.test.ts
  packages/jsii-pacmak/test/generated-code/target-java.test.ts
  packages/jsii-pacmak/test/generated-code/target-python.test.ts
Labels: contribution/core, effort/small, module/pacmak, ops-excellence, pr/ready-to-merge

#2175 chore: improve code to get symbol/node names
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/jsii-diagnostic.ts
Labels: contribution/core, effort/small, module/compiler, pr/ready-to-merge

#2178 chore(go): support get/set kernel API in go runtime
  packages/@jsii/go-runtime/jsii-experimental/api.go
  packages/@jsii/go-runtime/jsii-experimental/client.go
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: language/go, pr/ready-to-merge

#2192 feat(dotnet): introduce `UnsafeCast<T>()` method
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/DeputyBaseTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/AnonymousObject.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
Labels: contribution/core, effort/small, feature-request, language/dotnet, module/runtime, pr/ready-to-merge

#2196 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies

#2177 chore(actions): stop using set-env and add-path
  .github/workflows/main.yml
Labels: contribution/core

#2197 chore(actions): stop using set-env and add-path (#2177)
  .github/workflows/main.yml
Labels: contribution/core

#2146 feat(pacmak): prerelease identifier support
  .github/workflows/main.yml
  docs/configuration.md
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/lib/targets/index.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/js.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/prerelease-identifiers.test.ts
  packages/jsii-pacmak/test/npm-modules.test.ts
  packages/jsii-pacmak/test/targets/version-utils.test.ts
Labels: contribution/core, effort/small, language/python, module/pacmak, pr/ready-to-merge

#2206 chore(merge-back): 1.14.0
  .github/workflows/docker-images.yml
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash
