Repository aws/jsii, pull requests merged in 2020-11, with the labels that each got.

#2212 fix(python): update `cattrs` dependency specification
  packages/@jsii/python-runtime/setup.py
Labels: bug, contribution/core, pr/ready-to-merge

#2225 chore(release): 1.14.1
  CHANGELOG.md
  lerna.json
  packages/@jsii/python-runtime/setup.py
Labels: contribution/core, pr/no-squash, pr/ready-to-merge

#2227 chore(merge-back): 1.14.1
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/ready-to-merge

#2228 chore: npm-check-updates && yarn upgrade
  package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2226 chore(rosetta): de-duplicate diagnostics early
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/util.ts
Labels: contribution/core, pr/ready-to-merge

#2233 feat(jsii): configure diagnostics in package.json
  docs/configuration.md
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/test/jsii-diagnostic.test.ts
  packages/jsii/test/project-info.test.ts
Labels: contribution/core, module/compiler, pr/ready-to-merge

#2211 feat(rosetta): hoist imports above fixtures
  packages/jsii-rosetta/README.md
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/typescript/ast-utils.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii-rosetta/test/jsii/fake-assembly.ts
  packages/jsii-rosetta/test/jsii/fixtures/rosetta/explicit.ts-fixture
  packages/jsii-rosetta/test/rosetta.test.ts
Labels: contribution/core, pr/ready-to-merge

#2238 fix(runtime): "Error: EOF: end of file, read" on Windows
  .github/workflows/main.yml
  packages/@jsii/runtime/lib/program.ts
  packages/@jsii/runtime/lib/sleep.ts
  packages/@jsii/runtime/lib/sync-stdio.ts
  packages/@jsii/runtime/test/playback.test.ts
Labels: contribution/core, effort/small, os/windows, pr/ready-to-merge

#2214 chore: add Python 3.9 to test matrix
  .github/workflows/main.yml
  .mergify/config.yml
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: contribution/core, language/python, pr/ready-to-merge

#2244 chore: update test matrix to .NET5 release
  .github/workflows/main.yml
  .mergify/config.yml
Labels: contribution/core, language/dotnet

#2229 chore: enable additional eslint rules
  eslint-config.yaml
  packages/@jsii/kernel/lib/serialization.ts
  packages/@jsii/kernel/test/kernel.test.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-reflect/lib/tree.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/tree.test.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/markdown/replace-typescript-transform.ts
  packages/jsii-rosetta/lib/o-tree.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/typescript/ast-utils.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/docs.ts
  packages/oo-ascii-tree/lib/ascii-tree.ts
Labels: contribution/core, pr/ready-to-merge

#2245 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2247 feat(dotnet,java): finalize kernel process on VM shutdown
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
Labels: contribution/core, effort/small, language/dotnet, language/java, module/runtime, pr/ready-to-merge

#2230 feat(rosetta): support computed properties
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/visualize.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/lib/typescript/types.ts
  packages/jsii-rosetta/test/translations.test.ts
  packages/jsii-rosetta/test/translations/calls/shorthand_property.java
  packages/jsii-rosetta/test/translations/calls/will_type_deep_structs_directly_if_type_info_is_available.java
  packages/jsii-rosetta/test/translations/classes/class_with_props_argument.java
  packages/jsii-rosetta/test/translations/classes/constructor_with_optional_params.java
  packages/jsii-rosetta/test/translations/expressions/as_expression.java
  packages/jsii-rosetta/test/translations/expressions/computed_key.cs
  packages/jsii-rosetta/test/translations/expressions/computed_key.java
  packages/jsii-rosetta/test/translations/expressions/computed_key.py
  packages/jsii-rosetta/test/translations/expressions/computed_key.ts
  packages/jsii-rosetta/test/translations/expressions/string_interpolation.java
  packages/jsii-rosetta/test/translations/structs/var_new_class_unknown_struct.java
Labels: contribution/core, pr/ready-to-merge

#2252 feat(rosetta): make assembly validation opt-in
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
Labels: contribution/core, effort/small, pr/ready-to-merge

#2257 fix(go): generate concrete structs for behavioral interfaces
  packages/@jsii/go-runtime/jsii-calc-test/main.go
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/index.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/property-access.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, language/go

#2264 chore: npm-check-updates && yarn upgrade
  packages/@jsii/runtime/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2265 feat(go): generate go.mod files
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-experimental/go.mod
  packages/@jsii/go-runtime/package.json
  packages/@jsii/spec/lib/assembly.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-reflect/lib/assembly.ts
Labels: language/go

#2266 feat(go): runtime type casting
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/function-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/property-access.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, language/go

#2253 feat(rosetta): support "strict" assemblies
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-rosetta/README.md
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/convert.ts
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/markdown/extract-snippets.ts
  packages/jsii-rosetta/lib/markdown/replace-typescript-transform.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/strict.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/rosetta.test.ts
Labels: contribution/core, effort/small, pr/ready-to-merge

#2273 chore: go runtime renaming
  packages/@jsii/go-runtime/jsii-experimental/runtime.go
Labels: contribution/core, language/go

#2278 chore(merge-back): 1.15.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/ready-to-merge

#2280 chore: npm-check-updates && yarn upgrade
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge
