Repository aws/jsii, pull requests merged in 2020-01, with the labels that each got.

#1175 fix: edit typo in diagnostic message.
  packages/jsii/lib/assembler.ts
Labels: pr-status/ready-to-merge

#1165 fix(java): maven-surefire-plugin 2.22.2
  packages/@jsii/java-runtime/pom.xml.t.js
Labels: pr-status/ready-to-merge

#1181 docs: add information about jsii/superchain releasing
  CONTRIBUTING.md
Labels: pr-status/ready-to-merge

#1177 fix: depend on python-3.8-supporting version of cattrs
  packages/@jsii/python-runtime/setup.py
Labels: effort/small

#1187 fix: poor error message on scalar deserialization type mismatch
  packages/@jsii/kernel/lib/serialization.ts
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/test/serialization.test.ts
Labels: pr-status/ready-to-merge

#1205 feat(superchain): upgrade maven to 3.6.3
  superchain/Dockerfile
  superchain/README.md
  superchain/build-local.sh
Labels: pr-status/ready-to-merge

#1220 chore: add test loading current assembly
  packages/@jsii/spec/test/previous-assemblies/0.21.2.jsii.json
  packages/@jsii/spec/test/validate-assembly.test.ts
Labels: contribution/core, effort/small, pr-status/ready-to-merge
