Repository aws/jsii, pull requests merged in 2020-06, with the labels that each got.

#1706 fix(jsii-pacmak): computeIfAbsent throws ConcurrentModificationException
  packages/@jsii/java-runtime-test/.gitignore
  packages/@jsii/java-runtime-test/generate.sh
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/@jsii/java-runtime-test/user.xml.t.js
  packages/jsii-calc/lib/submodule/child/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/java/src/main/java/software/amazon/jsii/tests/calculator/baseofbase/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/java/software/amazon/jsii/tests/calculator/base/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/ISomeStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/InnerClass.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/OuterClass.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/SomeEnum.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/SomeStruct.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/SomeStructProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/child/InnerClass.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/child/OuterClass.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/child/SomeEnum.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/child/SomeStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: contribution/core, p0, pr/ready-to-merge

#1709 feat(pacmak/java): isolate maven repositories
  packages/@jsii/java-runtime/.gitignore
  packages/@jsii/java-runtime/generate.sh
  packages/@jsii/java-runtime/package.json
  packages/@jsii/java-runtime/project/.gitignore
  packages/@jsii/java-runtime/user.xml.t.js
  packages/jsii-pacmak/lib/targets/java.ts
Labels: contribution/core, pr/ready-to-merge

#1711 chore(release): merge release/1.6.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/ready-to-merge

#1716 fix(python): no overload variant of "Factory" matches argument type "object"
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
Labels: contribution/core

#1708 fix(jsii): build succeeds using Omit<T, K>
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/test/negatives/neg.omit.1.ts
  packages/jsii/test/negatives/neg.omit.2.ts
  packages/jsii/test/negatives/neg.omit.3.ts
  packages/jsii/test/negatives/neg.omit.4.ts
Labels: bug, contribution/core, effort/small, module/compiler, pr/ready-to-merge

#1696 feat(jsii-pacmak): add maven and nuget support for * dependencies
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/test/targets/version-utils.test.ts
Labels: pr/ready-to-merge

#1724 fix(python): reference isomorphism is broken within __init__
  packages/@jsii/python-runtime/bin/generate-calc
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Isomorphism.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IsomorphismProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Isomorphism.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: bug, contribution/core, language/python, module/runtime, pr/ready-to-merge

#1717 fix(@jsii/runtime): "maximum call stack size exceeded" in SyncStdio.readLine
  packages/@jsii/runtime/lib/sync-stdio.ts
Labels: bug, contribution/core, pr/ready-to-merge

#1737 chore: toolchain table in readme
  README.md
Labels: contribution/core, pr/ready-to-merge

#1751 feat: turn off assembly validation
  packages/jsii/lib/project-info.ts
Labels: contribution/core, pr/ready-to-merge

#1754 chore(release): 1.7.0
  .dependabot/config.yml
  .github/dependabot.yml
  .mergify.yml
  CHANGELOG.md
  README.md
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.sln
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/bin/generate-calc
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/runtime/lib/sync-stdio.ts
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Isomorphism.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/IsomorphismProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Isomorphism.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/targets/version-utils.test.ts
  packages/jsii-reflect/package.json
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/package.json
  packages/jsii/test/negatives/neg.omit.1.ts
  packages/jsii/test/negatives/neg.omit.2.ts
  packages/jsii/test/negatives/neg.omit.3.ts
  packages/jsii/test/negatives/neg.omit.4.ts
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#1755 chore(release): merge release/1.7.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/ready-to-merge

#1738 chore(pacmak/python): format generated code using black
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/src/scope/jsii_calc_base_of_base/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/src/scope/jsii_calc_base_of_base/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/custom_submodule_name/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/composition/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/derived_class_has_no_properties/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_only_interface/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/python_self/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/back_references/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/deeply_nested/__init__.py
Labels: contribution/core, pr/ready-to-merge
