Repository aws/jsii, pull requests merged in 2020-07, with the labels that each got.

#1766 fix(kernel): tarball unpacking does not behave like 'npm install'
  packages/@jsii/kernel/lib/kernel.ts
  packages/@jsii/kernel/test/kernel.test.ts
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UmaskCheck.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UmaskCheck.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: contribution/core, pr/ready-to-merge

#1769 chore: remove dependency on jq for fetch-dotnet-snk.sh
  .gitignore
  scripts/fetch-dotnet-snk.sh
Labels: contribution/core

#1768 fix(python): relative import missing for kwargs types
  packages/jsii-calc/lib/submodule/my-class.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/MyClass.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/MyClass.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
Labels: bug, contribution/core, language/python, module/pacmak, pr/ready-to-merge

#1770 chore: temporarily disable strong name signing
  scripts/fetch-dotnet-snk.sh
Labels: contribution/core

#1775 chore(release): merge release/1.8.0 to master
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/ready-to-merge

#1774 chore: yarn upgrade
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/codemaker/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: contribution/core

#1779 fix(jsii-reflect): TypeSystem.methods and .properties ignores submodules
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/test/type-system.test.ts
Labels: contribution/core, pr/ready-to-merge

#1782 fix(pacmak): python pack fails when installing 'black' via pip
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/targets/python.test.ts
  superchain/Dockerfile
Labels: contribution/core

#1783 fix(pacmak): race condition in python packing when run over multiple packages
  packages/jsii-pacmak/lib/targets/python.ts
Labels: contribution/core, pr/ready-to-merge

#1793 chore(release): 1.9.0
  CHANGELOG.md
  lerna.json
  package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/targets/python.test.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/package.json
  packages/jsii-reflect/test/type-system.test.ts
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  superchain/Dockerfile
  yarn.lock
Labels: pr/no-squash

#1794 chore(dotnet-runtime): exclusion of built binaries
  packages/@jsii/dotnet-runtime/.npmignore
Labels: contribution/core, pr/do-not-merge

#1797 chore(merge-back): 1.9.0
  CHANGELOG.md
  lerna.json
  packages/@jsii/dotnet-runtime/.npmignore
Labels: pr/no-squash, pr/ready-to-merge

#1798 chore: update yarn.lock file
  yarn.lock
Labels: contribution/core, pr/ready-to-merge

#1802 chore: add workflow to run "yarn upgrade" periodically
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core, pr/ready-to-merge

#1806 fix(jsii): document location of initializers in source
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii/lib/assembler.ts
Labels: contribution/core, effort/small, module/compiler, pr/ready-to-merge

#1811 chore: npm-check-updates && yarn upgrade
  package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#1810 fix(python): missing imports for certain keyword arguments
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-calc/lib/submodule/child/index.ts
  packages/jsii-calc/lib/submodule/index.ts
  packages/jsii-calc/lib/submodule/isolated.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/IKwargsProps.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/KwargsProps.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/KwargsPropsProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Isolated/Kwargs.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/child/KwargsProps.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/isolated/Kwargs.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/isolated/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: bug, contribution/core, effort/small, pr/ready-to-merge

#1812 fix(java): user.xml repository ID was not sanitized
  packages/jsii-pacmak/lib/targets/java.ts
Labels: bug, contribution/core, language/java, pr/ready-to-merge

#1829 fix(jsii): selective exports declarations are ignored
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/test/export-specifier.test.ts
Labels: contribution/core, effort/small, module/compiler, pr/ready-to-merge

#1831 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#1832 fix(rosetta): variadic arguments may use kwargs syntax in Python
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/test/translations/statements/vararg_any_call.cs
  packages/jsii-rosetta/test/translations/statements/vararg_any_call.java
  packages/jsii-rosetta/test/translations/statements/vararg_any_call.py
  packages/jsii-rosetta/test/translations/statements/vararg_any_call.ts
Labels: bug, contribution/core, pr/ready-to-merge

#1833 chore: comprehensive build-and-validate workflow
  .github/workflows/main.yml
  .versionrc.json
  packages/@jsii/java-runtime-test/package.json
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@jsii/python-runtime/package.json
  packages/codemaker/test/filebuff.test.ts
  packages/codemaker/test/source.test.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/project-info.ts
Labels: contribution/core, feature-request, management/repo

#1842 fix(rosetta): OOpsie -- couldn't find root file back on Windows
  .github/workflows/main.yml
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/java-runtime-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii-rosetta/test/translations.test.ts
Labels: bug, contribution/core, os/windows, pr/ready-to-merge
