Repository aws/jsii, pull requests merged in 2020-03, with the labels that each got.

#1305 chore: Fix integ test module install strategy
  packages/@jsii/integ-test/test/build-cdk.test.ts
  packages/@jsii/integ-test/utils/index.ts
Labels: contribution/core

#1318 chore: align versions in build test
  packages/@jsii/integ-test/test/build-cdk.test.ts
Labels: contribution/core

#1332 fix(python-runtime): KernelResponse missing types
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
Labels: contribution/core, language/python, pr/ready-to-merge

#1337 chore: ran 'yarn upgrade'
  .dependabot/config.yml
  .yarnrc
  package.json
  packages/@jsii/integ-test/test/build-cdk.test.ts
  yarn.lock
Labels: contribution/core, pr/ready-to-merge

#1341 fix(dotnet-analyzers): unit test null reference
  packages/@jsii/dotnet-analyzers/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.cs
Labels: contribution/core

#1347 fix(kernel): "any" serialization breaks private type instances
  docs/specifications/2-type-system.md
  packages/@jsii/kernel/lib/objects.ts
  packages/@jsii/kernel/lib/serialization.ts
  packages/@jsii/kernel/test/serialization.test.ts
  packages/@jsii/python-runtime/src/jsii/_reference_map.py
  packages/@jsii/python-runtime/tests/README.md
Labels: contribution/core

#1344 fix(jsii): out-of-source builds are broken
  packages/@scope/jsii-calc-lib/.gitignore
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId.csproj
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Internal/DependencyResolution/Anchor.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/pom.xml
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/_jsii/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
Labels: contribution/core, pr/ready-to-merge

#1354 fix(diff): check base types
  packages/jsii-diff/lib/classes-ifaces.ts
  packages/jsii-diff/lib/type-analysis.ts
  packages/jsii-diff/test/classes.test.ts
  packages/jsii-reflect/lib/type.ts
Labels: contribution/core, pr/ready-to-merge

#1406 fix(jsii): single-valued enums are not processed correctly
  packages/jsii-calc/lib/submodule/child/index.ts
  packages/jsii-calc/lib/submodule/my-class.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/Child/Awesomeness.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/Submodule/MyClass.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/MyClass.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/child/Awesomeness.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii/lib/assembler.ts
Labels: contribution/core, pr/ready-to-merge
