Repository aws/jsii, pull requests merged in 2020-12, with the labels that each got.

#2300 chore: add go reserved words
  docs/typescript-restrictions.md
  packages/jsii/lib/reserved-words.ts
Labels: language/go, pr/ready-to-merge

#2305 fix(java): exception is logged when Java VM is shutting down
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
Labels: bug, contribution/core, effort/small, pr/ready-to-merge

#2298 fix(runtime): excessive latency introduced by sleep
  .all-contributorsrc
  README.md
  packages/@jsii/runtime/jest.config.ts
  packages/@jsii/runtime/lib/sleep.ts
  packages/@jsii/runtime/lib/sync-stdio.ts
Labels: contribution/core, effort/small, module/runtime, p1, pr/ready-to-merge

#2322 chore(release): 1.16.0
  .all-contributorsrc
  .github/workflows/main.yml
  CHANGELOG.md
  README.md
  docs/typescript-restrictions.md
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/Amazon.JSII.JsonModel.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/jest.config.ts
  packages/@jsii/runtime/lib/sleep.ts
  packages/@jsii/runtime/lib/sync-stdio.ts
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/targets/version-utils.test.ts
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/reserved-words.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#2323 chore(merge-back): 1.16.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/ready-to-merge

#1941 feat: add support for bin-scripts (python only)
  packages/@jsii/kernel/lib/api.ts
  packages/@jsii/kernel/lib/kernel.ts
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@jsii/kernel/test/recording.ts
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/base.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/spec/lib/assembly.ts
  packages/jsii-calc/bin/run
  packages/jsii-calc/bin/run.cmd
  packages/jsii-calc/bin/run.ts
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/project-info.ts
Labels: pr/ready-to-merge

#2324 feat: go runtime auto push
  .github/workflows/push-go-runtime.yml
  packages/@jsii/go-runtime/build-tools/.eslintrc.yaml
  packages/@jsii/go-runtime/build-tools/_constants.ts
  packages/@jsii/go-runtime/build-tools/build-repo-dir.ts
  packages/@jsii/go-runtime/build-tools/gen-calc.ts
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/build-tools/repo-files/CONTRIBUTING.md
  packages/@jsii/go-runtime/build-tools/repo-files/README.md
  packages/@jsii/go-runtime/build-tools/tsconfig.json
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-experimental/go.mod
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core

#2341 docs: remove spurrious word
  gh-pages/content/home/runtime-architecture.md
Labels: pr/ready-to-merge

#2338 docs: fix typo in features.md
  gh-pages/content/home/features.md
Labels: pr/ready-to-merge

#2333 chore: stop running yarn upgrade at end of image build
  superchain/Dockerfile
Labels: contribution/core

#2331 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2350 fix(jsii): unknown error in Assembler._validateHeritageClauses
  packages/jsii/lib/assembler.ts
Labels: contribution/core, pr/ready-to-merge

#2351 fix(jsii): errors when invoking with a project root argument
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/compiler.ts
Labels: contribution/core, pr/ready-to-merge

#2356 fix: bad working directory in go runtime push
  .github/workflows/push-go-runtime.yml
Labels: contribution/core

#2362 chore: npm-check-updates && yarn upgrade
  packages/@jsii/spec/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2373 fix(pacmak): illegal static overrides in java & c#
  gh-pages/content/language-support/assembly.md
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core, effort/small, module/pacmak, pr/ready-to-merge

#2368 fix(dotnet): Use nested classes for proxies to avoid name collision
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
Labels: feature-request, language/dotnet, pr/ready-to-merge, review/medium

#2379 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2384 docs: fix typo in index.md
  gh-pages/content/index.md
Labels: pr/ready-to-merge
