Repository aws/jsii, pull requests merged in 2020-04, with the labels that each got.

#1461 chore(python): improve test harness slightly
  packages/@jsii/python-runtime/bin/generate-calc
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/setup.py
Labels: contribution/core, pr/ready-to-merge

#1479 chore: merge release/1.2.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash

#1498 chore: run travis on release branch
  .travis.yml
Labels: contribution/core

#1492 fix(jsii-diff): detect interfaces inherited via interfaces
  packages/jsii-diff/test/classes.test.ts
  packages/jsii-reflect/lib/class.ts
Labels: contribution/core

#1428 docs: Introduce language implementation handbook
  docs/handbooks/language-implementation.md
  docs/specifications/1-introduction.md
  docs/specifications/2-type-system.md
  docs/specifications/3-kernel-api.md
  docs/specifications/4-standard-compliance-suite.md
Labels: contribution/core, pr/do-not-merge

#1368 feat(compliance): produce compliance test reports
  packages/@jsii/dotnet-runtime-test/.gitignore
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ServiceContainerFixture.cs
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/XUnitLogger.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/JsiiTypeAttributeBase.cs
  packages/@jsii/java-runtime-test/pom.xml.t.js
  packages/@jsii/java-runtime-test/project/.gitignore
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/ComplianceSuiteHarness.java
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/JsiiVersionTest.java
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/ReloadingClassLoader.java
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/JsiiClientTest.java
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiClient.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectMapper.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/MessageInspector.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Util.java
Labels: contribution/core, pr/ready-to-merge

#1554 chore(python): cosmetic improvements on generated code
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/src/scope/jsii_calc_base_of_base/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_only_interface/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/back_references/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
Labels: contribution/core, effort/small, language/python, module/pacmak, pr/ready-to-merge

#1558 chore(python): improve generating of __all__ value
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/src/scope/jsii_calc_base_of_base/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/src/scope/jsii_calc_base_of_base/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/composition/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/derived_class_has_no_properties/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_only_interface/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/back_references/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/deeply_nested/__init__.py
Labels: contribution/core, pr/ready-to-merge

#1561 chore: merge release/1.3.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash, pr/ready-to-merge

#1562 chore: remove artifacts between builds in CI
  buildspec.yaml
Labels: contribution/core

#1564 chore: clean up all dist folders before building release packages
  buildspec.yaml
  package.json
  packages/@jsii/dotnet-analyzers/build.sh
  packages/@jsii/dotnet-analyzers/package.json
  packages/@jsii/dotnet-jsonmodel/build.sh
  packages/@jsii/dotnet-jsonmodel/package.json
  packages/@jsii/dotnet-runtime/build.sh
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/python-runtime/.gitignore
  packages/@jsii/python-runtime/package.json
  packages/@jsii/ruby-runtime/package.json
  tools/jsii-build-tools/bin/package-dotnet
  tools/jsii-build-tools/bin/package-java
  tools/jsii-build-tools/bin/package-python
  tools/jsii-build-tools/bin/package-ruby
Labels: contribution/core

#1568 fix(jsii-pacmak): invalid dotnet version suffixes
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId.csproj
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId.csproj
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon.JSII.Tests.CalculatorPackageId.csproj
  packages/jsii-pacmak/test/targets/version-utils.test.ts
Labels: contribution/core

#1569 chore(release): 1.3.1
  CHANGELOG.md
  lerna.json
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId.csproj
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId.csproj
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon.JSII.Tests.CalculatorPackageId.csproj
  packages/jsii-pacmak/test/targets/version-utils.test.ts
Labels: contribution/core, pr/no-squash, pr/ready-to-merge

#1582 fix(python): incorrect dependency on jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
Labels: bug, contribution/core, effort/small

#1584 chore(dotnet): standardize generation of jsii runtime dependency
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/lib/util.ts
Labels: contribution/core

#1585 chore(release): 1.3.2
  .gitignore
  CHANGELOG.md
  docs/assembly.md
  docs/configuration.md
  docs/handbooks/language-implementation.md
  docs/runtime-architecture.md
  docs/specifications/1-introduction.md
  docs/specifications/2-type-system.md
  docs/specifications/3-kernel-api.md
  docs/specifications/4-standard-compliance-suite.md
  docs/specifications/5-new-language-intake.md
  docs/typescript-restrictions.md
  lerna.json
  packages/@jsii/dotnet-analyzers/package.json
  packages/@jsii/dotnet-jsonmodel/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/ruby-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#1586 chore: merge release/1.3.2 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash, pr/ready-to-merge

#1587 feat(python): improve metadata of jsii package
  packages/@jsii/python-runtime/bin/generate
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/setup.py
Labels: contribution/core, effort/small, pr/ready-to-merge

#1563 feat(spec): model submodules in the Assembly schema
  packages/@jsii/spec/lib/assembly.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii/lib/assembler.ts
Labels: contribution/core, effort/medium, feature-request, pr/ready-to-merge

#1605 fix(java): compilation fails with "code too large"
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/java/src/main/java/software/amazon/jsii/tests/calculator/baseofbase/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/java/src/main/resources/software/amazon/jsii/tests/calculator/baseofbase/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/java/software/amazon/jsii/tests/calculator/base/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/resources/software/amazon/jsii/tests/calculator/base/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/resources/software/amazon/jsii/tests/calculator/lib/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
Labels: contribution/core, pr/ready-to-merge

#1603 chore: merge release/1.4.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash, pr/ready-to-merge

#1607 chore(release): 1.4.1
  CHANGELOG.md
  lerna.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/dotnet-runtime/src/Directory.Build.targets
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/ruby-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/java/src/main/java/software/amazon/jsii/tests/calculator/baseofbase/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/java/src/main/resources/software/amazon/jsii/tests/calculator/baseofbase/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/java/software/amazon/jsii/tests/calculator/base/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/resources/software/amazon/jsii/tests/calculator/base/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/resources/software/amazon/jsii/tests/calculator/lib/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/$Module.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: pr/no-squash

#1608 chore: merge release/1.4.1 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash, pr/ready-to-merge

#1557 fix(jsii): unable to use type from dependencies' submodules
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/lib/submodule/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/submodules.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/IReflectable.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/IReflectableEntry.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/IReflectableProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/ReflectableEntry.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/ReflectableEntryProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/Reflector.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/submodule/IReflectable.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/submodule/ReflectableEntry.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/submodule/Reflector.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/resources/software/amazon/jsii/tests/calculator/lib/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UpcasingReflectable.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UpcasingReflectable.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/composition/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/derived_class_has_no_properties/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_only_interface/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/back_references/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/deeply_nested/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii/lib/assembler.ts
Labels: contribution/core, effort/small, module/compiler, pr/ready-to-merge
