Repository aws/jsii, pull requests merged in 2020-05, with the labels that each got.

#1637 chore(release): 1.5.0
  CHANGELOG.md
  lerna.json
  package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/lib/submodule/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/codemaker/package.json
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/submodules.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/IReflectable.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/IReflectableEntry.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/IReflectableProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/ReflectableEntry.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/ReflectableEntryProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CalculatorNamespace/LibNamespace/Submodule/Reflector.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/submodule/IReflectable.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/submodule/ReflectableEntry.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/submodule/Reflector.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/resources/software/amazon/jsii/tests/calculator/lib/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UpcasingReflectable.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UpcasingReflectable.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/composition/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/derived_class_has_no_properties/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_only_interface/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/back_references/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/deeply_nested/__init__.py
  packages/jsii-reflect/package.json
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#1638 chore: merge release/1.5.0 to master
  CHANGELOG.md
  lerna.json
Labels: contribution/core, pr/no-squash, pr/ready-to-merge

#1643 docs: fixed SDTIN on docs/runtime-architecture.md
  docs/runtime-architecture.md
Labels: pr/ready-to-merge

#1624 docs: Missing links to @jsii/runtime
  CONTRIBUTING.md
Labels: pr/ready-to-merge

#1645 feat(python): add explicit return type to setters
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/composition/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/derived_class_has_no_properties/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
Labels: contribution/core, language/python, pr/ready-to-merge

#1651 chore: improve error message when a non-jsii dependency is not bundled
  packages/jsii/lib/project-info.ts
Labels: contribution/core, pr/ready-to-merge

#1653 feat(java): use covariant types for collection elements
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJacksonStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DerivedStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NullShouldBeTreatedAsUndefinedData.java
Labels: contribution/core, language/java, pr/ready-to-merge

#1654 feat(java): add a Builder<T> interface implemented by all builders
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Builder.java
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base-of-base/java/src/main/java/software/amazon/jsii/tests/calculator/baseofbase/VeryBaseProps.java
  packages/jsii-pacmak/test/expected.jsii-calc-base/java/src/main/java/software/amazon/jsii/tests/calculator/base/BaseProps.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/MyFirstStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/StructWithOnlyOptionals.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/lib/submodule/ReflectableEntry.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/AmbiguousParameters.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Calculator.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/CalculatorProps.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ChildStruct982.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJacksonStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DeprecatedStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DerivedStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DiamondInheritanceBaseLevelStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DiamondInheritanceFirstMidLevelStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DiamondInheritanceSecondMidLevelStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DiamondInheritanceTopLevelStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/EraseUndefinedHashValuesOptions.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ExperimentalStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ExtendsInternalInterface.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ExternalStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/Greetee.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ImplictBaseOfBase.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/LoadBalancedFargateServiceProps.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NestedStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NullShouldBeTreatedAsUndefinedData.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/OptionalStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/OptionalStructConsumer.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ParentStruct982.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/RootStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SecondLevelStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SmellyStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StableStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StructA.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StructB.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StructParameterType.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/StructWithJavaReservedWords.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SupportsNiceJavaBuilder.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SupportsNiceJavaBuilderProps.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/SupportsNiceJavaBuilderWithRequiredProps.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/TopLevelStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UnionProperties.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/interface_in_namespace_includes_classes/Hello.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/interface_in_namespace_only_interface/Hello.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/back_references/MyClassReference.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/submodule/child/Structure.java
Labels: contribution/core, effort/small, language/java, module/pacmak, pr/ready-to-merge

#1528 fix(python): imports between subpackages are broken
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/spec/lib/assembly.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/lib/targets/python/util.ts
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-base/python/src/scope/jsii_calc_base/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/_jsii/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/composition/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/derived_class_has_no_properties/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_includes_classes/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/interface_in_namespace_only_interface/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/back_references/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/child/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/submodule/nested_submodule/deeply_nested/__init__.py
  packages/jsii-pacmak/test/targets/python/type-name.test.ts
Labels: contribution/core, language/python, pr/ready-to-merge

#1675 Revert "feat(java): use covariant types for collection elements"
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/ConfusingToJacksonStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/DerivedStruct.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/NullShouldBeTreatedAsUndefinedData.java
Labels: contribution/core

#1663 fix(jsii): dependency submodules are not tagged
  packages/jsii/lib/assembler.ts
Labels: bug, effort/small, module/compiler, pr/ready-to-merge

#1676 chore: make integration test use local runtimes
  packages/@jsii/integ-test/test/build-cdk.test.ts
Labels: contribution/core, pr/ready-to-merge

#1655 fix(dotnet): F# dictionaries cause NullReferenceException
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Tests.fs
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.sln
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs
Labels: contribution/core, pr/ready-to-merge

#1677 fix: package runtimes as private for integ test
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/python-runtime/package.json
Labels: contribution/core, pr/do-not-merge

#1679 chore(pacmak): fix local runtime detection
  .prettierrc.yaml
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/java.ts
Labels: bug, contribution/core, effort/small, module/pacmak, pr/ready-to-merge

#1650 chore(repo): add stale github action
  .github/workflows/close-stale-issues.yml
Labels: contribution/core, pr/ready-to-merge

#1692 feat(jsii): use incremental builders
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/JsonDictionaryBase.cs
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/jsii-calc/package.json
  packages/jsii/lib/compiler.ts
Labels: contribution/core, effort/small, module/compiler, pr/ready-to-merge

#1691 chore: remove @jsii/ruby-runtime
  .dependabot/config.yml
  CONTRIBUTING.md
  packages/@jsii/ruby-runtime/.gitignore
  packages/@jsii/ruby-runtime/CHANGELOG.md
  packages/@jsii/ruby-runtime/generate.sh
  packages/@jsii/ruby-runtime/package.json
  packages/@jsii/ruby-runtime/project/.bundle/config
  packages/@jsii/ruby-runtime/project/.rubocop.yml
  packages/@jsii/ruby-runtime/project/Gemfile
  packages/@jsii/ruby-runtime/project/Gemfile.lock
  packages/@jsii/ruby-runtime/project/config
  packages/@jsii/ruby-runtime/project/jsii_runtime.gemspec
  packages/@jsii/ruby-runtime/project/lib/jsii_runtime.rb
  packages/@jsii/ruby-runtime/project/lib/jsii_runtime/errors.rb
  packages/@jsii/ruby-runtime/project/test/jsii_runtime_test.rb
  packages/@jsii/ruby-runtime/project/test/suite.rb
  packages/jsii-pacmak/lib/targets/index.ts
  packages/jsii-pacmak/lib/targets/ruby.ts
Labels: contribution/core

#1330 fix(python): `self` as property name leads to assignment error
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PythonSelf/ClassWithSelf.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PythonSelf/ClassWithSelfKwarg.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PythonSelf/IInterfaceWithSelf.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PythonSelf/IInterfaceWithSelfProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PythonSelf/IStructWithSelf.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PythonSelf/StructWithSelf.cs
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/PythonSelf/StructWithSelfProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/python_self/ClassWithSelf.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/python_self/ClassWithSelfKwarg.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/python_self/IInterfaceWithSelf.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/python_self/StructWithSelf.java
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/resources/software/amazon/jsii/tests/calculator/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/python_self/__init__.py
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii/lib/reserved-words.ts
Labels: bug, language/python, pr/ready-to-merge

#1702 fix(kernel): error raised during rename operation on win32
  packages/@jsii/kernel/lib/kernel.ts
Labels: bug, contribution/core, effort/small, pr/ready-to-merge

#1690 feat: allow per-submodule naming configuration
  docs/specifications/2-type-system.md
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@scope/jsii-calc-lib/lib/submodule/.jsiirc.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnettyperesolver.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CustomSubmoduleName/IReflectable.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CustomSubmoduleName/IReflectableEntry.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CustomSubmoduleName/IReflectableProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CustomSubmoduleName/ReflectableEntry.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CustomSubmoduleName/ReflectableEntryProxy.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/Amazon/JSII/Tests/CustomSubmoduleName/Reflector.cs
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/custom_submodule_name/IReflectable.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/custom_submodule_name/ReflectableEntry.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/java/software/amazon/jsii/tests/calculator/custom_submodule_name/Reflector.java
  packages/jsii-pacmak/test/expected.jsii-calc-lib/java/src/main/resources/software/amazon/jsii/tests/calculator/lib/$Module.txt
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/setup.py
  packages/jsii-pacmak/test/expected.jsii-calc-lib/python/src/scope/jsii_calc_lib/custom_submodule_name/__init__.py
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/.jsii
  packages/jsii-pacmak/test/expected.jsii-calc/dotnet/Amazon.JSII.Tests.CalculatorPackageId/Amazon/JSII/Tests/CalculatorNamespace/UpcasingReflectable.cs
  packages/jsii-pacmak/test/expected.jsii-calc/java/src/main/java/software/amazon/jsii/tests/calculator/UpcasingReflectable.java
  packages/jsii-pacmak/test/expected.jsii-calc/python/src/jsii_calc/__init__.py
  packages/jsii/lib/assembler.ts
Labels: contribution/core, effort/medium, module/compiler, module/pacmak, pr/ready-to-merge
