Repository aws/jsii, pull requests merged in 2020-09, with the labels that each got.

#1951 feat(jsii): reflect stabilities in doc comment summaries
  packages/@scope/jsii-calc-base-of-base/lib/index.ts
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/_utils.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/docs.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/ts-comment-replacer.ts
  packages/jsii/test/__snapshots__/negatives.test.ts.snap
  packages/jsii/test/docs.test.ts
Labels: contribution/core

#1973 fix(pacmak): go bad local package imports
  packages/@jsii/kernel/test/kernel.test.ts
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/golang/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core

#1994 feat: add go to superchain
  superchain/Dockerfile
  superchain/README.md
Labels: contribution/core

#2004 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: contribution/core, dependencies

#2006 chore: use relative imports in the Python runtime
  packages/@jsii/python-runtime/src/jsii/__meta__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/base.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
Labels: contribution/core, effort/small

#2007 chore: remove console.log from go pacmak gen
  packages/jsii-pacmak/lib/targets/golang/documentation.ts
Labels: contribution/core

#2013 feat(pacmak): retry select external command invocations
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/test/util.test.ts
Labels: contribution/core, effort/small, module/pacmak, p1, pr/ready-to-merge

#1996 feat(go): runtime library definition
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/LICENSE
  packages/@jsii/go-runtime/NOTICE
  packages/@jsii/go-runtime/build-tools/_constants.ts
  packages/@jsii/go-runtime/build-tools/gen-calc.ts
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-calc-test/main.go
  packages/@jsii/go-runtime/jsii-experimental/api.go
  packages/@jsii/go-runtime/jsii-experimental/client.go
  packages/@jsii/go-runtime/jsii-experimental/client_test.go
  packages/@jsii/go-runtime/jsii-experimental/embedded/.gitkeep
  packages/@jsii/go-runtime/jsii-experimental/no_op.go
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/golang/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  yarn.lock
Labels: contribution/core

#2017 chore: optimize jsii/superchain layers for size
  superchain/Dockerfile
Labels: contribution/core, effort/small, p2, pr/ready-to-merge

#2024 chore: rename go target
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/documentation.ts
  packages/jsii-pacmak/lib/targets/go/emit-context.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/readme-file.ts
  packages/jsii-pacmak/lib/targets/go/runtime.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/index.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/lib/targets/index.ts
Labels: language/go

#2026 chore: make yarn-upgrade use "minor" target for prod deps
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core, dependencies, pr/ready-to-merge

#2018 chore: kernel API type translations
  packages/@jsii/go-runtime/jsii-experimental/api.go
  packages/@jsii/go-runtime/jsii-experimental/client.go
Labels: language/go

#2035 fix(go): correctly handle void return types
  packages/@jsii/go-runtime/jsii-calc-test/main.go
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/go/runtime.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, language/go

#2034 chore: start testing with .NET 5
  .github/workflows/main.yml
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
Labels: contribution/core, language/dotnet, pr/ready-to-merge

#2044 chore: run integration test with node 10
  .github/workflows/main.yml
Labels: contribution/core

#2038 chore: npm-check-updates && yarn upgrade
  package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2041 chore(go): generate module embedding
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: language/go, pr/ready-to-merge

#2031 chore(go): correctly generate statics
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: language/go, pr/ready-to-merge

#2028 chore(python): documentation improvements
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/targets/python/type-name.test.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: contribution/core, documentation, effort/medium, language/python, pr/ready-to-merge

#2054 chore: use "full" version number for .NET 5.0-rc.1 SDK
  .github/workflows/main.yml
Labels: contribution/core

#2058 fix(dontet): iso-8601 date strings get turned into DateTime
  packages/@jsii/dotnet-runtime-test/generate.sh
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.sln
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Client.cs
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-calc/lib/date.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: bug, contribution/core, effort/small, language/dotnet, module/runtime, p1

#2062 chore(merge-back): 1.13.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash
