Repository aws/jsii, pull requests merged in 2020-08, with the labels that each got.

#1853 chore(merge-back): 1.10.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/ready-to-merge

#1852 chore: npm-check-updates && yarn upgrade
  package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#1850 fix(rosetta): use of keyword 'lambda' produces invalid Python code
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/test/translations/identifiers/keyword.cs
  packages/jsii-rosetta/test/translations/identifiers/keyword.java
  packages/jsii-rosetta/test/translations/identifiers/keyword.py
  packages/jsii-rosetta/test/translations/identifiers/keyword.ts
Labels: contribution/core, pr/ready-to-merge

#1849 chore: no more eslint warn rules
  eslint-config.yaml
  packages/jsii-rosetta/lib/jsii/assemblies.ts
Labels: contribution/core

#1817 chore(pacmak): improve error messaging
  .eslintrc.yaml
  packages/jsii-pacmak/lib/util.ts
Labels: contribution/core, effort/small, module/pacmak

#1864 chore: stop running generated Python though `black`
  packages/codemaker/lib/codemaker.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
  packages/jsii-pacmak/test/jsii-pacmak.test.ts
  packages/jsii-pacmak/test/targets/python.test.ts
  yarn.lock
Labels: contribution/core, effort/small, feature-request, language/python, module/pacmak, pr/ready-to-merge

#1870 chore: run integration tests as part of workflow
  .github/workflows/main.yml
  .mergify/config.yml
Labels: effort/small, ops-excellence

#1718 fix(dotnet): "Could not infer JSII type for .NET type 'AnonymousObject'"
  packages/@jsii/dotnet-runtime-test/.gitignore
  packages/@jsii/dotnet-runtime-test/.npmignore
  packages/@jsii/dotnet-runtime-test/generate.sh
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime-test/test/NuGet.Config
  packages/@jsii/dotnet-runtime-test/test/NuGet.config
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/ValueConverter.cs
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: bug, contribution/core, pr/ready-to-merge

#1866 fix(jsii): unable to use nested types from dependencies
  .github/workflows/main.yml
  packages/@scope/jsii-calc-lib/lib/submodule/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/nested-class.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-pacmak/test/jsii-pacmak.test.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii/lib/assembler.ts
Labels: bug, contribution/core, effort/small, module/compiler, pr/do-not-merge

#1876 feat(jsii): prohibit changing visibility when overriding
  packages/jsii/lib/validator.ts
  packages/jsii/test/__snapshots__/negatives.test.js.snap
  packages/jsii/test/negatives/neg.override-changes-visibility.ts
Labels: contribution/core, effort/small, feature-request, module/compiler, pr/ready-to-merge

#1871 fix(jsii): README.md filename is case sensitive
  packages/jsii/lib/assembler.ts
  packages/jsii/test/compiler.test.ts
  packages/jsii/test/negatives/Readme.md
Labels: contribution/core, pr/ready-to-merge

#1878 chore: run Python runtime through `black`
  packages/@jsii/python-runtime/build-tools/_constants.ts
  packages/@jsii/python-runtime/build-tools/deps.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/base.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/src/jsii/_reference_map.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/src/jsii/errors.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/python-runtime/tests/test_python.py
Labels: contribution/core, language/python, pr/ready-to-merge

#1879 chore: npm-check-updates && yarn upgrade
  .github/workflows/yarn-upgrade.yml
  .gitignore
  package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/bundle.sh
  packages/@jsii/runtime/lib/host.ts
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: contribution/core, dependencies

#1885 chore: add workflow to validate jsii/superchain image
  .github/workflows/main.yml
  .github/workflows/superchain.yml
  superchain/Dockerfile
Labels: contribution/core, ops-excellence, pr/ready-to-merge

#1902 feat(python): allow setting additional trove classifiers
  docs/configuration.md
  packages/@jsii/kernel/test/kernel.test.ts
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Labels: contribution/core, feature-request, language/python, module/pacmak

#1890 feat(jsii-pacmak): option to disallow parallel generation of languages
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/test/build-test.sh
Labels: contribution/core, pr/ready-to-merge

#1912 chore(superchain): install awscli from pip instead of yum
  superchain/Dockerfile
Labels: contribution/core

#1913 fix(dotnet): crash when TEMP contains certain unicode characters
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/INodeProcess.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
  packages/@jsii/runtime/lib/sync-stdio.ts
Labels: contribution/core, pr/ready-to-merge

#1891 fix(pacmak): `EMFILE` error when running `jsii-pacmak`
  packages/jsii-pacmak/lib/dependency-graph.ts
  packages/jsii-pacmak/lib/target.ts
  packages/jsii-pacmak/test/dependency-graph.test.ts
Labels: bug, contribution/core, effort/small, module/pacmak, pr/ready-to-merge

#1917 chore(merge-back): 1.11.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#1918 chore: dial down integration test
  .github/workflows/main.yml
  packages/jsii-rosetta/lib/tablets/tablets.ts
Labels: contribution/core, pr/ready-to-merge

#1920 chore: npm-check-updates && yarn upgrade
  packages/@jsii/runtime/package.json
  yarn.lock
Labels: contribution/core, dependencies

#1906 fix(java): module "<module name>" not found error
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/java-runtime-test/pom.xml.t.js
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/ComplianceSuiteHarness.java
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/ReloadingClassLoader.java
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/JsiiClientTest.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectMapper.java
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@jsii/runtime/test/__snapshots__/kernel-host.test.js.snap
  packages/@jsii/runtime/test/kernel-host.test.ts
  packages/@scope/jsii-calc-base-of-base/lib/index.ts
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/lib/submodule/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: bug, contribution/core, effort/small, language/java, module/runtime, pr/ready-to-merge

#1551 feat(golang): introduce Golang code generation
  docs/configuration.md
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/codemaker/lib/codemaker.ts
  packages/codemaker/test/source.test.ts
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-pacmak/lib/targets/golang.ts
  packages/jsii-pacmak/lib/targets/golang/documentation.ts
  packages/jsii-pacmak/lib/targets/golang/emit-context.ts
  packages/jsii-pacmak/lib/targets/golang/package.ts
  packages/jsii-pacmak/lib/targets/golang/readme-file.ts
  packages/jsii-pacmak/lib/targets/golang/types/class.ts
  packages/jsii-pacmak/lib/targets/golang/types/enum.ts
  packages/jsii-pacmak/lib/targets/golang/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/golang/types/go-type.ts
  packages/jsii-pacmak/lib/targets/golang/types/index.ts
  packages/jsii-pacmak/lib/targets/golang/types/interface.ts
  packages/jsii-pacmak/lib/targets/golang/types/struct.ts
  packages/jsii-pacmak/lib/targets/golang/types/type-field.ts
  packages/jsii-pacmak/lib/targets/golang/util.ts
  packages/jsii-pacmak/lib/targets/index.ts
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
  packages/jsii-reflect/lib/type.ts
Labels: contribution/core, pr/do-not-merge

#1932 fix(kernel): calling super.property unexpectedly returns `undefined`
  packages/@jsii/kernel/lib/kernel.ts
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@jsii/runtime/package.json
  packages/@jsii/runtime/test/__snapshots__/kernel-host.test.ts.snap
  packages/@jsii/runtime/test/playback.test.ts
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: bug, contribution/core, effort/small, module/kernel, p1, pr/ready-to-merge

#1903 fix(jsii): class members named after the class result in illegal C#
  docs/typescript-restrictions.md
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/calculator.ts
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-diff/test/classes.test.ts
  packages/jsii-diff/test/structs.test.ts
  packages/jsii-diff/test/util.ts
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-reflect/test/independent.test.ts
  packages/jsii-reflect/test/type-system.test.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/test/__snapshots__/negatives.test.js.snap
  packages/jsii/test/docs.test.ts
  packages/jsii/test/negatives/neg.implementation-changes-types.4.ts
  packages/jsii/test/negatives/neg.implementation-changes-types.5.ts
  packages/jsii/test/negatives/neg.inheritance-changes-types.4.ts
  packages/jsii/test/negatives/neg.inheritance-changes-types.5.ts
  packages/jsii/test/negatives/neg.member-named-after-type.ts
Labels: bug, contribution/core, effort/small, module/compiler, p1

#1931 feat(jsii): standardized error messages
  packages/jsii-reflect/lib/callable.ts
  packages/jsii-reflect/lib/module-like.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/emitter.ts
  packages/jsii/lib/index.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/utils.ts
  packages/jsii/lib/validator.ts
  packages/jsii/package.json
  packages/jsii/test/__snapshots__/negatives.test.js.snap
  packages/jsii/test/__snapshots__/negatives.test.ts.snap
  packages/jsii/test/negatives.test.ts
  packages/jsii/test/negatives/mylib.d.ts
  packages/jsii/test/negatives/neg.expose-unexported-type-external.ts
  tsconfig-base.json
Labels: contribution/core, effort/medium, feature-request, module/compiler, pr/ready-to-merge

#1952 chore(go): generate constructors for GoClass
  packages/jsii-pacmak/lib/targets/golang/types/class.ts
  packages/jsii-pacmak/lib/targets/golang/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/golang/types/go-type.ts
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Labels: pr/ready-to-merge

#1954 chore(go): code generation for extensions
  packages/jsii-pacmak/lib/targets/golang/types/class.ts
  packages/jsii-pacmak/lib/targets/golang/types/go-type.ts
  packages/jsii-pacmak/lib/targets/golang/types/interface.ts
  packages/jsii-pacmak/test/__snapshots__/jsii-pacmak.test.ts.snap
Labels: pr/ready-to-merge

#1964 chore(merge-back): 1.12.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#1960 chore: switch `jsii-calc` to `stable`
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
Labels: contribution/core, pr/ready-to-merge

#1956 feat(pacmak): go module resolution & compiler fixes
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/golang.ts
  packages/jsii-pacmak/lib/targets/golang/package.ts
  packages/jsii-pacmak/lib/targets/golang/runtime.ts
  packages/jsii-pacmak/lib/targets/golang/types/class.ts
  packages/jsii-pacmak/lib/targets/golang/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/golang/types/go-type.ts
  packages/jsii-pacmak/lib/targets/golang/types/interface.ts
  packages/jsii-pacmak/lib/targets/golang/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core
