Repository aws/jsii, pull requests merged in 2021-10, with the labels that each got.

#3014 chore: set response-requested length to 2 and closing-soon to 5
  .github/workflows/close-stale-issues.yml
Labels: pr/ready-to-merge

#3017 chore: auto approve dependabot
  .github/workflows/auto-approve.yml
Labels: pr/ready-to-merge, contribution/core

#3018 chore(superchain): set UID and GID of superchain user
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3022 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: dependencies, contribution/core

#3024 chore(merge-back): 1.36.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3032 feat(pacmak): opt out of jsii assembly validation
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/lib/util.ts
Labels: pr/ready-to-merge, contribution/core

#3033 chore(release): 1.37.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-reflect/lib/_memoized.ts
  packages/jsii-reflect/lib/interface.ts
  packages/jsii-reflect/lib/module-like.ts
  packages/jsii-reflect/lib/reference-type.ts
  packages/jsii-reflect/lib/type.ts
  packages/jsii-reflect/tsconfig.json
Labels: pr/ready-to-merge, pr/no-squash
