Repository aws/jsii, pull requests merged in 2021-11, with the labels that each got.

#3110 chore: simplify auto approve mechanism
  .github/workflows/auto-approve.yml
  .github/workflows/pr-labeler.yml
Labels: pr/ready-to-merge, contribution/core

#3112 fix(jsii): unexpected deprecated warnings when a deprecated interface is extended
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: contribution/core

#3101 feat(rosetta): reuse translation results from a cache
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/convert.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/extract_worker.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/commands/read.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/jsii/fingerprinting.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/index.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/markdown/extract-snippets.ts
  packages/jsii-rosetta/lib/markdown/replace-code-renderer.ts
  packages/jsii-rosetta/lib/markdown/replace-typescript-transform.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/lib/snippet-selectors.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/tablets/key.ts
  packages/jsii-rosetta/lib/tablets/schema.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/fixtures.test.ts
  packages/jsii-rosetta/test/rosetta.test.ts
  packages/jsii-rosetta/test/snippet-selectors.test.ts
  packages/jsii-rosetta/test/testutil.ts
  packages/jsii-rosetta/test/translate.test.ts
  packages/jsii-rosetta/test/translations.test.ts
Labels: pr/ready-to-merge, contribution/core

#3114 chore(release): 1.42.0
  .github/workflows/auto-approve.yml
  .github/workflows/pr-labeler.yml
  CHANGELOG.md
  lerna.json
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/go.sum
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/convert.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/extract_worker.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/commands/read.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/jsii/fingerprinting.ts
  packages/jsii-rosetta/lib/jsii/jsii-types.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/index.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/visualize.ts
  packages/jsii-rosetta/lib/markdown/extract-snippets.ts
  packages/jsii-rosetta/lib/markdown/javadoc-renderer.ts
  packages/jsii-rosetta/lib/markdown/replace-code-renderer.ts
  packages/jsii-rosetta/lib/markdown/replace-typescript-transform.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/lib/snippet-selectors.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/tablets/key.ts
  packages/jsii-rosetta/lib/tablets/schema.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/fixtures.test.ts
  packages/jsii-rosetta/test/markdown/javadoc.test.ts
  packages/jsii-rosetta/test/rosetta.test.ts
  packages/jsii-rosetta/test/snippet-selectors.test.ts
  packages/jsii-rosetta/test/testutil.ts
  packages/jsii-rosetta/test/translate.test.ts
  packages/jsii-rosetta/test/translations.test.ts
  packages/jsii-rosetta/test/translations/expressions/array_index.cs
  packages/jsii-rosetta/test/translations/expressions/array_index.java
  packages/jsii-rosetta/test/translations/expressions/array_index.py
  packages/jsii-rosetta/test/translations/expressions/array_index.ts
  packages/jsii-rosetta/test/translations/statements/vararg_any_call.cs
  packages/jsii-rosetta/test/translations/statements/vararg_any_call.java
  packages/jsii-rosetta/test/translations/statements/vararg_any_call.py
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, pr/no-squash

#3115 chore(merge-back): 1.42.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3113 chore: using queue action in the 'Synchronize that PR to upstream and merge it (no-squash)' rule
  .mergify/config.yml
Labels: pr/ready-to-merge, contribution/core

#3119 fix(rosetta): crashes on outdated tablet files in a package
  packages/jsii-rosetta/lib/rosetta.ts
Labels: pr/ready-to-merge, contribution/core

#3126 fix(rosetta): `infuse` creates untranslated examples
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
Labels: pr/ready-to-merge, contribution/core

#3128 fix(rosetta): stop skipping example values
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
Labels: pr/ready-to-merge, contribution/core

#3129 fix(rosetta): remember live-translated snippets without fixtures
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/test/rosetta.test.ts
Labels: pr/ready-to-merge, contribution/core

#3121 fix(pacmak): development version cannot pack java
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/targets/version-utils.test.ts
Labels: pr/ready-to-merge, contribution/core

#3125 fix(pacmak): add 'silly' loglevel for command output
  packages/jsii-pacmak/lib/logging.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/lib/util.ts
Labels: pr/ready-to-merge, contribution/core

#3124 fix(pacmak): re-introduce parallelism for Python and Go builds
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/targets/index.ts
  packages/jsii-pacmak/lib/toposort.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/test/npm-modules.test.ts
  packages/jsii-rosetta/test/record-references.test.ts
Labels: pr/ready-to-merge, contribution/core

#3131 feat(rosetta): find fixtures based on submodules
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii-rosetta/test/record-references.test.ts
  packages/jsii-rosetta/test/syntax-counter.test.ts
  packages/jsii-rosetta/test/testutil.ts
Labels: pr/ready-to-merge, contribution/core

#3130 fix(pacmak): API locations for inherited members are incorrect
  packages/jsii-pacmak/lib/targets/_utils.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
Labels: pr/ready-to-merge, contribution/core

#3141 chore(release): 1.43.0
  .mergify/config.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/logging.ts
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/lib/targets/_utils.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/index.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/lib/toposort.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/npm-modules.test.ts
  packages/jsii-pacmak/test/targets/version-utils.test.ts
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii-rosetta/test/record-references.test.ts
  packages/jsii-rosetta/test/rosetta.test.ts
  packages/jsii-rosetta/test/syntax-counter.test.ts
  packages/jsii-rosetta/test/testutil.ts
Labels: pr/ready-to-merge, pr/no-squash

#3142 chore: fix pr-labeler permissions
  .github/workflows/pr-labeler.yml
Labels: pr/ready-to-merge, contribution/core

#3143 chore(merge-back): 1.43.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3145 fix(rosetta): snippet throughput incorrect
  packages/jsii-rosetta/lib/commands/extract.ts
Labels: pr/ready-to-merge, contribution/core

#3149 fix(rosetta): `didCompile` evaluates to true when compilation not attempted
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/test/translate.test.ts
Labels: pr/ready-to-merge, contribution/core

#3148 fix(pacmak): remove disclaimer on compiling examples
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/index.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: pr/ready-to-merge, contribution/core

#3147 fix(jsii): incorrectly allowed unexported type in constructor params
  packages/jsii/lib/node-bindings.ts
  packages/jsii/lib/validator.ts
  packages/jsii/test/__snapshots__/negatives.test.ts.snap
  packages/jsii/test/negatives/_unexported.ts
  packages/jsii/test/negatives/neg.expose-unexported-type-constructor-param.ts
Labels: pr/ready-to-merge, contribution/core

#3133 fix(pacmak): Support more than 255 properties for interfaces in Java
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
Labels: pr/ready-to-merge

#3151 fix: dependency submodules may not be discovered
  lerna.json
  package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  regression-tests/@barrelimports/consumer/.gitignore
  regression-tests/@barrelimports/consumer/README.md
  regression-tests/@barrelimports/consumer/lib/index.ts
  regression-tests/@barrelimports/consumer/package.json
  regression-tests/@barrelimports/provider/.gitignore
  regression-tests/@barrelimports/provider/README.md
  regression-tests/@barrelimports/provider/lib/index.ts
  regression-tests/@barrelimports/provider/lib/namespaced.ts
  regression-tests/@barrelimports/provider/package.json
  regression-tests/README.md
Labels: pr/ready-to-merge, contribution/core

#3156 fix(rosetta): gets confused by type unions
  packages/jsii-rosetta/lib/jsii/jsii-types.ts
  packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.cs
  packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.java
  packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.py
  packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.ts
Labels: pr/ready-to-merge, contribution/core

#3157 fix: deprecation warnings are generated even when one property is not deprecated
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3161 feat(rosetta): expose the 'extract' API
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/extract_worker.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/translate_all.ts
  packages/jsii-rosetta/lib/translate_all_worker.ts
  packages/jsii-rosetta/lib/typescript/visible-spans.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/jsii/visible-spans.test.ts
  packages/jsii-rosetta/test/rosetta-translator.test.ts
  packages/jsii-rosetta/test/snippet.test.ts
  packages/jsii-rosetta/test/testutil.ts
Labels: pr/ready-to-merge, contribution/core

#3159 chore: explain "infuse" in rosetta README
  packages/jsii-rosetta/README.md
Labels: pr/ready-to-merge, contribution/core

#3158 chore(rosetta): suppress diagnostics after a certain point
  packages/jsii-rosetta/lib/util.ts
Labels: pr/ready-to-merge, contribution/core

#3163 fix(rosetta): cache source file parses
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
Labels: pr/ready-to-merge, contribution/core

#3165 chore(merge-back): 1.44.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3170 revert: "fix: dependency submodules may not be discovered (#3151)"
  lerna.json
  package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  regression-tests/@barrelimports/consumer/.gitignore
  regression-tests/@barrelimports/consumer/README.md
  regression-tests/@barrelimports/consumer/lib/index.ts
  regression-tests/@barrelimports/consumer/package.json
  regression-tests/@barrelimports/provider/.gitignore
  regression-tests/@barrelimports/provider/README.md
  regression-tests/@barrelimports/provider/lib/index.ts
  regression-tests/@barrelimports/provider/lib/namespaced.ts
  regression-tests/@barrelimports/provider/package.json
  regression-tests/README.md
Labels: pr/ready-to-merge, contribution/core

#3175 chore(release): 1.44.1
  CHANGELOG.md
  lerna.json
  package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  regression-tests/@barrelimports/consumer/.gitignore
  regression-tests/@barrelimports/consumer/README.md
  regression-tests/@barrelimports/consumer/lib/index.ts
  regression-tests/@barrelimports/consumer/package.json
  regression-tests/@barrelimports/provider/.gitignore
  regression-tests/@barrelimports/provider/README.md
  regression-tests/@barrelimports/provider/lib/index.ts
  regression-tests/@barrelimports/provider/lib/namespaced.ts
  regression-tests/@barrelimports/provider/package.json
  regression-tests/README.md
Labels: pr/ready-to-merge, contribution/core, pr/no-squash

#3177 chore: fix changelog heading level
  CHANGELOG.md
Labels: contribution/core

#3174 fix(rosetta): types from submodules not recognized properly
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/lib/tablets/key.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/record-references.test.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/index.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/lib/utils.ts
  packages/jsii/test/symbol-identifiers.test.ts
Labels: pr/ready-to-merge, contribution/core

#3179 chore(merge-back): 1.44.1
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3180 fix(pacmak): dotnet code docs loses indentation
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
Labels: pr/ready-to-merge, contribution/core

#3182 fix(rosetta): diagnostics not showing
  packages/jsii-rosetta/lib/util.ts
Labels: pr/ready-to-merge, contribution/core

#3183 fix: C# NamespaceDoc emitted to wrong location
  packages/@jsii/spec/lib/assembly.ts
  packages/@scope/jsii-calc-lib/lib/submodule/README.md
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii/lib/assembler.ts
Labels: pr/ready-to-merge, contribution/core

#3181 fix(pacmak): Generate Relative Module Imports in Python
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: pr/ready-to-merge

#3184 fix(jsii): require statement for the warning file is generated when it's not used
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3187 chore(release): 1.44.2
  CHANGELOG.md
  lerna.json
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core, pr/no-squash

#3176 fix(rosetta): Rosetta is not submodule-aware
  packages/@jsii/spec/lib/assembly.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/jsii/jsii-types.ts
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/jsii/packages.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/lib/typescript/imports.ts
  packages/jsii-rosetta/lib/typescript/types.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/jsii-imports.test.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii-rosetta/test/record-references.test.ts
  packages/jsii-rosetta/test/rosetta-translator.test.ts
  packages/jsii-rosetta/test/syntax-counter.test.ts
  packages/jsii-rosetta/test/testutil.ts
  packages/jsii-rosetta/test/translations.test.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/test/symbol-identifiers.test.ts
Labels: pr/ready-to-merge, contribution/core

#3186 chore: record missing contributions
  .all-contributorsrc
  README.md
Labels: pr/ready-to-merge, contribution/core, pr/auto-approve

#3189 chore(release): 1.45.0
  .all-contributorsrc
  CHANGELOG.md
  README.md
  lerna.json
  packages/@jsii/spec/lib/assembly.ts
  packages/@scope/jsii-calc-lib/lib/submodule/README.md
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/jsii/jsii-types.ts
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/jsii/packages.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/lib/tablets/key.ts
  packages/jsii-rosetta/lib/typescript/imports.ts
  packages/jsii-rosetta/lib/typescript/types.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/jsii-imports.test.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii-rosetta/test/record-references.test.ts
  packages/jsii-rosetta/test/rosetta-translator.test.ts
  packages/jsii-rosetta/test/syntax-counter.test.ts
  packages/jsii-rosetta/test/testutil.ts
  packages/jsii-rosetta/test/translations.test.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/index.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/lib/utils.ts
  packages/jsii/test/symbol-identifiers.test.ts
Labels: pr/ready-to-merge, pr/no-squash

#3190 fix(rosetta): enum resolution breaks for properties
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/test/jsii-imports.test.ts
Labels: pr/ready-to-merge, contribution/core

#3191 chore(merge-back): 1.45.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3193 fix(rosetta): `extract` ignores `--compile` option
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
Labels: pr/ready-to-merge, contribution/core

#3194 feat(reflect): add `allTypes` accessor
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/test/independent.test.ts
  packages/jsii-reflect/test/type-system.test.ts
  packages/jsii-reflect/test/util.ts
  packages/jsii/lib/helpers.ts
Labels: pr/ready-to-merge, contribution/core

#3195 chore(release): 1.46.0
  CHANGELOG.md
  lerna.json
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
Labels: pr/no-squash

#3135 chore: auto approve yarn upgrade PR's
  .github/workflows/yarn-upgrade.yml
Labels: pr/ready-to-merge, contribution/core

#3201 chore: fixup @kaizen3031593 name
  .all-contributorsrc
  README.md
Labels: pr/ready-to-merge, contribution/core

#3200 feat(rosetta): metadata tag for fixtures in docs
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
Labels: pr/ready-to-merge, contribution/core

#3203 chore: upgrade Maven to 3.8.4
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3206 fix(jsii): deprecation message is not displayed for deprecated classes
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3099 chore: npm-check-updates && yarn upgrade
  eslint-config.yaml
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/lib/validate-assembly.ts
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/lib/calculator.ts
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: dependencies, contribution/core, pr/auto-approve

#3209 fix(jsii): constants can't mix letters and digits
  packages/jsii/lib/validator.ts
  packages/jsii/test/enums.test.ts
Labels: pr/ready-to-merge, contribution/core

#3218 fix(rosetta): use `--compile` flag by default
  packages/jsii-rosetta/bin/jsii-rosetta.ts
Labels: pr/ready-to-merge, contribution/core

#3210 feat(rosetta): reuse output file as additional cache and introduce `--infuse` option for `extract`
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/testutil.ts
Labels: pr/ready-to-merge, contribution/core
