Repository aws/jsii, pull requests merged in 2021-09, with the labels that each got.

#2946 chore: upgrade baseline node requirement to >=12.7.0
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  .mergify/config.yml
  CONTRIBUTING.md
  gh-pages/partials/node-support-table.md
  packages/@fixtures/jsii-calc-bundled/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/integ-test/utils/index.ts
  packages/@jsii/java-runtime-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/lib/api.ts
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/bin/jsii-runtime.ts
  packages/@jsii/runtime/package.json
  packages/@jsii/runtime/webpack.config.js
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/README.md
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
  packages/jsii-rosetta/package.json
  packages/jsii/lib/compiler.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  superchain/README.md
  tools/jsii-build-tools/package.json
  tools/jsii-compliance/package.json
  tsconfig-base.json
  yarn.lock
Labels: pr/do-not-merge, contribution/core

#2987 chore: fix docker-in-docker
  superchain/Dockerfile
  superchain/dockerd-entrypoint.sh
Labels: contribution/core

#2986 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/bin/jsii-config.ts
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: dependencies, contribution/core

#2997 fix(jsii): improve checks around peerDependencies
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/test/project-info.test.ts
Labels: pr/ready-to-merge, contribution/core

#2998 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core

#2999 fix: typo in documentation
  gh-pages/content/overview/runtime-architecture.md
Labels: pr/ready-to-merge

#3002 feat(rosetta): propagate max heap size to worker threads
  packages/jsii-rosetta/lib/commands/extract.ts
Labels: contribution/core

#3006 chore(merge-back): 1.35.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3007 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core

#3011 chore(rosetta): change prettier line width to 120
  .prettierrc.yaml
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/convert.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/extract_worker.ts
  packages/jsii-rosetta/lib/commands/read.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/visualize.ts
  packages/jsii-rosetta/lib/logging.ts
  packages/jsii-rosetta/lib/markdown/extract-snippets.ts
  packages/jsii-rosetta/lib/markdown/javadoc-renderer.ts
  packages/jsii-rosetta/lib/markdown/markdown-renderer.ts
  packages/jsii-rosetta/lib/markdown/markdown.ts
  packages/jsii-rosetta/lib/markdown/replace-code-renderer.ts
  packages/jsii-rosetta/lib/markdown/replace-typescript-transform.ts
  packages/jsii-rosetta/lib/markdown/xml-comment-renderer.ts
  packages/jsii-rosetta/lib/o-tree.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/typescript/ast-utils.ts
  packages/jsii-rosetta/lib/typescript/imports.ts
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
  packages/jsii-rosetta/lib/typescript/types.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/fixtures.test.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii-rosetta/test/jsii/astutils.test.ts
  packages/jsii-rosetta/test/markdown/roundtrip.test.ts
  packages/jsii-rosetta/test/otree.test.ts
  packages/jsii-rosetta/test/rosetta.test.ts
  packages/jsii-rosetta/test/translate.test.ts
  packages/jsii-rosetta/test/translations.test.ts
  packages/jsii-rosetta/test/util.test.ts
Labels: pr/ready-to-merge, contribution/core
