Repository aws/jsii, pull requests merged in 2021-02, with the labels that each got.

#2507 fix(go): major version suffix is missing in module names for >=v2
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
Labels: contribution/core

#2492 feat(go): version file in the generated module directory
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/version-file.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2493 chore(merge-back): 1.18.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#2513 chore(release): 1.19.0
  CHANGELOG.md
  lerna.json
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/version-file.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/lib/module-like.ts
  packages/jsii-reflect/lib/submodule.ts
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/transforms/runtime-info.ts
  packages/jsii/package.json
  packages/jsii/test/transforms/runtime-info.test.ts
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#2515 chore(merge-back): 1.19.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#2519 fix(go): invalid major version suffix for submodules and jsii init
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/package.json
  packages/@jsii/java-runtime-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/package.json
  scripts/align-version.js
Labels: contribution/core

#2523 chore(merge-back): 1.20.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#2544 chore(release): 1.20.1
  CHANGELOG.md
  lerna.json
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/runtime/package.json
  yarn.lock
Labels: contribution/core, pr/no-squash

#2545 chore: fix 1.20.1 changelog title
  CHANGELOG.md
Labels: contribution/core, pr/no-squash

#2546 chore(merge-back): 1.20.1
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash

#2549 chore(build): fix Windows PR validation
  .github/workflows/main.yml
Labels: contribution/core, effort/small, management/repo

#2521 chore(superchain): use public ECR amazonlinux for base
  superchain/Dockerfile
Labels: contribution/core, pr/ready-to-merge

#2537 docs: fixed dead links from User guides page to Lib Consumer and Lang Support
  gh-pages/content/user-guides/index.md
Labels: pr/ready-to-merge

#2522 chore: npm-check-updates && yarn upgrade
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2550 fix(pacmak): TypeError when operating with Worker threads
  packages/jsii-pacmak/lib/targets/go.ts
Labels: bug, contribution/core, pr/ready-to-merge

#2554 fix(rosetta,pacmak): TypeError in node 10 with --experimental-worker
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: contribution/core

#2557 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2560 chore(go-runtime): Publish with jsii-release
  .github/workflows/main.yml
  packages/@jsii/go-runtime/build-tools/build-repo-dir.ts
  packages/@jsii/go-runtime/jsii-runtime-go/CODE_OF_CONDUCT.md
  packages/@jsii/go-runtime/jsii-runtime-go/CONTRIBUTING.md
  packages/@jsii/go-runtime/jsii-runtime-go/LICENSE
  packages/@jsii/go-runtime/jsii-runtime-go/NOTICE
  packages/@jsii/go-runtime/jsii-runtime-go/README.md
Labels: contribution/core

#2571 fix(pacmak): examples with multi-line strings produce invalid python docstrings
  packages/jsii-calc/lib/documented.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: contribution/core

#2576 chore(release): 1.21.0
  .all-contributorsrc
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  README.md
  gh-pages/content/user-guides/index.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/build-tools/build-repo-dir.ts
  packages/@jsii/go-runtime/jsii-runtime-go/CODE_OF_CONDUCT.md
  packages/@jsii/go-runtime/jsii-runtime-go/CONTRIBUTING.md
  packages/@jsii/go-runtime/jsii-runtime-go/LICENSE
  packages/@jsii/go-runtime/jsii-runtime-go/NOTICE
  packages/@jsii/go-runtime/jsii-runtime-go/README.md
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-calc/lib/documented.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  superchain/Dockerfile
  yarn.lock
Labels: pr/no-squash

#2579 chore(merge-back): 1.21.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash

#2577 chore: increase test timeout to 5 minutes
  packages/@jsii/runtime/test/playback.test.ts
Labels: contribution/core

#1736 fix(jsii): excessive "exclude" in "tsconfig.json"
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/jsii/lib/compiler.ts
Labels: contribution/core, pr/ready-to-merge

#2578 chore: remove npm deps from dependabot + auto-approve
  .github/dependabot.yml
  .github/workflows/auto-approve.yml
  .github/workflows/dependabot.yml
Labels: contribution/core, pr/ready-to-merge

#2584 fix(pacmak): go local replace do not respect `--outdir` in some cases
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/test/build-test.sh
Labels: contribution/core, pr/ready-to-merge

#2567 chore(go): runtime-wide type registration
  packages/@jsii/go-runtime/build-tools/gen-calc.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/jsii-runtime-go/type-registry.go
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/function-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/property-access.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2585 fix(go-runtime): enums are not encoded/decoded correctly
  gh-pages/content/specification/2-type-system.md
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/jsii-runtime-go/type-registry.go
Labels: bug, contribution/core, effort/small, language/go, module/runtime, pr/ready-to-merge

#2586 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2587 fix(go): map values incorrectly handled though de/serialization
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
Labels: bug, contribution/core, effort/small, language/go, pr/ready-to-merge

#2588 refactor(go): re-organize the go runtime
  .github/workflows/main.yml
  packages/@jsii/go-runtime/build-tools/all-go.ts
  packages/@jsii/go-runtime/build-tools/gen-calc.ts
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/api/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/api/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/api/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/begin.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/complete.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/create.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/del.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/end.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/get.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/hello.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/invoke.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/json.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/load.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/naming.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/request-response-markers.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/set.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/stats.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/jsii-runtime-go/type-registry.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/registeration.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/type-registry.go
  packages/@jsii/go-runtime/lib/index.ts
  packages/@jsii/go-runtime/lib/local-runtime-modules.ts
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/go.ts
Labels: contribution/core, effort/small, language/go, pr/ready-to-merge

#2592 refactor(go): we don't actually need submodules
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/api/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/go.mod
Labels: contribution/core, pr/ready-to-merge

#2591 fix(java): invalid code when multi-inheriting optional properties
  packages/@scope/jsii-calc-lib/lib/duplicate-inherited-prop.ts
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/duplicate-inherited-prop.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
Labels: bug, contribution/core, effort/small, language/java, module/pacmak, pr/ready-to-merge

#2590 chore(release): 1.22.0
  .github/dependabot.yml
  .github/workflows/auto-approve.yml
  .github/workflows/dependabot.yml
  .github/workflows/main.yml
  CHANGELOG.md
  gh-pages/content/specification/2-type-system.md
  lerna.json
  package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/build-tools/gen-calc.ts
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/jsii-runtime-go/type-registry.go
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/runtime/test/playback.test.ts
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/function-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/property-access.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/lib/compiler.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#2596 feat(go): emit indirect dependencies in go.mod
  packages/@jsii/go-runtime/build-tools/gen-calc.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, effort/small, feature-request, language/go

#2599 chore: copy golang runtime to dist for publishing
  .github/workflows/main.yml
  packages/@jsii/go-runtime/build-tools/package.sh
  packages/@jsii/go-runtime/package.json
Labels: contribution/core

#2602 chore: use GitHub Actions to auto-approve PR
  .github/workflows/auto-approve.yml
Labels: contribution/core

#2601 chore(merge-back): 1.22.0
  CHANGELOG.md
  lerna.json
  packages/@jsii/go-runtime/build-tools/gen-calc.ts
Labels: pr/auto-approve, pr/no-squash

#2604 feat(pacmak): emit LICENSE file with SPDX license text, NOTICE file
  gh-pages/content/user-guides/lib-author/configuration/index.md
  gh-pages/content/user-guides/lib-author/quick-start/set-up.md
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-pacmak/lib/target.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/js.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: contribution/core, effort/small, language/go, module/pacmak

#2598 feat(go): preserve casing of enum member names
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, effort/small, language/go, module/pacmak, pr/do-not-merge

#2605 chore: npm-check-updates && yarn upgrade
  eslint-config.yaml
  package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: contribution/core, dependencies

#2603 feat(go): require go 1.16, use native embed
  .github/workflows/main.yml
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/jsii-runtime-go/embedded/embedded.go
  packages/@jsii/go-runtime/jsii-runtime-go/embedded/embedded_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client.go
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  superchain/Dockerfile
  superchain/README.md
Labels: contribution/core, effort/small, language/go, module/pacmak, module/runtime

#2540 fix(java): JsiiRuntime.ErrorStreamSink does not respond to being interrupted
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
Labels: contribution/core, effort/small, language/java, module/runtime

#2600 feat(go): represent jsii structs as go structs (only)
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/registeration.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/type-registry.go
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, effort/small, language/go, module/pacmak, pr/do-not-merge

#2616 fix(pacmak): go 1.16 requires running "go mod download" explicitly
  packages/jsii-pacmak/lib/targets/go.ts
Labels: contribution/core

#2612 refactor(go): stop emitting unused fields in go structs
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/type-registry.go
  packages/jsii-pacmak/lib/targets/go/comparators.ts
  packages/jsii-pacmak/lib/targets/go/documentation.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime/class-constructor.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-reflect/lib/docs.ts
Labels: contribution/core, effort/medium, language/go, module/pacmak, module/runtime
