Repository aws/jsii, pull requests merged in 2021-08, with the labels that each got.

#2934 chore(mergify): add @comcalvi to team roster
  .mergify/config.yml
Labels: pr/ready-to-merge

#2939 chore(mergify): add kaizen3031593 to config file
  .mergify/config.yml
Labels: pr/ready-to-merge

#2943 chore: upgrade cattrs dependency to 1.7.1 (py3.7+)
  packages/@jsii/python-runtime/setup.py
Labels: pr/ready-to-merge, contribution/core

#2945 chore: upgrade xmldom from 0.6.0 to 0.7.0
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: SECURITY, pr/ready-to-merge, contribution/core

#2941 chore(mergify): add Chriscbr to team members
  .mergify/config.yml
Labels: pr/ready-to-merge

#2952 fix(java): implemented interface is not registered
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java
Labels: pr/ready-to-merge, contribution/core

#2953 chore: upgrade dependencies
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/lib/transforms/deprecated-remover.ts
  packages/jsii/lib/validator.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-build-tools/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core

#2853 fix(java): Disable covariants for java builder params
  .all-contributorsrc
  README.md
  packages/jsii-calc/lib/container-types.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: pr/ready-to-merge

#2949 feat(superchain): arm64 support
  .github/workflows/docker-images.yml
  superchain/.dockerignore
  superchain/Dockerfile
  superchain/README.md
  superchain/build-local.sh
  superchain/gpg/corretto.asc
  superchain/gpg/docker.asc
  superchain/gpg/nodesource.asc
  superchain/gpg/yarn.asc
Labels: pr/ready-to-merge, contribution/core

#2964 fix(python): unable to implement additional interfaces
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: pr/ready-to-merge, contribution/core

#2965 feat: @struct type system hint
  gh-pages/content/user-guides/lib-author/.pages.yml
  gh-pages/content/user-guides/lib-author/hints.md
  gh-pages/content/user-guides/lib-author/typescript-restrictions.md
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/docs.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/utils.ts
  packages/jsii/test/__snapshots__/negatives.test.ts.snap
  packages/jsii/test/hints.test.ts
  packages/jsii/test/negatives/neg.struct-hint-on-class.ts
  packages/jsii/test/negatives/neg.struct-hint-on-enum.ts
  packages/jsii/test/negatives/neg.struct-hint-with-methods.ts
Labels: contribution/core

#2973 chore(release): 1.34.0
  .all-contributorsrc
  .github/workflows/docker-images.yml
  CHANGELOG.md
  README.md
  gh-pages/content/specification/2-type-system.md
  gh-pages/content/user-guides/lib-author/.pages.yml
  gh-pages/content/user-guides/lib-author/hints.md
  gh-pages/content/user-guides/lib-author/typescript-restrictions.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-rosetta/lib/markdown/xml-comment-renderer.ts
  packages/jsii-rosetta/package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/docs.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/utils.ts
  packages/jsii/test/__snapshots__/negatives.test.ts.snap
  packages/jsii/test/hints.test.ts
  packages/jsii/test/negatives/neg.struct-hint-on-class.ts
  packages/jsii/test/negatives/neg.struct-hint-on-enum.ts
  packages/jsii/test/negatives/neg.struct-hint-with-methods.ts
  superchain/.dockerignore
  superchain/Dockerfile
  superchain/README.md
  superchain/build-local.sh
  superchain/gpg/corretto.asc
  superchain/gpg/docker.asc
  superchain/gpg/nodesource.asc
  superchain/gpg/yarn.asc
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#2974 chore(merge-back): 1.34.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve
