Repository aws/jsii, pull requests merged in 2021-06, with the labels that each got.

#2860 chore(merge-back): 1.30.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash, pr/ready-to-merge

#2867 docs: fix broken links
  packages/jsii-config/README.md
Labels: pr/ready-to-merge

#2871 fix(rosetta): hangs on 'markdown' command when a file is provided
  packages/jsii-rosetta/bin/jsii-rosetta.ts
Labels: contribution/core, pr/ready-to-merge

#2869 feat(jsii-rosetta transliterate): transliterate a jsii assembly
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/jest.config.ts
  packages/jsii-rosetta/jestsetup.js
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/index.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/target-language.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/rosetta.test.ts
Labels: contribution/core, pr/ready-to-merge

#2893 fix(pacmak/go): missing go.sum entry
  packages/jsii-pacmak/lib/targets/go.ts
Labels: contribution/core, pr/ready-to-merge

#2863 fix(rosetta): extract does not respect strict metadata entry
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/fixtures.test.ts
  packages/jsii-rosetta/test/util.test.ts
Labels: contribution/core, pr/ready-to-merge

#2892 feat(rosetta): transliterate loose mode
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
Labels: contribution/core, pr/ready-to-merge

#2894 fix(dotnet): strong-name sign assemblies
  .gitignore
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BaseOfBasePackageId/keypair.snk
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/keypair.snk
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/keypair.snk
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId/keypair.snk
  packages/@jsii/dotnet-runtime/keypair.snk
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/Amazon.JSII.JsonModel.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/AssemblyInfo.cs
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@scope/jsii-calc-base-of-base/keypair.snk
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/keypair.snk
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/keypair.snk
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/keypair.snk
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
Labels: contribution/core, pr/ready-to-merge
