Repository aws/jsii, pull requests merged in 2021-04, with the labels that each got.

#2765 chore(java): re-implement error stream sink in Java runtime
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
Labels: contribution/core, pr/ready-to-merge

#2763 fix(dotnet): unable to pass 2d-array of interfaces
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs
Labels: contribution/core, pr/ready-to-merge

#2776 chore(merge-back): 1.27.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash, pr/ready-to-merge

#2778 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/runtime/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2780 feat(jsii-go): use reflect to resolve overriden methods
  .all-contributorsrc
  README.md
  gh-pages/content/user-guides/lib-user/language-specific/go.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/internal/overrideAsyncMethods/overrideAsyncMethods.go
  packages/@jsii/go-runtime-test/project/internal/syncOverrides/syncOverrides.go
  packages/@jsii/go-runtime-test/project/internal/twoOverrides/twoOverrides.go
  packages/@jsii/go-runtime-test/project/internal/wallClock/wallClock.go
  packages/@jsii/go-runtime/jsii-runtime-go/overrides_reflect_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/jsii-pacmak/lib/targets/go.ts
Labels: pr/ready-to-merge

#2786 chore(go): retract v1.27.0
  CHANGELOG.md
  lerna.json
  packages/@jsii/go-runtime/.npmignore
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/package.json
Labels: contribution/core, pr/ready-to-merge

#2788 chore(merge-back): 1.27.1
  CHANGELOG.md
  lerna.json
  packages/@jsii/go-runtime/.npmignore
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/package.json
Labels: pr/auto-approve, pr/no-squash

#2783 fix: deprecated symbol stripping does not strip out heritage clause with imported type
  packages/jsii/lib/transforms/deprecated-remover.ts
  packages/jsii/test/deprecated-remover.test.ts
Labels: contribution/core, pr/ready-to-merge

#2791 chore(release): 1.28.0
  .all-contributorsrc
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  README.md
  gh-pages/content/user-guides/lib-user/language-specific/go.md
  gh-pages/requirements-dev.txt
  jest.config.ts
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/internal/overrideAsyncMethods/overrideAsyncMethods.go
  packages/@jsii/go-runtime-test/project/internal/syncOverrides/syncOverrides.go
  packages/@jsii/go-runtime-test/project/internal/twoOverrides/twoOverrides.go
  packages/@jsii/go-runtime-test/project/internal/wallClock/wallClock.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/embedded/.gitattributes
  packages/@jsii/go-runtime/jsii-runtime-go/overrides_reflect_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii/lib/transforms/deprecated-remover.ts
  packages/jsii/test/deprecated-remover.test.ts
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#2792 chore(merge-back): 1.28.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash

#2794 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2797 fix(go): panic on callback: using *<interface> as <interface>
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/internal/bellRinger/bellRinger.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  tools/jsii-compliance/suite.ts
Labels: contribution/core, effort/small, language/go, pr/ready-to-merge

#2803 feat(superchain): add github cli
  superchain/Dockerfile
  superchain/README.md
Labels: contribution/core, pr/ready-to-merge

#2806 chore(release): 1.29.0
  CHANGELOG.md
  gh-pages/content/specification/6-compliance-report.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/internal/bellRinger/bellRinger.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  superchain/Dockerfile
  superchain/README.md
  tools/jsii-compliance/package.json
  tools/jsii-compliance/suite.ts
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#2807 chore(merge-back): 1.29.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash, pr/ready-to-merge

#2816 feat(rosetta): JSII_ROSETTA_MAX_WORKER_COUNT limits max workers
  packages/jsii-rosetta/README.md
  packages/jsii-rosetta/lib/commands/extract.ts
Labels: contribution/core, pr/ready-to-merge
