Repository aws/jsii, pull requests merged in 2021-12, with the labels that each got.

#3217 chore(rosetta): rewrite README
  packages/jsii-rosetta/README.md
Labels: contribution/core

#3220 chore(superchain): generate complete NOTICE list
  superchain/Dockerfile
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core

#3219 fix(pacmak): don't automatically translate examples without asking
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/index.ts
Labels: pr/ready-to-merge, contribution/core

#3223 feat(rosetta): generate rosetta tablets next to each assembly
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/commands/trim-cache.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/typescript/types.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii-rosetta/test/commands/trim-cache.test.ts
Labels: pr/ready-to-merge, contribution/core

#3205 fix: improve compatibility with restricted-export modules
  packages/jsii-pacmak/lib/dependency-graph.ts
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/test/dependency-graph.test.ts
  packages/jsii-pacmak/test/generated-code/prerelease-identifiers.test.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/lib/util.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/lib/utils.ts
  packages/jsii/test/project-info.test.ts
Labels: contribution/core

#3235 chore(merge-back): 1.47.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/auto-approve

#3225 fix(rosetta): classes are not correctly identified if package uses an outDir
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/testutil.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/test/compiler.test.ts
  packages/jsii/test/symbol-identifiers.test.ts
Labels: contribution/core

#3234 fix(jsii): symbolid for single-valued enums is incorrect
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/utils.ts
  packages/jsii/test/symbol-identifiers.test.ts
Labels: pr/ready-to-merge, contribution/core

#3233 fix(jsii): correctly identify types regardless of import method
  packages/@jsii/spec/lib/configuration.ts
  packages/jsii-reflect/test/independent.test.ts
  packages/jsii-rosetta/test/testutil.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/test/submodules.test.ts
Labels: pr/ready-to-merge, contribution/core

#3242 chore: fix issues encountered during CDK build
  packages/jsii/lib/compiler.ts
Labels: contribution/core

#3243 fix(rosetta): infuse drops first assembly
  packages/jsii-rosetta/bin/jsii-rosetta.ts
Labels: contribution/core

#3245 fix(jsii): handle imports from libraries compiled with old jsii
  packages/jsii/lib/assembler.ts
Labels: pr/ready-to-merge, contribution/core

#3247 chore(pacmak, reflect): punycode messes us up in more places
  packages/jsii-pacmak/lib/dependency-graph.ts
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/lib/util.ts
Labels: contribution/core

#3249 chore: move away from mergify commit_message
  .mergify/config.yml
Labels: contribution/core

#3221 chore: npm-check-updates && yarn upgrade
  .github/workflows/main.yml
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, pr/auto-approve

#3254 chore(release): 1.48.0
  .github/workflows/main.yml
  .mergify/config.yml
  CHANGELOG.md
  gh-pages/content/user-guides/lib-author/quick-start/write-code.md
  lerna.json
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/lib/configuration.ts
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/dependency-graph.ts
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/dependency-graph.test.ts
  packages/jsii-pacmak/test/generated-code/prerelease-identifiers.test.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/lib/util.ts
  packages/jsii-reflect/package.json
  packages/jsii-reflect/test/independent.test.ts
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/testutil.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/lib/utils.ts
  packages/jsii/package.json
  packages/jsii/test/compiler.test.ts
  packages/jsii/test/project-info.test.ts
  packages/jsii/test/submodules.test.ts
  packages/jsii/test/symbol-identifiers.test.ts
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/no-squash

#3248 fix(rosetta): `rosetta extract` fails if run after `rosetta infuse`
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3255 chore(merge-back): 1.48.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/auto-approve

#3257 chore(release): 1.49.0
  CHANGELOG.md
  lerna.json
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/no-squash

#3258 chore(merge-back): 1.49.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, pr/auto-approve

#3260 fix(rosetta): non-compiling snippets not reported on subsequent extracts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
Labels: pr/ready-to-merge, contribution/core

#3262 fix(rosetta): transliterate command does not translate in parallel
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/lib/snippet.ts
Labels: pr/ready-to-merge, contribution/core

#3268 chore(jsii): more tests on importing
  packages/jsii/test/submodules.test.ts
Labels: pr/ready-to-merge, contribution/core

#3274 chore: tweak auto-approval workflow
  .github/workflows/auto-approve.yml
  .github/workflows/pr-labeler.yml
Labels: pr/ready-to-merge, contribution/core

#3277 fix(pacmak): fails on bundled dependency without entry point
  packages/jsii-pacmak/lib/dependency-graph.ts
  packages/jsii-pacmak/test/dependency-graph.test.ts
Labels: pr/ready-to-merge, contribution/core

#3284 fix(jsii): color codes are logged to logfiles
  packages/jsii/bin/jsii.ts
Labels: pr/ready-to-merge, contribution/core

#3282 fix(rosetta): diagnostics from infused snippets were not ignored
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
Labels: pr/ready-to-merge, contribution/core

#3288 chore: auto approve workflow broken
  .github/workflows/auto-approve.yml
Labels: pr/ready-to-merge, contribution/core

#3261 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, pr/auto-approve

#3291 fix(rosetta): infused snippets not returned from cache
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
Labels: pr/ready-to-merge, contribution/core

#3294 fix(jsii): slow with deep dependency tree
  packages/jsii/lib/project-info.ts
Labels: contribution/core

#3295 chore(release): 1.50.0
  .github/workflows/auto-approve.yml
  .github/workflows/pr-labeler.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/go.sum
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/dependency-graph.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/dependency-graph.test.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/package.json
  packages/jsii/test/submodules.test.ts
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3296 chore(merge-back): 1.50.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, pr/auto-approve

#3297 chore: deprecation warnings test are timing out
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3298 chore: merge dependabot with mergify
  .github/workflows/auto-approve.yml
  .github/workflows/pr-labeler.yml
  .mergify/config.yml
Labels: contribution/core

#3300 chore: rename label for auto approvals
  .github/workflows/auto-approve.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/yarn-upgrade.yml
Labels: pr/ready-to-merge, contribution/core

#3299 feat(pacmak): go yaml struct tags
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: pr/ready-to-merge

#3307 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3306 fix(jsii): cannot use submodule types from assemblies before 1.39.0
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/test/submodules.test.ts
Labels: pr/ready-to-merge, contribution/core

#3308 chore: move disclaimer logic from pacmak to rosetta
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/rosetta.test.ts
Labels: pr/ready-to-merge, contribution/core

#3304 chore(rosetta): loose option not exposed to command-line for extract
  packages/jsii-rosetta/bin/jsii-rosetta.ts
Labels: pr/ready-to-merge, contribution/core

#3280 fix(rosetta): Python translation for `implements` is wrong
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/test/translate.test.ts
  packages/jsii-rosetta/test/translations/classes/class_implementing_jsii_interface.cs
  packages/jsii-rosetta/test/translations/classes/class_implementing_jsii_interface.java
  packages/jsii-rosetta/test/translations/classes/class_implementing_jsii_interface.py
  packages/jsii-rosetta/test/translations/classes/class_implementing_jsii_interface.ts
Labels: pr/ready-to-merge, contribution/core
