Repository aws/jsii, pull requests merged in 2021-05, with the labels that each got.

#2802 refactor(go): move jsii runtime functions into separate module
  packages/@jsii/go-runtime/jsii-runtime-go/deprecated.go
  packages/@jsii/go-runtime/jsii-runtime-go/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/helpers.go
  packages/@jsii/go-runtime/jsii-runtime-go/helpers_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/jsii.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime/overrides_reflect_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime/runtime.go
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, language/go, pr/ready-to-merge

#2805 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-build-tools/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core, dependencies

#2821 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/runtime/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2804 docs: update typescript links
  gh-pages/content/specification/2-type-system.md
Labels: pr/ready-to-merge

#2844 chore: disable the auto upgrade workflow
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core

#2845 chore: permissions for github actions
  .github/workflows/auto-approve.yml
  .github/workflows/close-stale-issues.yml
  .github/workflows/closed-issue-message.yml
  .github/workflows/docker-images.yml
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core

#2835 chore: npm-check-updates && yarn upgrade
  eslint-config.yaml
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/lib/objects.ts
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/lib/calculator.ts
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/lib/prompt.ts
  packages/jsii-config/package.json
  packages/jsii-diff/lib/type-comparison.ts
  packages/jsii-diff/lib/validations.ts
  packages/jsii-diff/package.json
  packages/jsii-diff/test/classes.test.ts
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/js.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/targets/version-utils.test.ts
  packages/jsii-reflect/bin/jsii-tree.ts
  packages/jsii-reflect/lib/callable.ts
  packages/jsii-reflect/lib/initializer.ts
  packages/jsii-reflect/lib/method.ts
  packages/jsii-reflect/lib/property.ts
  packages/jsii-reflect/lib/reference-type.ts
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/typescript/ast-utils.ts
  packages/jsii-rosetta/package.json
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/node-bindings.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/lib/transforms/deprecated-remover.ts
  packages/jsii/lib/utils.ts
  packages/jsii/lib/validator.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2856 chore: browser compatibility for `jsii-reflect` and `codemaker`
  packages/codemaker/lib/filebuff.ts
  packages/jsii-reflect/lib/type-system.ts
Labels: contribution/core, pr/ready-to-merge

#2851 fix(python): module import fails: NameError: name 'List' is not defined
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: pr/ready-to-merge

#2809 fix(python): classes do not correctly implement interfaces
  packages/@jsii/python-runtime/tests/test_python.py
  packages/jsii-calc/lib/module2702/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: pr/ready-to-merge

#2758 fix(pacmak): fails when package path contains space
  packages/jsii-pacmak/lib/packaging.ts
Labels: contribution/core
