Repository aws/jsii, pull requests merged in 2021-01, with the labels that each got.

#2394 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/runtime/package.json
  yarn.lock
Labels: contribution/core, dependencies

#2364 chore: sanitize exit handler for Kernel
  packages/@jsii/kernel/lib/kernel.ts
  packages/@jsii/kernel/lib/on-exit.ts
Labels: contribution/core, pr/ready-to-merge

#2399 fix(go): generated code runtime dependency version
  packages/jsii-pacmak/lib/targets/go/package.ts
Labels: contribution/core

#2248 feat(dotnet,java): kernel process inherits host's STDERR
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ServiceContainerFixture.cs
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/XUnitLogger.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Client/RuntimeTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/INodeProcess.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Runtime.cs
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
Labels: contribution/core, effort/small, language/dotnet, language/java, module/runtime, pr/ready-to-merge

#2403 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2421 fix(python): process.terminate() got an unexpected keyword argument 'timeout'
  CHANGELOG.md
  lerna.json
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
Labels: contribution/core

#2422 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2423 chore(merge-back): 1.17.1
  CHANGELOG.md
  lerna.json
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
Labels: pr/no-squash, pr/ready-to-merge

#2418 chore(jsii): improve locality of JSII9998 error
  packages/jsii/lib/assembler.ts
Labels: contribution/core, effort/small, language/typescript, module/jsii, pr/ready-to-merge

#2426 docs: update copyright year
  gh-pages/mkdocs.yml
Labels: pr/ready-to-merge

#2417 feat(go): runtime release tagging
  .github/workflows/main.yml
  .github/workflows/push-go-runtime.yml
  packages/@jsii/go-runtime/build-tools/build-repo-dir.ts
Labels: contribution/core, pr/ready-to-merge

#2448 docs: correct spelling of traditional
  gh-pages/content/dev-guide/index.md
Labels: pr/ready-to-merge, review/small

#2451 chore: npm-check-updates && yarn upgrade
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2456 chore(docs): re-organized documentation website
  gh-pages/content/.pages.yml
  gh-pages/content/adr/.pages.yml
  gh-pages/content/adr/_README.md
  gh-pages/content/adr/introduction.md
  gh-pages/content/index.md
  gh-pages/content/overview/features.md
  gh-pages/content/overview/runtime-architecture.md
  gh-pages/content/overview/toolchain.md
  gh-pages/content/specification/.pages.yml
  gh-pages/content/specification/1-introduction.md
  gh-pages/content/specification/2-type-system.md
  gh-pages/content/user-guides/.pages.yml
  gh-pages/content/user-guides/index.md
  gh-pages/content/user-guides/language-support/.pages.yml
  gh-pages/content/user-guides/language-support/assembly.md
  gh-pages/content/user-guides/language-support/callbacks.md
  gh-pages/content/user-guides/language-support/callbacks.monopic
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/.pages.yml
  gh-pages/content/user-guides/lib-author/configuration/.pages.yml
  gh-pages/content/user-guides/lib-author/configuration/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/dotnet.md
  gh-pages/content/user-guides/lib-author/configuration/targets/go.md
  gh-pages/content/user-guides/lib-author/configuration/targets/java.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  gh-pages/content/user-guides/lib-author/quick-start/set-up.md
  gh-pages/content/user-guides/lib-author/quick-start/write-code.md
  gh-pages/content/user-guides/lib-author/typescript-restrictions.md
  gh-pages/content/user-guides/lib-user/.pages.yml
  gh-pages/content/user-guides/lib-user/index.md
  gh-pages/content/user-guides/lib-user/language-specific/.pages.yml
  gh-pages/content/user-guides/lib-user/language-specific/python.md
  gh-pages/mkdocs.yml
  gh-pages/requirements-dev.txt
  gh-pages/start.sh
Labels: contribution/core, documentation, effort/small, pr/ready-to-merge

#2458 chore: remove unused strong-named signing build infrastructure
  buildspec.yaml
  package.json
  scripts/fetch-dotnet-snk.sh
Labels: contribution/core, pr/ready-to-merge

#2462 fix(go): invalid output for multi-line @return and @deprecated comments
  packages/jsii-calc/lib/documented.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/documentation.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2476 fix(python): pin mypy to the exact version
  .github/dependabot.yml
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
Labels: contribution/core, pr/ready-to-merge

#2419 fix(rosetta): correctly emit multi-line string literals
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/visualize.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/test/translations/expressions/string_interpolation.cs
  packages/jsii-rosetta/test/translations/expressions/string_interpolation.java
  packages/jsii-rosetta/test/translations/expressions/string_interpolation.py
  packages/jsii-rosetta/test/translations/expressions/string_interpolation.ts
  packages/jsii-rosetta/test/translations/expressions/string_literal.cs
  packages/jsii-rosetta/test/translations/expressions/string_literal.java
  packages/jsii-rosetta/test/translations/expressions/string_literal.py
  packages/jsii-rosetta/test/translations/expressions/string_literal.ts
Labels: bug, contribution/core, effort/small, module/sampiler, pr/ready-to-merge

#2481 fix(jsii): submodules of dependencies show up in assembly
  packages/jsii-calc/test/assembly.jsii
  packages/jsii/lib/assembler.ts
Labels: contribution/core, pr/ready-to-merge

#2437 feat(jsii): experimental --strip-deprecated feature
  gh-pages/content/.pages.yml
  gh-pages/content/decisions/.pages.yml
  gh-pages/content/decisions/_README.md
  gh-pages/content/decisions/introduction.md
  gh-pages/content/user-guides/lib-author/.pages.yml
  gh-pages/content/user-guides/lib-author/toolchain/.pages.yml
  gh-pages/content/user-guides/lib-author/toolchain/jsii.md
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/node-bindings.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/lib/transforms/deprecated-remover.ts
  packages/jsii/lib/transforms/ts-comment-replacer.ts
  packages/jsii/lib/transforms/utils.ts
  packages/jsii/lib/utils.ts
  packages/jsii/test/__snapshots__/negatives.test.ts.snap
  packages/jsii/test/compiler.test.ts
  packages/jsii/test/deprecated-remover.test.ts
  packages/jsii/test/negatives.test.ts
  packages/jsii/test/negatives/neg.stripped-deprecated.ts
  packages/jsii/tsconfig.json
Labels: contribution/core, pr/ready-to-merge

#2472 fix(python): mypy validation errors
  packages/@jsii/python-runtime/build-tools/gen-calc.ts
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
Labels: contribution/core, effort/small, language/python, pr/ready-to-merge

#2487 chore(go): rename jsii-experimental directory to jsii-runtime-go
  packages/@jsii/go-runtime/README.md
  packages/@jsii/go-runtime/build-tools/build-repo-dir.ts
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-experimental/no_op.go
  packages/@jsii/go-runtime/jsii-runtime-go/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/package.json
Labels: contribution/core, language/go, pr/ready-to-merge

#2482 feat: submodules expose readmes and targets via `jsii-reflect`
  packages/@jsii/spec/lib/assembly.ts
  packages/jsii-calc/lib/submodule/README.md
  packages/jsii-calc/lib/submodule/isolated.README.md
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/lib/module-like.ts
  packages/jsii-reflect/lib/submodule.ts
  packages/jsii-reflect/test/type-system.test.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/test/submodules.test.ts
Labels: contribution/core, pr/ready-to-merge

#2489 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/spec/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2488 chore(go): minor refactors in go runtime
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/package.json
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, effort/small, language/go

#2485 feat(go): run "go build" on generated code
  packages/@jsii/go-runtime/.eslintrc.yaml
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/build-tools/tsconfig.json
  packages/@jsii/go-runtime/lib/index.ts
  packages/@jsii/go-runtime/package.json
  packages/@jsii/go-runtime/tsconfig.json
  packages/@scope/jsii-calc-base/lib/index.ts
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-calc/test/test.calc.ts
  packages/jsii-calc/test/test.transitive.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2348 feat: add runtime type info (fqn and version) to compiled sources
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/transforms/runtime-info.ts
  packages/jsii/test/transforms/runtime-info.test.ts
Labels: contribution/core

#2484 refactor(jsii-reflect): `tryFindFqn` uses map lookups if possible
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/lib/module-like.ts
  packages/jsii-reflect/lib/submodule.ts
Labels: contribution/core, pr/ready-to-merge
