Repository aws/jsii, pull requests merged in 2021-07, with the labels that each got.

#2902 revert: "fix(dotnet): strong-name sign assemblies (#2894)"
  .gitignore
  gh-pages/content/user-guides/lib-author/configuration/targets/dotnet.md
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BaseOfBasePackageId/keypair.snk
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId.BasePackageId/keypair.snk
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId.LibPackageId/keypair.snk
  packages/@jsii/dotnet-runtime-test/test/generated/dotnet/Amazon.JSII.Tests.CalculatorPackageId/keypair.snk
  packages/@jsii/dotnet-runtime/NuGet.Metadata.props.t.js
  packages/@jsii/dotnet-runtime/keypair.snk
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/Amazon.JSII.JsonModel.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/AssemblyTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/AssemblyInfo.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Spec/AssemblyTargets.cs
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@jsii/spec/lib/configuration.ts
  packages/@scope/jsii-calc-base-of-base/keypair.snk
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/keypair.snk
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/keypair.snk
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/keypair.snk
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/lib/schema.ts
  packages/jsii-config/test/index.test.ts
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
Labels: contribution/core

#2903 chore(release): 1.31.0
  .all-contributorsrc
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  README.md
  gh-pages/content/user-guides/lib-author/configuration/targets/dotnet.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/dotnet-runtime/NuGet.Metadata.props.t.js
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/AssemblyTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Spec/AssemblyTargets.cs
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/go.sum
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/spec/lib/configuration.ts
  packages/jsii-config/README.md
  packages/jsii-config/lib/schema.ts
  packages/jsii-config/test/index.test.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/jest.config.ts
  packages/jsii-rosetta/jestsetup.js
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/index.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/target-language.ts
  packages/jsii-rosetta/lib/rosetta.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/fixtures.test.ts
  packages/jsii-rosetta/test/rosetta.test.ts
  packages/jsii-rosetta/test/util.test.ts
  yarn.lock
Labels: pr/no-squash, pr/ready-to-merge

#2904 chore(merge-back): 1.31.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash

#2914 chore: test against .NET 6 (prerelease)
  .github/workflows/main.yml
Labels: contribution/core, pr/ready-to-merge

#2917 fix(rosetta): fails on "Debug Failure"
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/translate.test.ts
Labels: contribution/core, pr/ready-to-merge

#2897 feat(rosetta): hoist declare statements to top-level of document
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/test/fixtures.test.ts
  packages/jsii-rosetta/test/rosetta/default.ts-fixture
Labels: contribution/core, pr/ready-to-merge

#2906 docs: Fix broken link to Contribution Guide
  gh-pages/content/index.md
Labels: pr/ready-to-merge

#2920 chore(release): 1.32.0
  .all-contributorsrc
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  README.md
  gh-pages/content/index.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/go.sum
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/fixtures.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/fixtures.test.ts
  packages/jsii-rosetta/test/rosetta/default.ts-fixture
  packages/jsii-rosetta/test/translate.test.ts
Labels: pr/no-squash, pr/ready-to-merge

#2922 chore(merge-back): 1.32.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash, pr/ready-to-merge
