Repository aws/jsii, pull requests merged in 2021-03, with the labels that each got.

#2622 fix(pacmak): multiple go (and python) issues
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/no-direct-types/index.ts
  packages/jsii-calc/lib/no-direct-types/sub1/index.ts
  packages/jsii-calc/lib/no-direct-types/sub2/index.ts
  packages/jsii-calc/lib/only-static/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2608 refactor(go): hide API fields from the kernel API
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/begin.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/complete.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/create.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/del.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/end.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/get.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/hello.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/invoke.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/load.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/naming.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/request-response-markers.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/set.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/stats.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
Labels: contribution/core, effort/small, language/go

#2609 refactor(go): move child process handling to dedicated package
  .github/dependabot.yml
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/hello.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/process/consume-stderr.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/process/handshake.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/process/jsii-mock-runtime.js
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/process/process.go
  packages/@jsii/go-runtime/jsii-runtime-go/kernel/process/process_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/typeregistry/type-registry.go
Labels: contribution/core

#2629 chore: add "version" file to go dist directory
  packages/@jsii/go-runtime/build-tools/package.sh
Labels: contribution/core

#2628 chore: add "version" file to go dist directory
  packages/@jsii/go-runtime/build-tools/package.sh
Labels: contribution/core

#2636 fix(go): enums inside structs are not properly serialized
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/build-tools/gen.ts
  packages/@jsii/go-runtime/jsii-calc-test/main_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/api/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/api/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/embedded/embedded.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/embedded/embedded_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/begin.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/complete.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/create.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/del.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/end.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/get.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/invoke.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/json.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/load.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/naming.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/consume-stderr.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/handshake.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/jsii-mock-runtime.js
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/request-response-markers.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/set.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/stats.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/type-registry.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2614 feat(go): support direct implementation of jsii interfaces
  .github/dependabot.yml
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/go-runtime/build-tools/all-go.ts
  packages/@jsii/go-runtime/build-tools/go-run.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/go.sum
  packages/@jsii/go-runtime/jsii-calc-test/callbacks_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/api/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/embedded/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/embedded/embedded.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/begin.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/complete.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/create.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/del.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/end.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/get.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/invoke.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/json.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/load.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/manage-object.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/naming.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/set.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/stats.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/doc.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/objectstore.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/discover-implemented.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/type-registry.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/package.json
  packages/@jsii/go-runtime/tools.go
  packages/jsii-pacmak/lib/targets/go/runtime/class-constructor.ts
  packages/jsii-pacmak/lib/targets/go/runtime/constants.ts
  packages/jsii-pacmak/lib/targets/go/runtime/function-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, effort/large, language/go

#2642 chore(dotnet): correct all .NET Code Analyzer Errors
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/AssemblyInfo.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Helpers/DiagnosticResult.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.Helper.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/AssemblyInfo.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/AssemblyInfo.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/AssemblyInfo.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Client/ClientTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/Converters/FrameworkToJsiiConverterTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/Converters/JsiiToFrameworkConverterTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/DeputyBaseTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/AssemblyTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/ClassTypeTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/CollectionKindTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/CollectionTypeReferenceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/DocsTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/EnumMemberTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/JsonModel/TestUtils.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/AssemblyInfo.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Api/Response/NamingResponse.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Converters/TypeConverter.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/FileSystem/FileSystem.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Spec/DependencyRoot.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/ValueConverter.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
Labels: contribution/core

#2639 fix(go): malformed multiline docstrings in constructors
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2641 fix(go): invalid generated code for classes a keyword name
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/lib/submodule/index.ts
  packages/jsii-calc/lib/submodule/issue2637.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2607 feat(compliance): Compliance suite
  buildspec.yaml
  gh-pages/content/specification/.pages.yml
  gh-pages/content/specification/6-compliance-report.md
  package.json
  packages/@jsii/go-runtime-test/.eslintrc.yaml
  packages/@jsii/go-runtime-test/.gitignore
  packages/@jsii/go-runtime-test/LICENSE
  packages/@jsii/go-runtime-test/NOTICE
  packages/@jsii/go-runtime-test/README.md
  packages/@jsii/go-runtime-test/build-tools/gen-calc.ts
  packages/@jsii/go-runtime-test/package.json
  packages/@jsii/go-runtime-test/project/callbacks_test.go
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime-test/project/main_test.go
  packages/@jsii/go-runtime-test/tsconfig.json
  packages/@jsii/go-runtime/build-tools/all-go.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/go.sum
  packages/@jsii/go-runtime/package.json
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/ComplianceSuiteHarness.java
  superchain/Dockerfile
  tools/jsii-compliance/.eslintrc.yaml
  tools/jsii-compliance/README.md
  tools/jsii-compliance/package.json
  tools/jsii-compliance/report.ts
  tools/jsii-compliance/schema.ts
  tools/jsii-compliance/suite.ts
  tools/jsii-compliance/tsconfig.json
  yarn.lock
Labels: contribution/core

#2646 chore(merge-back): 1.24.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash

#2644 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core, dependencies

#2658 chore(compliance): Golang compliance tests batch
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  tools/jsii-compliance/schema.ts
  tools/jsii-compliance/suite.ts
Labels: contribution/core, pr/ready-to-merge

#2645 chore(go): make Load call idempotent
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/json.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/load.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/typeregistry.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2657 chore(compliance): add "missing" and "n/a" test statuses
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/README.md
  packages/@jsii/go-runtime-test/project/compliance.go
  packages/@jsii/go-runtime-test/project/compliance_test.go
  tools/jsii-compliance/README.md
  tools/jsii-compliance/report.ts
  tools/jsii-compliance/schema.ts
  tools/jsii-compliance/suite.ts
Labels: contribution/core, pr/ready-to-merge

#2664 chore: fix rendering of compliance table
  gh-pages/content/assets/stylesheets/extra.css
  gh-pages/content/specification/6-compliance-report.md
  tools/jsii-compliance/report.ts
Labels: contribution/core, pr/ready-to-merge

#2666 chore(compliance): more compliance tests
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  tools/jsii-compliance/suite.ts
Labels: contribution/core

#2667 chore: go compliance test pack
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/README.md
  packages/@jsii/go-runtime-test/project/compliance.go
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/nativeobjectwithinterdfaces.go
Labels: contribution/core, pr/ready-to-merge

#2668 chore: two tiny build tweaks
  packages/@jsii/java-runtime/package.json
  tools/jsii-compliance/package.json
Labels: contribution/core, pr/ready-to-merge

#2669 chore: fix the link-all.sh script
  scripts/link-all.sh
Labels: contribution/core

#2674 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/auto-approve, pr/ready-to-merge

#2650 fix(go): nested types are not namespaced
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/jsii-pacmak/.eslintrc.yaml
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/examples.test.ts
  packages/jsii-pacmak/test/generated-code/examples/nested-types.ts
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/tsconfig.json
  packages/jsii-reflect/lib/type.ts
  packages/jsii/lib/helpers.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/validator.ts
  packages/jsii/test/__snapshots__/negatives.test.ts.snap
  packages/jsii/test/negatives/neg.static-nested-conflict.ts
Labels: bug, contribution/core, language/go, module/jsii, module/pacmak, pr/ready-to-merge

#2684 chore: add "go" to issue templates
  .github/ISSUE_TEMPLATE/1-bug.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/3-guidance.md
Labels: contribution/core

#2687 feat(go): packageName and versionSuffix
  gh-pages/content/user-guides/lib-author/configuration/targets/go.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/main_test.go
  packages/@jsii/kernel/test/kernel.test.ts
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/lib/submodule/.jsiirc.json
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-calc/update-all.sh
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core

#2685 fix(go): missing imports needed by base members
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/module2647/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2691 fix(go): missing imports required by collection types
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/module2689/index.ts
  packages/jsii-calc/lib/module2689/methods/index.ts
  packages/jsii-calc/lib/module2689/props/index.ts
  packages/jsii-calc/lib/module2689/retval/index.ts
  packages/jsii-calc/lib/module2689/structs/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2697 fix(go): duplicate conversion functions when parent structs have the same base name
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/module2530/index.ts
  packages/jsii-calc/lib/module2692/index.ts
  packages/jsii-calc/lib/module2692/submodule1/index.ts
  packages/jsii-calc/lib/module2692/submodule2/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/lib/targets/go/util.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core, pr/do-not-merge

#2701 fix(go): missing methods for multiple inheritance of the same interface
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/module2700/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core, pr/do-not-merge

#2690 chore(compliance): golang compliance tests batch
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  tools/jsii-compliance/suite.ts
Labels: contribution/core, pr/ready-to-merge

#2696 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2704 fix(go): invalid code when a module only has static methods [test only]
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/module2617/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2681 fix(pacmak): Python submodules don't have docstrings
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2713 fix(pacmak): xmldom error when generating packages
  packages/jsii-rosetta/lib/markdown/xml-comment-renderer.ts
Labels: contribution/core

#2699 fix(go,python/java): bad code for members with same name with different casing
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/module2700/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/naming-util.ts
  packages/jsii-pacmak/lib/targets/dotnet/nameutils.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2656 chore(go): pre-size slices where possible
  packages/@jsii/go-runtime/jsii-runtime-go/internal/embedded/embedded.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/objectstore.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/typeregistry.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
Labels: contribution/core, effort/small, language/go, p2, pr/ready-to-merge

#2682 fix(pacmak): Java submodules don't have package infos
  packages/@jsii/spec/lib/assembly.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2703 fix(go): embedded bases may conflict with member names
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/module2702/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.ts.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.ts.snap
Labels: contribution/core

#2683 fix(pacmak): .NET submodules don't have namespace docs
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2705 fix(go): optional values
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/package.json
  packages/@jsii/go-runtime-test/project/callbacks_test.go
  packages/@jsii/go-runtime-test/project/compliance.go
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/main_test.go
  packages/@jsii/go-runtime-test/project/nativeobjectwithinterdfaces.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, language/go, pr/ready-to-merge

#2654 fix(python): duplicated kwargs when field is multi-inherited
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/examples/diamond-struct-parameter.ts
Labels: contribution/core, pr/ready-to-merge

#2723 chore(go): Update snapshots
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
Labels: contribution/core

#2655 chore(go): adding new compliance tests
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/build-tools/go-run.ts
  packages/@jsii/go-runtime-test/package.json
  packages/@jsii/go-runtime-test/project/compliance.go
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime-test/project/internal/addTen/addTen.go
  packages/@jsii/go-runtime-test/project/internal/doNotOverridePrivates/doNotOverridePrivates.go
  packages/@jsii/go-runtime-test/project/internal/friendlyRandom/friendlyRandom.go
  packages/@jsii/go-runtime-test/project/internal/overrideAsyncMethods/overrideAsyncMethods.go
  packages/@jsii/go-runtime-test/project/internal/syncOverrides/syncOverrides.go
  packages/@jsii/go-runtime-test/project/internal/twoOverrides/twoOverrides.go
  packages/@jsii/go-runtime-test/project/internal/wallClock/wallClock.go
  packages/@jsii/go-runtime-test/project/tools.go
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/runtime/class-constructor.ts
  packages/jsii-pacmak/lib/targets/go/runtime/emit-arguments.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/lib/timer.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
  packages/jsii-pacmak/test/generated-code/target-python.test.ts
Labels: compliance, contribution/core, effort/medium, language/go, pr/ready-to-merge

#2725 chore: remove integration test from PR validation
  .github/workflows/main.yml
  .mergify/config.yml
Labels: contribution/core

#2716 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2712 fix(rosetta): 'extract' does not translate samples in submodule READMEs
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
Labels: contribution/core, pr/ready-to-merge

#2718 feat(superchain): install both Node 10 and Node 14
  superchain/Dockerfile
Labels: contribution/core, pr/ready-to-merge

#2726 feat(superchain): `$NVM_USE_VERSION` selects Node.js version
  superchain/Dockerfile
  superchain/README.md
Labels: contribution/core, pr/ready-to-merge

#2717 feat(go): extension & overrides mechanism
  gh-pages/content/specification/6-compliance-report.md
  gh-pages/content/user-guides/lib-user/language-specific/.pages.yml
  gh-pages/content/user-guides/lib-user/language-specific/go.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/internal/doNotOverridePrivates/doNotOverridePrivates.go
  packages/@jsii/go-runtime-test/project/internal/friendlyRandom/friendlyRandom.go
  packages/@jsii/go-runtime-test/project/internal/overrideAsyncMethods/overrideAsyncMethods.go
  packages/@jsii/go-runtime-test/project/internal/syncOverrides/syncOverrides.go
  packages/@jsii/go-runtime-test/project/internal/twoOverrides/twoOverrides.go
  packages/@jsii/go-runtime-test/project/internal/wallClock/wallClock.go
  packages/@jsii/go-runtime-test/project/nativeobjectwithinterdfaces.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/api/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/create.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/manage-object.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/objectstore.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/discover-implemented.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/overrides.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/typeregistry.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/jsii-pacmak/lib/targets/go/runtime/class-constructor.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, effort/medium, language/go, pr/ready-to-merge

#2720 fix: TypeError when trying to use bin-scripts in Python
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
Labels: pr/ready-to-merge

#2729 revert(rosetta): 'extract' does not translate samples in submodule READMEs
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
Labels: contribution/core, pr/ready-to-merge

#2733 chore(merge-back): 1.26.0
  CHANGELOG.md
  lerna.json
Labels: pr/auto-approve, pr/no-squash

#2731 fix(go): missing setter for R/W interface properties
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/go.sum
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: bug, contribution/core, effort/small, language/go, module/pacmak, pr/ready-to-merge

#2736 fix(superchain): use entrypoint to set up nvm
  superchain/Dockerfile
  superchain/README.md
  superchain/run.sh
Labels: contribution/core

#2737 Revert "feat(superchain): install both Node 10 and Node 14 (#2718)"
  superchain/Dockerfile
  superchain/README.md
  superchain/run.sh
Labels: contribution/core

#2730 fix(go): dates are mistreated as strings
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/api/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime.go
  packages/jsii-pacmak/lib/targets/go/dependencies.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: bug, compliance, contribution/core, effort/small, language/go, module/pacmak, module/runtime, pr/ready-to-merge

#2738 fix(go): protected property accessors missing
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2742 chore(golang): sync overrides compliance test cleanup
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
Labels: contribution/core, pr/ready-to-merge

#2743 chore(golang): require instead of assert
  packages/@jsii/go-runtime-test/project/compliance.go
  packages/@jsii/go-runtime-test/project/compliance_test.go
Labels: contribution/core, pr/ready-to-merge

#2741 feat(superchain): also build a superchain image with Node 14
  .github/workflows/docker-images.yml
  .mergify/config.yml
  superchain/Dockerfile
  superchain/README.md
  superchain/build-local.sh
Labels: contribution/core

#2739 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge

#2754 fix(go): unable to set an array of interfaces/enums
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
Labels: bug, contribution/core, effort/medium, language/go, module/runtime, pr/ready-to-merge

#2747 chore: jsii docs incorrect refer to the strip-dependencies option
  gh-pages/content/user-guides/lib-author/toolchain/jsii.md
Labels: contribution/core, pr/ready-to-merge

#2744 fix(rosetta): 'extract' does not translate samples in submodule READMEs
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
Labels: contribution/core, pr/ready-to-merge

#2757 fix(python): module import fails with: KeyError: '__all__'
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: contribution/core, pr/ready-to-merge

#2606 fix(python): accept Sequence[T] for array parameters
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
Labels: contribution/core, effort/small, language/python, module/pacmak, pr/ready-to-merge

#2762 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: contribution/core, dependencies, pr/ready-to-merge
