Repository aws/jsii, pull requests merged in 2022-01, with the labels that each got.

#3314 chore: excluding setuptools from dependabot
  .github/dependabot.yml
Labels: pr/ready-to-merge, contribution/core

#3317 chore(rosetta): change how python shows declared types and include module name
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/test/jsii-imports.test.ts
  packages/jsii-rosetta/test/translate.test.ts
  packages/jsii-rosetta/test/translations/expressions/array_index.py
  packages/jsii-rosetta/test/translations/statements/declare_var.py
Labels: pr/ready-to-merge, contribution/core

#3323 chore(merge-back): 1.51.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3324 fix(rosetta): `transliterate` tries to recompile samples from tablets
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/coverage.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
Labels: pr/ready-to-merge, contribution/core

#3325 chore(release): 1.52.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/python-runtime/setup.py
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/coverage.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/rosetta-translator.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
Labels: pr/ready-to-merge, pr/no-squash

#3327 chore(merge-back): 1.52.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3328 fix(jsii): breaks due to faulty version of `colors`
  packages/jsii-reflect/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3329 chore(release): 1.52.1
  CHANGELOG.md
  lerna.json
  packages/jsii-reflect/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3331 chore(merge-back): 1.52.1
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3318 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3335 chore: transition from using colors to chalk
  packages/jsii-reflect/bin/jsii-tree.ts
  packages/jsii-reflect/lib/tree.ts
  packages/jsii-reflect/package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3316 feat(go): add UnsafeCast function
  .github/workflows/main.yml
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime-test/project/internal/cdk16625/cdk16625.go
  packages/@jsii/go-runtime-test/project/tools.go
  packages/@jsii/go-runtime/jsii-runtime-go/cast.go
  packages/@jsii/go-runtime/jsii-runtime-go/cast_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/manage-object.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/objectstore.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/typeregistry.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime/runtime.go
  packages/@jsii/kernel/lib/api.ts
  packages/@jsii/kernel/lib/kernel.ts
  packages/@jsii/kernel/lib/objects.ts
  packages/@jsii/kernel/lib/serialization.ts
  superchain/Dockerfile
  superchain/README.md
  tools/jsii-compliance/suite.ts
Labels: pr/ready-to-merge, contribution/core

#3339 fix(kernel): kernel's private object annotations are enumerable
  packages/@jsii/kernel/lib/objects.ts
  packages/@jsii/kernel/test/objects.test.ts
Labels: pr/ready-to-merge, contribution/core

#3309 feat: add configuration for Visual Studio Code
  .devcontainer.json
  .dockerignore
Labels: pr/ready-to-merge

#3337 docs(go): document UnsafeCast feature
  gh-pages/content/user-guides/lib-user/language-specific/go.md
Labels: pr/ready-to-merge, contribution/core

#3338 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3340 fix(superchain): failure to download PowerShell
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3347 fix(jsii): submodule READMEs don't have literate examples
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/literate.ts
  packages/jsii/test/literate.test.ts
  packages/jsii/test/submodules.test.ts
Labels: pr/ready-to-merge, contribution/core

#3351 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/runtime/package.json
  packages/jsii-diff/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3321 fix(go): unable to reuse instances between child/parent interfaces
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/objectstore.go
Labels: pr/ready-to-merge, contribution/core

#3355 fix(dontet): excessive overrides generated
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/JsiiMethodAttribute.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/JsiiPropertyAttribute.cs
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetruntimegenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.ts.snap
Labels: language/dotnet, pr/ready-to-merge, contribution/core
