Repository aws/jsii, pull requests merged in 2022-05, with the labels that each got.

#3511 chore(superchain): change default node version to 14
  .github/workflows/docker-images.yml
  superchain/Dockerfile
  superchain/README.md
Labels: contribution/core

#3515 ci: remove usage of semantic pr app for action
  .github/semantic.yml
  .github/workflows/pull-request-lint.yml
  .mergify/config.yml
Labels: contribution/core

#3518 fix(pacmak): missing python artifacts when using relative -o path
  .all-contributorsrc
  README.md
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/test/build-test.sh
Labels: bug, pr/ready-to-merge, effort/small, module/pacmak, contribution/core

#3517 fix: incorrect token for benchmark action
  .github/workflows/main.yml
Labels: pr/ready-to-merge, contribution/core

#3526 chore(merge-back): 1.58.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3528 fix(jsii): deprecation warnings use this.constructor before calling super
  .all-contributorsrc
  README.md
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3521 feat(jsii): enable source maps for declaration files
  packages/@fixtures/jsii-calc-bundled/.gitignore
  packages/@jsii/benchmarks/.gitignore
  packages/@jsii/check-node/.gitignore
  packages/@jsii/dotnet-runtime-test/.gitignore
  packages/@jsii/dotnet-runtime/.gitignore
  packages/@jsii/go-runtime-test/.gitignore
  packages/@jsii/go-runtime/.gitignore
  packages/@jsii/integ-test/.gitignore
  packages/@jsii/integ-test/package.json
  packages/@jsii/integ-test/tsconfig.json
  packages/@jsii/java-runtime/.gitignore
  packages/@jsii/kernel/.gitignore
  packages/@jsii/runtime/.gitignore
  packages/@jsii/spec/.gitignore
  packages/@scope/jsii-calc-base-of-base/.gitignore
  packages/@scope/jsii-calc-base/.gitignore
  packages/@scope/jsii-calc-lib/.gitignore
  packages/codemaker/.gitignore
  packages/jsii-calc/.gitignore
  packages/jsii-config/.gitignore
  packages/jsii-diff/.gitignore
  packages/jsii-pacmak/.gitignore
  packages/jsii-reflect/.gitignore
  packages/jsii-rosetta/.gitignore
  packages/jsii-rosetta/lib/typescript/ts-compiler.ts
  packages/jsii/.gitignore
  packages/jsii/lib/compiler.ts
  packages/jsii/test/compiler.test.ts
  packages/jsii/test/deprecated-remover.test.ts
  packages/jsii/vendor/.gitignore
  packages/oo-ascii-tree/.gitignore
  tools/jsii-build-tools/.gitignore
  tsconfig-base.json
Labels: pr/ready-to-merge

#3532 chore: npm-check-updates && yarn upgrade
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/@jsii/benchmarks/bin/benchmark.ts
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: dependencies, pr/do-not-merge, contribution/core, auto-approve

#3535 chore(@jsii/kernel): build out-of-tree
  .gitignore
  packages/@jsii/kernel/.gitignore
  packages/@jsii/kernel/.npmignore
  packages/@jsii/kernel/src/api.ts
  packages/@jsii/kernel/src/index.ts
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/objects.test.ts
  packages/@jsii/kernel/src/objects.ts
  packages/@jsii/kernel/src/on-exit.ts
  packages/@jsii/kernel/src/recording.ts
  packages/@jsii/kernel/src/serialization.test.ts
  packages/@jsii/kernel/src/serialization.ts
  packages/@jsii/kernel/tsconfig.json
  packages/@jsii/python-runtime/build-tools/deps.ts
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/test/playback.test.ts
  packages/@jsii/spec/lib/assembly.js.map
  packages/@jsii/spec/lib/configuration.js.map
  packages/@jsii/spec/lib/index.js.map
  packages/@jsii/spec/lib/name-tree.js.map
  packages/@jsii/spec/lib/name-tree.test.js.map
  packages/@jsii/spec/lib/validate-assembly.js.map
  packages/@jsii/spec/lib/validate-assembly.test.js.map
  packages/jsii-pacmak/test/build-test.sh
Labels: pr/ready-to-merge, contribution/core

#3540 fix(python): cannot import nested submodules
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: pr/ready-to-merge, contribution/core

#3546 chore(merge-back): 1.59.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3537 chore: npm-check-updates && yarn upgrade
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3539 chore: stop using ts-jest
  .github/workflows/yarn-upgrade.yml
  jest.config.ts
  package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/runtime/test/__snapshots__/kernel-host.test.js.snap
  packages/@jsii/runtime/test/playback.test.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii/package.json
  packages/jsii/test/__snapshots__/negatives.test.js.snap
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3553 fix(jsii): `assert` not allowed as interface member
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3556 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/spec/package.json
  packages/jsii-diff/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3534 chore(@jsii/spec): build out-of-tree
  packages/@jsii/spec/.gitignore
  packages/@jsii/spec/.npmignore
  packages/@jsii/spec/build-tools/generate-json-schema.sh
  packages/@jsii/spec/lib/assembly.js.map
  packages/@jsii/spec/lib/configuration.js.map
  packages/@jsii/spec/lib/index.js.map
  packages/@jsii/spec/lib/name-tree.js.map
  packages/@jsii/spec/lib/name-tree.test.js.map
  packages/@jsii/spec/lib/validate-assembly.js.map
  packages/@jsii/spec/lib/validate-assembly.test.js.map
  packages/@jsii/spec/package.json
  packages/@jsii/spec/src/assembly.ts
  packages/@jsii/spec/src/configuration.ts
  packages/@jsii/spec/src/index.ts
  packages/@jsii/spec/src/name-tree.test.ts
  packages/@jsii/spec/src/name-tree.ts
  packages/@jsii/spec/src/validate-assembly.test.ts
  packages/@jsii/spec/src/validate-assembly.ts
  packages/@jsii/spec/test-data/previous-assemblies/0.21.2.jsii.json
  packages/@jsii/spec/tsconfig.json
  tsconfig-base.json
Labels: pr/ready-to-merge, contribution/core

#3564 chore: remove Go dev preview from docs
  gh-pages/content/overview/features.md
  gh-pages/content/user-guides/lib-author/configuration/targets/go.md
  gh-pages/content/user-guides/lib-user/language-specific/go.md
Labels: pr/ready-to-merge, contribution/core

#3565 fix(@jsii/spec): speed up assembly validation by 20x for large libraries
  packages/@jsii/spec/package.json
  packages/@jsii/spec/src/validate-assembly.ts
  yarn.lock
Labels: contribution/core
