Repository aws/jsii, pull requests merged in 2022-11, with the labels that each got.

#3821 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3827 chore(release): 1.71.0
  .all-contributorsrc
  .github/workflows/auto-approve.yml
  CHANGELOG.md
  README.md
  gh-pages/requirements-dev.txt
  jest.config.mjs
  lerna.json
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-calc/lib/homonymous/README.md
  packages/jsii-calc/lib/homonymous/bar.ts
  packages/jsii-calc/lib/homonymous/foo.ts
  packages/jsii-calc/lib/homonymous/index.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/package.json
  packages/jsii-diff/lib/type-comparison.ts
  packages/jsii-diff/test/classes.test.ts
  packages/jsii-diff/test/util.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/lib/module-like.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  superchain/Dockerfile
  superchain/amazon-ssm-agent.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3830 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3796 chore: fix typo in benchmark.ts
  packages/@jsii/benchmarks/bin/benchmark.ts
Labels: pr/ready-to-merge

#3842 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3848 fix(python): parameter names shadow imported modules
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/targets/python/type-name.test.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3850 fix: revert "chore(deps): Bump aws-actions/stale-issue-cleanup from 5 to 6"
  .github/workflows/close-stale-issues.yml
Labels: pr/ready-to-merge, contribution/core

#3794 feat(python): streaming bin script output
  packages/@jsii/kernel/src/api.ts
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/base.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii-calc/bin/run.ts
Labels: pr/ready-to-merge

#3847 fix(python): dereference values returned from Kernel.ainvoke
  .all-contributorsrc
  README.md
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
Labels: pr/ready-to-merge

#3852 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3841 feat(check-node): allow silencing @jsii/check-node warnings
  .github/workflows/main.yml
  .mergify/config.yml
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/check-node/src/index.ts
  packages/jsii-config/test/index.test.ts
Labels: pr/ready-to-merge, contribution/core

#3855 fix(dotnet): broken error name deserialization
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/dotnet-runtime-test/build.sh
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Client/ClientTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Api/NamedError.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Api/Request/CompleteRequest.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Api/Response/ErrorResponse.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Client.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/IClient.cs
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/@jsii/kernel/src/api.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-calc/lib/cdk22369/index.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  tools/jsii-compliance/suite.ts
Labels: pr/ready-to-merge, contribution/core
