Repository aws/jsii, pull requests merged in 2022-04, with the labels that each got.

#3473 chore: cache the results of `findPackageInfo`
  packages/jsii/lib/assembler.ts
Labels: pr/ready-to-merge, contribution/core

#3475 feat: expose unknownSnippets config
  packages/jsii-rosetta/lib/commands/transliterate.ts
Labels: pr/ready-to-merge, contribution/core

#3474 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.ts.snap
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3485 fix(go): object type not recognized
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
Labels: pr/ready-to-merge, contribution/core

#3491 fix(jsii): some submodules are not exported from `aws-cdk-lib`
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
Labels: contribution/core

#3492 chore(release): 1.57.0
  .github/workflows/close-stale-issues.yml
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/conversions.go
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii/bin/jsii.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/test/compiler.test.ts
Labels: pr/no-squash

#3472 chore: drop support for Python 3.6 (EOL as of 2021-12-23)
  .github/workflows/main.yml
  .mergify/config.yml
  CONTRIBUTING.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  packages/@jsii/python-runtime/build-tools/deps.ts
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.ts.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
Labels: contribution/core

#3488 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3496 chore(jsii): improve error message when jsii dep fails to resolve
  packages/jsii/lib/project-info.ts
Labels: contribution/core

#3478 fix(rosetta): attempts transliteraiton to unsupported languages
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/languages/target-language.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
Labels: contribution/core

#3499 chore: automated node runtime deprecation warnings
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  .mergify/config.yml
  gh-pages/content/user-guides/lib-author/index.md
  gh-pages/partials/node-support-table.md
  packages/@jsii/check-node/package.json
  packages/@jsii/check-node/src/constants.test.ts
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/check-node/src/index.test.ts
  packages/@jsii/check-node/src/index.ts
  superchain/README.md
Labels: contribution/core
