Repository aws/jsii, pull requests merged in 2022-06, with the labels that each got.

#3571 chore(codemaker): build out-of-tree
  packages/codemaker/.gitignore
  packages/codemaker/.npmignore
  packages/codemaker/src/case-utils.test.ts
  packages/codemaker/src/case-utils.ts
  packages/codemaker/src/codemaker.test.ts
  packages/codemaker/src/codemaker.ts
  packages/codemaker/src/filebuff.test.ts
  packages/codemaker/src/filebuff.ts
  packages/codemaker/src/index.ts
  packages/codemaker/tsconfig.json
Labels: contribution/core

#3572 chore(oo-ascii-tree): build out-of-tree
  packages/oo-ascii-tree/.gitignore
  packages/oo-ascii-tree/.npmignore
  packages/oo-ascii-tree/src/ascii-tree.ts
  packages/oo-ascii-tree/src/index.ts
  packages/oo-ascii-tree/src/tree.test.ts
  packages/oo-ascii-tree/test-data/basic.expected.txt
  packages/oo-ascii-tree/test-data/big.expected.txt
  packages/oo-ascii-tree/test-data/extend.expected.txt
  packages/oo-ascii-tree/test-data/multiline.expected.txt
  packages/oo-ascii-tree/test/.gitignore
  packages/oo-ascii-tree/tsconfig.json
Labels: contribution/core

#3579 chore(jsii-rosetta): export `GoVisitor` from index
  packages/jsii-rosetta/lib/index.ts
Labels: pr/ready-to-merge, contribution/core

#3590 chore(release): v1.60.1
  CHANGELOG.md
  lerna.json
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/check-node/tsconfig.json
  packages/@jsii/runtime/webpack.config.js
Labels: pr/ready-to-merge, contribution/core

#3591 chore(merge-back): 1.60.1
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3583 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/runtime/package.json
  packages/jsii-diff/package.json
  packages/jsii/package.json
  tools/jsii-build-tools/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3585 fix: instantiate perf observer for each iteration
  packages/@jsii/benchmarks/bin/benchmark.ts
  packages/@jsii/benchmarks/lib/benchmark.ts
Labels: pr/ready-to-merge, contribution/core

#3573 feat: add support for using custom .m2 directory
  .all-contributorsrc
  README.md
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/targets/java.ts
Labels: pr/ready-to-merge

#3598 chore: cache heavy elements in assemblyRelativeSourceFile
  packages/@jsii/benchmarks/lib/benchmark.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/utils.ts
Labels: pr/ready-to-merge, contribution/core

#3601 chore(superchain): update to Maven 3.8.6
  superchain/Dockerfile
Labels: contribution/core

#3604 chore: switch dotnet feed to avoid CDN caching
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3603 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3606 chore: update layer cache last in workflow
  .github/workflows/docker-images.yml
Labels: contribution/core

#3607 fix: Status icon for Go language that it is generally available.
  gh-pages/content/overview/features.md
Labels: pr/ready-to-merge

#3608 chore(merge-back): 1.61.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3596 chore: keep @jsii/kernel loadable with Node 12+
  packages/@jsii/kernel/tsconfig.json
  packages/@jsii/runtime/tsconfig.json
Labels: pr/ready-to-merge, contribution/core

#3622 chore: run benchmarks in separate VMs
  .github/workflows/main.yml
  packages/@jsii/benchmarks/lib/benchmark.ts
  packages/@jsii/benchmarks/lib/index.ts
  packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/build-with-jsii.ts
  packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/build-with-tsc.ts
  packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/index.ts
  packages/@jsii/benchmarks/lib/util.ts
Labels: pr/ready-to-merge, contribution/core

#3570 feat(@jsii/utils): add a utility library to be consumed by jsii modules
  packages/@jsii/spec/package.json
  packages/@jsii/spec/src/assembly-utils.test.ts
  packages/@jsii/spec/src/assembly-utils.ts
  packages/@jsii/spec/src/assembly.ts
  packages/@jsii/spec/src/index.ts
  packages/jsii/lib/assembler.ts
Labels: pr/ready-to-merge

#3625 chore: register missing go project with dependabot
  .github/dependabot.yml
Labels: contribution/core
