Repository aws/jsii, pull requests merged in 2022-07, with the labels that each got.

#3646 fix: jitter Docker build startup
  .github/workflows/docker-images.yml
Labels: pr/ready-to-merge, contribution/core

#3632 chore: add UX tests around @jsii/kernel serializer errors
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/serialization.test.ts
  packages/@jsii/kernel/src/serialization.ts
  packages/@jsii/kernel/src/serialization.ux.test.ts
Labels: pr/ready-to-merge, contribution/core

#3631 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3648 chore(@jsii/kernel): various improvements
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/objects.ts
Labels: pr/ready-to-merge, contribution/core

#3652 feat(rosetta): tablets can be compressed
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
Labels: pr/ready-to-merge

#3655 chore(mergify): add team members to contribution/core
  .mergify/config.yml
Labels: pr/ready-to-merge

#3662 feat(jsii): allow specifying baseUrl and paths in tsconfig.json
  gh-pages/content/user-guides/lib-author/configuration/index.md
  packages/jsii/lib/project-info.ts
Labels: pr/ready-to-merge, contribution/core

#3663 chore: stop testing .NET 5
  .github/workflows/main.yml
  .mergify/config.yml
Labels: contribution/core

#3659 chore(merge-back): 1.62.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3667 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3664 fix(go): unused imports emitted for type unions
  packages/jsii-pacmak/jest.config.mjs
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/test/targets/fixtures/base.jsii.json
  packages/jsii-pacmak/test/targets/fixtures/dependent.jsii.json
  packages/jsii-pacmak/test/targets/go.test.ts
Labels: pr/ready-to-merge, contribution/core

#3660 feat(python): add dynamic type checking
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/src/jsii/_reference_map.py
  packages/@jsii/python-runtime/tests/test_python.py
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3669 fix(rosetta): infuse incorrectly handles compressed assemblies
  packages/@jsii/spec/src/assembly-utils.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
Labels: pr/ready-to-merge, contribution/core

#3670 fix(rosetta): tablet compression handled incorrectly in multiple places
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/commands/trim-cache.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii-rosetta/test/commands/trim-cache.test.ts
Labels: pr/ready-to-merge, contribution/core

#3679 chore: federate into AWS to authenticate to ECR Public
  .github/workflows/docker-images.yml
Labels: contribution/core

#3672 chore(java): extend dependency ranges to allow new versions
  packages/@jsii/java-runtime/pom.xml.t.js
Labels: contribution/core

#3680 chore(release): 1.63.0
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  .mergify/config.yml
  CHANGELOG.md
  gh-pages/content/user-guides/lib-author/configuration/index.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/src/jsii/_reference_map.py
  packages/@jsii/python-runtime/tests/test_python.py
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/@jsii/spec/src/assembly-utils.ts
  packages/jsii-diff/package.json
  packages/jsii-pacmak/jest.config.mjs
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-pacmak/test/targets/fixtures/base.jsii.json
  packages/jsii-pacmak/test/targets/fixtures/dependent.jsii.json
  packages/jsii-pacmak/test/targets/go.test.ts
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/lib/class.ts
  packages/jsii-reflect/lib/interface.ts
  packages/jsii-reflect/lib/module-like.ts
  packages/jsii-reflect/lib/submodule.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/lib/util.ts
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/commands/trim-cache.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/infuse.test.ts
  packages/jsii-rosetta/test/commands/trim-cache.test.ts
  packages/jsii/lib/project-info.ts
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3681 chore(merge-back): 1.63.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3684 chore(release): 1.63.1
  CHANGELOG.md
  lerna.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/targets/python/type-name.test.ts
Labels: contribution/core

#3688 fix(pyhon): under-qualified types used by dynamic type checking
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-rosetta/jest.config.mjs
Labels: contribution/core

#3682 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-diff/package.json
  packages/jsii-rosetta/jest.config.mjs
  packages/jsii/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3689 chore(release): 1.63.2
  CHANGELOG.md
  lerna.json
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/@jsii/runtime/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-rosetta/jest.config.mjs
  packages/jsii/package.json
  yarn.lock
Labels: pr/no-squash
