Repository aws/jsii, pull requests merged in 2022-09, with the labels that each got.

#3737 chore: update sudoers settings
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3739 chore(release): 1.67.0
  .all-contributorsrc
  .github/workflows/main.yml
  CHANGELOG.md
  README.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/TypeCheckingTest.java
  packages/@jsii/java-runtime/lib/index.ts
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Configuration.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectRef.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/UnsafeCast.java
  packages/@jsii/java-runtime/project/src/test/java/software/amazon/jsii/UnsafeCastTest.java
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/src/disk-cache/digest-file.ts
  packages/@jsii/kernel/src/disk-cache/disk-cache.ts
  packages/@jsii/kernel/src/disk-cache/index.ts
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/link.ts
  packages/@jsii/kernel/src/objects.ts
  packages/@jsii/kernel/src/tar-cache/default-cache-root.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/runtime/lib/host.ts
  packages/@jsii/runtime/lib/program.ts
  packages/jsii-pacmak/generate.sh
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  superchain/Dockerfile
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3740 chore(merge-back): 1.67.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3748 perf(jsii-pacmak): cache type lookups for go
  packages/jsii-pacmak/lib/targets/go/package.ts
Labels: pr/ready-to-merge

#3752 fix(jsii): unable to return Promise<void>
  packages/jsii/lib/assembler.ts
  packages/jsii/test/__snapshots__/negatives.test.js.snap
  packages/jsii/test/promise.test.ts
Labels: pr/ready-to-merge, contribution/core

#3736 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/test/__snapshots__/kernel-host.test.js.snap
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  packages/jsii/test/deprecated-remover.test.ts
  packages/jsii/test/deprecation-warnings.test.ts
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3758 chore(superchain): grant passwordless sudo to superchain user
  superchain/Dockerfile
  superchain/dockerd-entrypoint.sh
Labels: pr/ready-to-merge, contribution/core

#3761 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3760 fix(pacmak): .NET bindings fail to compile with error CS8120
  .all-contributorsrc
  README.md
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/union.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  tsconfig-base.json
Labels: pr/ready-to-merge, contribution/core

#3757 chore(pacmak): use Map instead of object
  packages/jsii-pacmak/lib/targets/go/package.ts
Labels: pr/ready-to-merge, contribution/core

#3763 fix(runtime): type not found
  .all-contributorsrc
  README.md
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/go-runtime-test/project/compliance_test.go
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/objects.ts
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@scope/jsii-calc-lib/deprecated-to-strip.txt
  packages/@scope/jsii-calc-lib/lib/deprecation-removal.ts
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii/bin/jsii.ts
  packages/jsii/test/deprecation-warnings.test.ts
  tools/jsii-compliance/suite.ts
Labels: pr/ready-to-merge, contribution/core

#3766 chore(merge-back): 1.68.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3756 fix(jsii): missing deprecation warning in collections
  packages/jsii/jest.config.mjs
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3762 fix(python): bin script python support, test argument passing
  .all-contributorsrc
  README.md
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii-calc/bin/run.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge

#3764 feat(dotnet): distinguish error types
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Client/RuntimeTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/JsiiTypeAttributeBase.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsiiException.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Api/Response/ErrorResponse.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Client.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/ITypeCache.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/ReferenceMap.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/ResourceExtractor.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Runtime.cs
Labels: pr/ready-to-merge, contribution/core

#3754 chore(jsii): enable skipLibCheck
  packages/jsii/lib/compiler.ts
  packages/jsii/test/compiler.test.ts
Labels: pr/ready-to-merge, contribution/core

#3769 fix(kernel): EPERM on rename operation on Windows
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
Labels: pr/ready-to-merge, contribution/core

#3770 chore: add @andipabst to all-contributors manifest
  .all-contributorsrc
  README.md
Labels: contribution/core, auto-approve

#3773 chore(release): 1.69.0
  .all-contributorsrc
  .github/workflows/main.yml
  CHANGELOG.md
  README.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Client/RuntimeTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/DeputyBase.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/JsiiTypeAttributeBase.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsiiException.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/JsonModel/Api/Response/ErrorResponse.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Client.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/ITypeCache.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/ReferenceMap.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/ResourceExtractor.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Runtime.cs
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii-calc/bin/run.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii/jest.config.mjs
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/compiler.test.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, pr/no-squash

#3776 chore(merge-back): 1.69.0
  .github/workflows/main.yml
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3774 chore: drop support for go < 1.18
  .github/workflows/main.yml
  .mergify/config.yml
  CONTRIBUTING.md
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3778 fix(jsii-reflect): TypeMember is not SourceLocatable
  packages/jsii-reflect/lib/type-member.ts
Labels: pr/ready-to-merge

#3780 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve
