Repository aws/jsii, pull requests merged in 2022-10, with the labels that each got.

#3783 feat(superchain): add 'acl' package to support projen GHA
  superchain/Dockerfile
Labels: pr/ready-to-merge

#3790 chore(spec): improve assembly validation error messages
  packages/@jsii/spec/src/assembly-utils.test.ts
  packages/@jsii/spec/src/assembly-utils.ts
  packages/@jsii/spec/src/redirect.ts
  packages/@jsii/spec/src/validate-assembly.test.ts
  packages/@jsii/spec/src/validate-assembly.ts
Labels: pr/ready-to-merge, contribution/core

#3791 fix(python): KeyError in type checks when decorating methods
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3792 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3799 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3805 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3807 chore(merge-back): 1.70.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3814 chore: fix auto-approve workflow
  .github/workflows/auto-approve.yml
Labels: pr/ready-to-merge, contribution/core
