Repository aws/jsii, pull requests merged in 2022-03, with the labels that each got.

#3409 fix(go): lots of documentation is missing from generated code
  packages/jsii-pacmak/lib/targets/go/documentation.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.ts.snap
Labels: pr/ready-to-merge, contribution/core

#3404 chore(mergify): add TheRealAmazonKendra to mergify
  .mergify/config.yml
Labels: pr/ready-to-merge

#3407 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/lib/compiler.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  tools/jsii-compliance/suite.ts
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3416 chore(merge-back): 1.55.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3413 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve

#3429 chore(release): 1.55.1
  .github/workflows/gh-pages.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  lerna.json
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  superchain/Dockerfile
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3434 chore(merge-back): 1.55.1
  CHANGELOG.md
  lerna.json
  superchain/Dockerfile
Labels: pr/no-squash, auto-approve

#3427 chore: update gitigonre to ignore build, coverage and jsii-outdir
  .gitignore
Labels: pr/ready-to-merge, contribution/core

#3432 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/go-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3437 feat: specify output directory for assemblies
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
Labels: pr/ready-to-merge, contribution/core

#3440 chore: npm-check-updates && yarn upgrade
  package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3419 fix: typo "though" -> "through"
  gh-pages/content/overview/runtime-architecture.md
Labels: pr/ready-to-merge

#3426 feat: drop internal functions from Deprecation Error stack trace
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3449 fix(rosetta): incorrect transliteration of map keys in python
  .all-contributorsrc
  README.md
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.ts.snap
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/test/translations/expressions/map-literal.cs
  packages/jsii-rosetta/test/translations/expressions/map-literal.go
  packages/jsii-rosetta/test/translations/expressions/map-literal.java
  packages/jsii-rosetta/test/translations/expressions/map-literal.py
  packages/jsii-rosetta/test/translations/expressions/map-literal.ts
Labels: pr/ready-to-merge, contribution/core

#3450 chore(jsii): revert to using Set
  packages/jsii/lib/transforms/deprecation-warnings.ts
  packages/jsii/test/deprecation-warnings.test.ts
Labels: pr/ready-to-merge, contribution/core

#3445 chore: replace deprecated String.prototype.substr()
  eslint-config.yaml
  packages/@jsii/kernel/lib/serialization.ts
  packages/@jsii/runtime/lib/in-out.ts
  packages/codemaker/lib/case-utils.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-reflect/lib/source.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/markdown/markdown-renderer.ts
  packages/jsii-rosetta/test/translations.test.ts
  packages/jsii/lib/docs.ts
  packages/jsii/lib/literate.ts
Labels: pr/ready-to-merge
