Repository aws/jsii, pull requests merged in 2022-08, with the labels that each got.

#3690 chore(merge-back): 1.63.2
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, auto-approve

#3691 chore: stop testing Node 17 (EOL for > 1 month)
  .github/workflows/main.yml
  .mergify/config.yml
  CONTRIBUTING.md
  packages/@jsii/check-node/src/index.test.ts
Labels: contribution/core

#3676 feat(.net): embed package icon when configured
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
Labels: pr/ready-to-merge, contribution/core

#3696 chore: move replaceAssembly to @jsii/spec and expose it
  packages/@jsii/spec/src/assembly-utils.ts
  packages/jsii-rosetta/lib/commands/infuse.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/package.json
Labels: pr/ready-to-merge, contribution/core

#3668 feat(.net): dynmic type checking for union-typed parameters
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.sln.DotSettings.user
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/TypeCheckingTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Configuration.cs
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnettyperesolver.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3694 fix(python): classproperty not working with type checkers
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/src/jsii/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/python-runtime/src/jsii/_reference_map.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/src/jsii/_utils.py
  packages/@jsii/python-runtime/src/jsii/python.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/python-runtime/tests/test_python.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/python-pyright.test.ts
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3704 chore(merge-back): 1.64.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3705 chore(python): fix typo in type-name.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
Labels: pr/ready-to-merge

#3701 chore: npm-check-updates && yarn upgrade
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/@jsii/benchmarks/package.json
  packages/jsii-config/package.json
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3709 fix(dotnet): AnonymousObject fails runtime type checks
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/TypeCheckingTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/AnonymousObject.cs
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-calc/lib/anonymous/index.ts
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: bug, language/dotnet, pr/ready-to-merge, p1, contribution/core

#3710 feat(pacmak): allow opt-out of runtime type checking generation
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/target.ts
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/js.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/targets/go.test.ts
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3713 chore(release): 1.65.0
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/TypeCheckingTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Deputy/AnonymousObject.cs
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-calc/lib/anonymous/index.ts
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/package.json
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/generator.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/target.ts
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/js.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/targets/go.test.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3715 chore(merge-back): 1.65.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3718 feat(go): emit deprecation warning when using go1.16 and go1.17
  .github/workflows/main.yml
  gh-pages/content/user-guides/lib-author/index.md
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/deprecationwarning.go
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/internal/compiler/go1.16.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/compiler/go1.17.go
  packages/jsii-pacmak/lib/targets/go.ts
  superchain/Dockerfile
  superchain/README.md
Labels: contribution/core

#3720 fix(.net): missing dynamic type checking for collection-nested unions
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/TypeCheckingTests.cs
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnettyperesolver.ts
  packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3712 feat(go): runtime type check type unions
  .github/dependabot.yml
  packages/@jsii/go-runtime-test/build-tools/go-run.ts
  packages/@jsii/go-runtime-test/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime-test/project/runtime_type_checking_test.go
  packages/@jsii/go-runtime/build-tools/go-run.ts
  packages/@jsii/go-runtime/go.mod
  packages/@jsii/go-runtime/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/cast.go
  packages/@jsii/go-runtime/jsii-runtime-go/deprecated.go
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/internal/api/api.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/client_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/load.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/handshake.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/objectstore/objectstore.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/registration.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/typeregistry.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/typeregistry/validate-struct.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime/runtime.go
  packages/@jsii/go-runtime/jsii-runtime-go/runtime/type_checking.go
  packages/@jsii/go-runtime/jsii-runtime-go/tools.go
  packages/@jsii/go-runtime/package.json
  packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/dependencies.ts
  packages/jsii-pacmak/lib/targets/go/emit-context.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/lib/targets/go/runtime/class-constructor.ts
  packages/jsii-pacmak/lib/targets/go/runtime/method-call.ts
  packages/jsii-pacmak/lib/targets/go/runtime/property-access.ts
  packages/jsii-pacmak/lib/targets/go/runtime/runtime-type-checking.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/interface.ts
  packages/jsii-pacmak/lib/targets/go/types/struct.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
Labels: language/go, contribution/core

#3722 fix: type unions in variadic position leads to invalid code-gen
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/TypeCheckingTests.cs
  packages/@jsii/go-runtime-test/project/runtime_type_checking_test.go
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts
  packages/jsii-pacmak/lib/targets/go/runtime/runtime-type-checking.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: contribution/core

#3723 fix(rosetta): rosetta reader expects default tablet file to be uncompressed
  packages/jsii-rosetta/lib/commands/extract.ts
  packages/jsii-rosetta/lib/jsii/assemblies.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/test/commands/extract.test.ts
  packages/jsii-rosetta/test/commands/transliterate.test.ts
Labels: pr/ready-to-merge, contribution/core

#3728 fix(python): reference to type does not use alias
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
Labels: pr/ready-to-merge, contribution/core

#3729 chore(release): v1.65.1
  CHANGELOG.md
  lerna.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
Labels: pr/ready-to-merge, contribution/core, pr/no-squash

#3731 chore(merge-back): 1.65.1
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3733 chore(merge-back): 1.66.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3703 feat(java): dynamic type checking for union-typed parameters
  .all-contributorsrc
  README.md
  packages/@jsii/java-runtime-test/project/src/test/java/software/amazon/jsii/testing/TypeCheckingTest.java
  packages/@jsii/java-runtime/lib/index.ts
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Configuration.java
  packages/jsii-pacmak/generate.sh
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3721 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3730 feat(java): utility to perform unsafe cast
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiObjectRef.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/UnsafeCast.java
  packages/@jsii/java-runtime/project/src/test/java/software/amazon/jsii/UnsafeCastTest.java
Labels: pr/ready-to-merge, contribution/core

#3724 feat(kernel): experimental runtime package cache
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/src/disk-cache/digest-file.ts
  packages/@jsii/kernel/src/disk-cache/disk-cache.ts
  packages/@jsii/kernel/src/disk-cache/index.ts
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/link.ts
  packages/@jsii/kernel/src/objects.ts
  packages/@jsii/kernel/src/tar-cache/default-cache-root.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/@jsii/runtime/lib/host.ts
  packages/@jsii/runtime/lib/program.ts
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3735 fix(java): type generation code-gen issues
  .github/workflows/main.yml
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
Labels: pr/ready-to-merge, contribution/core
