Repository aws/jsii, pull requests merged in 2023-09, with the labels that each got.

#4253 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4267 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4272 chore(release): 1.89.0
  .github/workflows/docker-images.yml
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  .mergify/config.yml
  CHANGELOG.md
  gh-pages/partials/node-support-table.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/lib/transforms/runtime-info.ts
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4274 docs(jsii-diff): explain making properties optional
  packages/jsii-diff/BREAKING_CHANGES.md
  packages/jsii-diff/README.md
Labels: pr/ready-to-merge, contribution/core

#4279 perf(jsii-reflect): Cache classes in TypeSystem.
  packages/jsii-reflect/lib/type-system.ts
Labels: pr/do-not-merge, contribution/core
