Repository aws/jsii, pull requests merged in 2023-06, with the labels that each got.

#4134 chore(release): 1.83.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  superchain/Dockerfile
  superchain/README.md
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4126 chore: test for Node 20, set default to node 16
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  .mergify/config.yml
  packages/@fixtures/jsii-calc-bundled/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/java-runtime-test/package.json
  packages/@jsii/java-runtime-test/pom.xml.t.js
  packages/@jsii/java-runtime/package.json
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-build-tools/package.json
Labels: contribution/core

#4137 chore(merge-back): 1.83.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4139 chore: fix 1.83.0 release notes
  CHANGELOG.md
Labels: pr/ready-to-merge, contribution/core

#4138 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@jsii/spec/src/assembly-utils.test.ts
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4145 feat(jsii): allow specifying a deprecation message regardless of stability
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii/lib/project-info.ts
Labels: pr/ready-to-merge, contribution/core

#4142 chore(comments): correct spelling
  packages/@jsii/kernel/src/api.ts
  packages/@jsii/kernel/src/link.ts
  packages/@jsii/runtime/lib/host.ts
Labels: pr/ready-to-merge

#4143 chore(runtime): correct return types for completeCallback and processRequest
  packages/@jsii/runtime/lib/host.ts
Labels: pr/ready-to-merge

#4146 chore(release): 1.84.0
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  .mergify/config.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@fixtures/jsii-calc-bundled/package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/dotnet-runtime-test/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/java-runtime-test/package.json
  packages/@jsii/java-runtime-test/pom.xml.t.js
  packages/@jsii/java-runtime/package.json
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@jsii/spec/src/assembly-utils.test.ts
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-lib/package.json
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/lib/project-info.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  superchain/Dockerfile
  tools/jsii-build-tools/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4148 chore: upgrade lerna to 7.0.x and migrate config
  lerna.json
  package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#4149 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4135 chore: simplify branch protection configuration
  .github/workflows/docker-images.yml
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/pull-request-lint.yml
Labels: pr/ready-to-merge, contribution/core

#4157 chore: fix confusing comment about FD number 4 that does not exist
  packages/@jsii/runtime/bin/jsii-runtime.ts
Labels: pr/ready-to-merge, contribution/core
