Repository aws/jsii, pull requests merged in 2023-04, with the labels that each got.

#4037 fix(jsii): incorrect symbol-id generated with typesVersions
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/types-versions.ts
  packages/jsii/test/types-versions.test.ts
Labels: pr/ready-to-merge, contribution/core

#4030 fix: enable dereference when copying module to tmp dir
  packages/jsii-pacmak/lib/packaging.ts
Labels: pr/ready-to-merge

#4040 docs: refer to ECR Public image
  CONTRIBUTING.md
  README.md
  gh-pages/content/specification/5-new-language-intake.md
  gh-pages/content/user-guides/language-support/index.md
  superchain/Dockerfile
  superchain/README.md
  superchain/build-local.sh
Labels: pr/ready-to-merge, contribution/core

#4041 chore(release): 1.80.0
  .github/workflows/docker-images.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  gh-pages/content/specification/5-new-language-intake.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-rosetta/lib/json.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/json.test.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/types-versions.ts
  packages/jsii/test/types-versions.test.ts
  superchain/Dockerfile
  superchain/README.md
  superchain/build-local.sh
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4042 chore(merge-back): 1.80.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4043 fix(rosetta): flakey trim-cache test
  packages/jsii-rosetta/lib/json.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
Labels: pr/ready-to-merge, contribution/core

#4045 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4055 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4058 chore: remove node: pseudo-protocol
  packages/jsii-rosetta/lib/json.ts
Labels: pr/ready-to-merge, contribution/core

#4063 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4067 docs: publish jsii@1.x and jsii-rosetta@1.x maintenance announcement
  README.md
  gh-pages/content/compiler-and-rosetta-maintenance.md
  gh-pages/content/overview/toolchain.md
  gh-pages/mkdocs.yml
Labels: pr/ready-to-merge, contribution/core

#4071 chore: add upgrade prompt at load of jsii and jsii-rosetta 1.x
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/upgrade-prompt.ts
  packages/jsii/lib/index.ts
  packages/jsii/lib/upgrade-prompt.ts
Labels: pr/ready-to-merge, contribution/core

#4064 chore: added colifran to mergify config file
  .mergify/config.yml
Labels: pr/ready-to-merge
