Repository aws/jsii, pull requests merged in 2023-11, with the labels that each got.

#4313 chore: fix pages build
  gh-pages/mkdocs.yml
Labels: pr/ready-to-merge, contribution/core

#4239 chore: switch to python 3.8
  .github/workflows/main.yml
  CONTRIBUTING.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4317 revert: "switch to python 3.8 (#4239)"
  .github/workflows/main.yml
  CONTRIBUTING.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4318 feat(jsii-reflect): TypeSystem can be locked to improve reflection performance
  packages/jsii-reflect/lib/_memoized.ts
  packages/jsii-reflect/lib/class.ts
  packages/jsii-reflect/lib/method.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/lib/type.ts
  packages/jsii-reflect/test/_memoized.test.ts
Labels: pr/ready-to-merge, contribution/core

#4325 feat: make node 18 the default
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/check-node/src/index.test.ts
  packages/@jsii/check-node/src/index.ts
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  superchain/Dockerfile
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core

#4324 fix(kernel): invokeBinScript fails when using symlinked cache
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/jsii-calc/bin/run.ts
Labels: pr/ready-to-merge, contribution/core

#4301 chore: fix typo in CallbackExtensions.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs
Labels: pr/ready-to-merge

#4236 fix(pacmak): *.tsbuildinfo not in auto-generated .npmignore file
  packages/jsii-pacmak/lib/npm-modules.ts
Labels: pr/ready-to-merge

#3995 docs(typescript-restrictions): clarify non-jsii deps
  gh-pages/content/user-guides/lib-author/typescript-restrictions.md
Labels: pr/ready-to-merge

#4326 feat(superchain): publish a bullseye image with node18 & python 3.9
  .github/workflows/docker-images.yml
  CONTRIBUTING.md
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core

#4327 feat: switch to python 3.8 (#4239)
  .github/workflows/main.yml
  CONTRIBUTING.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4310 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/src/kernel.ts
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/go.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/package.json
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4333 fix(superchain): installed setuptools is an unsupported version
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-pacmak/test/generated-code/python-pyright.test.ts
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#4336 chore(release): 1.92.0
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  CHANGELOG.md
  CONTRIBUTING.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  gh-pages/content/user-guides/lib-author/typescript-restrictions.md
  gh-pages/mkdocs.yml
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/check-node/src/index.test.ts
  packages/@jsii/check-node/src/index.ts
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/CallbackExtensions.cs
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii-calc/bin/run.ts
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/targets/dotnet/runtime-type-checking.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/python-pyright.test.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-reflect/lib/_memoized.ts
  packages/jsii-reflect/lib/class.ts
  packages/jsii-reflect/lib/method.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/lib/type.ts
  packages/jsii-reflect/test/_memoized.test.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/go.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/package.json
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/package.json
  superchain/Dockerfile
  superchain/README.md
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4337 chore(merge-back): 1.92.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4346 chore: update superchain README
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core

#4355 chore: use Node 18 in yarn upgrade workflow
  .github/workflows/yarn-upgrade.yml
Labels: pr/ready-to-merge, contribution/core

#4356 chore: update DockerHub README daily
  .github/workflows/docker-images.yml
Labels: pr/ready-to-merge, contribution/core

#4359 feat: deprecate `jsii/superchain:buster-slim-*` images
  .github/workflows/docker-images.yml
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core
