Repository aws/jsii, pull requests merged in 2023-03, with the labels that each got.

#3975 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/benchmarks/scripts/snapshot-package.ts
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/lib/find-utils.ts
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3987 fix(dotnet): target netcoreapp3.1 with RollForward
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/TypeCache.cs
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#3989 chore(release): 1.77.0
  .all-contributorsrc
  .github/workflows/main.yml
  .mergify/config.yml
  CHANGELOG.md
  README.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/benchmarks/scripts/snapshot-package.ts
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/TypeCache.cs
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/src/jsii/__meta__.py
  packages/@jsii/python-runtime/src/jsii/_compat.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/find-utils.ts
  packages/jsii-rosetta/lib/languages/go.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/lib/util.ts
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/no-squash

#3990 chore(merge-back): 1.77.0
  CHANGELOG.md
  lerna.json
Labels: pr/no-squash, auto-approve

#4000 fix(kernel): json deserialization fails on `null` value
  packages/@jsii/kernel/src/serialization.ts
Labels: pr/ready-to-merge, contribution/core

#4008 chore: configure default tag for jsii & jsii-rosetta
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
Labels: pr/ready-to-merge, contribution/core

#4010 chore(release): 1.78.0
  .github/workflows/docker-images.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/kernel/src/serialization.ts
  packages/jsii-diff/test/classes.test.ts
  packages/jsii-diff/test/type-unions.test.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-reflect/lib/type-ref.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  superchain/Dockerfile
Labels: pr/ready-to-merge, pr/no-squash

#4015 chore(merge-back): 1.78.1
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4021 feat: add configurable pack command
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/test/build-test.sh
Labels: pr/ready-to-merge

#3998 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4025 chore: configure publishing container images to ECR Public
  .github/workflows/docker-images.yml
Labels: pr/ready-to-merge, contribution/core

#4024 feat(runtimes): support JSII_NODE setting
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
  packages/@jsii/java-runtime-test/project/.mvn/maven.config
  packages/@jsii/java-runtime/project/.mvn/maven.config
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
  packages/@jsii/java-runtime/project/src/test/java/software/amazon/jsii/JsiiRuntimeTest.java
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
Labels: pr/ready-to-merge, contribution/core

#4027 chore(release): 1.79.0
  .all-contributorsrc
  .github/workflows/main.yml
  CHANGELOG.md
  README.md
  lerna.json
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
  packages/@jsii/go-runtime/jsii-runtime-go/helpers.go
  packages/@jsii/go-runtime/jsii-runtime-go/helpers_test.go
  packages/@jsii/java-runtime-test/project/.mvn/maven.config
  packages/@jsii/java-runtime/project/.mvn/maven.config
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
  packages/@jsii/java-runtime/project/src/test/java/software/amazon/jsii/JsiiRuntimeTest.java
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/runtime/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4031 chore: publish nightly images to ECR Public
  .github/workflows/docker-images.yml
Labels: pr/ready-to-merge, contribution/core

#4033 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4034 feat(rosetta): handle tablets with a streaming JSON codec
  packages/jsii-rosetta/lib/json.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/json.test.ts
  yarn.lock
Labels: pr/ready-to-merge, contribution/core
