Repository aws/jsii, pull requests merged in 2023-12, with the labels that each got.

#4362 fix(check-node): unstable node 21 is incorrectly listed as supported
  packages/@jsii/check-node/src/constants.ts
Labels: pr/ready-to-merge, contribution/core

#4364 chore: add author paulhcs to contribution/core
  .mergify/config.yml
Labels: pr/ready-to-merge

#4368 chore(merge-back): 1.93.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve
