Repository aws/jsii, pull requests merged in 2023-02, with the labels that each got.

#3946 chore: fix version updates
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/jsii-config/package.json
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#3947 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3927 fix(go): shorten file names for sub-packages
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
Labels: pr/ready-to-merge

#3955 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3959 feat(check-node): export NodeRelease class
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/check-node/src/index.ts
Labels: pr/ready-to-merge, contribution/core

#3966 chore(merge-back): 1.75.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3969 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3912 fix: JSII_RUNTIME_PACKAGE_CACHE improper case bug
  .all-contributorsrc
  README.md
  packages/@jsii/kernel/src/tar-cache/index.ts
Labels: pr/ready-to-merge

#3890 feat(go): add JSII_NODE to override node entrypoint
  .all-contributorsrc
  README.md
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process_test.go
Labels: pr/ready-to-merge

#3976 chore(release): 1.76.0
  .all-contributorsrc
  .github/workflows/main.yml
  .mergify/config.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  gh-pages/content/user-guides/lib-author/index.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests.FSharp/Amazon.JSII.Runtime.IntegrationTests.FSharp.fsproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.JsonModel/Amazon.JSII.JsonModel.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/ReflectionUtils.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/Converters/FrameworkToJsiiConverter.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/TypeCache.cs
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process_test.go
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/@jsii/python-runtime/build-tools/gen.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/src/jsii/_kernel/__init__.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/base.py
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/src/jsii/_utils.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  superchain/Dockerfile
  superchain/README.md
  tools/jsii-build-tools/bin/package-dotnet
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3977 chore(merge-back): 1.76.0
  CHANGELOG.md
  lerna.json
  tools/jsii-build-tools/bin/package-dotnet
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3953 fix(rosetta): prints colors to log file
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/commands/transliterate.ts
  packages/jsii-rosetta/lib/rosetta-reader.ts
  packages/jsii-rosetta/lib/util.ts
Labels: pr/ready-to-merge, contribution/core

#3985 fix(rosetta): go may incorrectly emit _ instead of .
  packages/jsii-rosetta/lib/languages/go.ts
Labels: pr/ready-to-merge, contribution/core
