Repository aws/jsii, pull requests merged in 2023-01, with the labels that each got.

#3897 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-config/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#3898 chore: updated maven to 3.8.7 in the superchain Dockerfile
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3896 chore(release): 1.73.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/package.json
  packages/jsii-config/package.json
  packages/jsii-pacmak/package.json
  superchain/Dockerfile
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3900 chore(merge-back): 1.73.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3886 chore: fix typo in Kernel.java
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Kernel.java
Labels: pr/ready-to-merge

#3913 chore(superchain): use `pipx` instead of `pip` to install CLIs
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3915 fix(rosetta): Rosetta does not support `await`
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/visualize.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/test/translations/expressions/await.cs
  packages/jsii-rosetta/test/translations/expressions/await.go
  packages/jsii-rosetta/test/translations/expressions/await.java
  packages/jsii-rosetta/test/translations/expressions/await.py
  packages/jsii-rosetta/test/translations/expressions/await.ts
Labels: pr/ready-to-merge, contribution/core

#3916 fix(python): returning Promise<void> breaks runtime
  gh-pages/content/specification/6-compliance-report.md
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  tools/jsii-compliance/suite.ts
Labels: pr/ready-to-merge, contribution/core

#3929 chore: rotate yarn GPG key
  superchain/gpg/yarn.asc
Labels: pr/ready-to-merge, contribution/core

#3940 chore: revert "chore(superchain): use `pipx` instead of `pip` to install CLIs"
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#3941 chore(release): 1.74.0
  CHANGELOG.md
  gh-pages/content/specification/6-compliance-report.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/Kernel.java
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/spec/package.json
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/visualize.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/translations/expressions/await.cs
  packages/jsii-rosetta/test/translations/expressions/await.go
  packages/jsii-rosetta/test/translations/expressions/await.java
  packages/jsii-rosetta/test/translations/expressions/await.py
  packages/jsii-rosetta/test/translations/expressions/await.ts
  superchain/gpg/yarn.asc
  tools/jsii-compliance/suite.ts
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#3942 chore(merge-back): 1.74.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#3928 fix(rosetta): submodule-qualified names produce invalid Go, Java
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-rosetta/jest.config.mjs
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/default.ts
  packages/jsii-rosetta/lib/languages/go.ts
  packages/jsii-rosetta/lib/languages/java.ts
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/lib/languages/target-language.ts
  packages/jsii-rosetta/lib/languages/visualize.ts
  packages/jsii-rosetta/lib/renderer.ts
  packages/jsii-rosetta/lib/submodule-reference.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/typescript/imports.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii-rosetta/test/jsii-imports.test.ts
  packages/jsii-rosetta/test/translations/calls/shorthand_property.cs
  packages/jsii-rosetta/test/translations/calls/will_type_deep_structs_directly_if_type_info_is_available.go
  packages/jsii-rosetta/test/translations/expressions/await.cs
  packages/jsii-rosetta/test/translations/expressions/backtick_string_w_o_substitutions.cs
  packages/jsii-rosetta/test/translations/expressions/computed_key.cs
  packages/jsii-rosetta/test/translations/expressions/string_interpolation.cs
  packages/jsii-rosetta/test/translations/expressions/string_literal.cs
  packages/jsii-rosetta/test/translations/expressions/string_literal.go
  packages/jsii-rosetta/test/translations/expressions/string_literal.java
  packages/jsii-rosetta/test/translations/expressions/string_literal.py
  packages/jsii-rosetta/test/translations/expressions/string_literal.ts
  packages/jsii-rosetta/test/translations/expressions/struct_assignment.cs
  packages/jsii-rosetta/test/translations/imports/selective_import.java
  packages/jsii-rosetta/test/translations/imports/submodule-import.cs
  packages/jsii-rosetta/test/translations/imports/submodule-import.go
  packages/jsii-rosetta/test/translations/imports/submodule-import.java
  packages/jsii-rosetta/test/translations/imports/submodule-import.py
  packages/jsii-rosetta/test/translations/imports/submodule-import.ts
  packages/jsii-rosetta/test/translations/statements/statements_and_newlines.cs
  packages/jsii-rosetta/test/translations/structs/infer_struct_from_union.go
  packages/jsii-rosetta/test/translations/structs/optional_known_struct.go
  packages/jsii-rosetta/test/translations/structs/struct_starting_with_i.go
  packages/jsii-rosetta/test/translations/structs/var_new_class_known_struct.cs
  packages/jsii-rosetta/test/translations/structs/var_new_class_known_struct.go
Labels: pr/ready-to-merge, contribution/core

#3944 chore: update dependencies
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/python-pyright.test.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
Labels: pr/ready-to-merge, contribution/core
