Repository aws/jsii, pull requests merged in 2023-07, with the labels that each got.

#4166 fix: export transliterateAssembly and fix bug with transliterate cli (backport)
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/index.ts
Labels: pr/ready-to-merge, contribution/core

#4109 fix(go-runtime): use fatih/color instead of ANSI Escape Code
  packages/@jsii/go-runtime/jsii-runtime-go/deprecationwarning.go
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
Labels: pr/ready-to-merge

#4167 chore: fix pr labeler workflow does not trigger auto-approval
  .github/workflows/pr-labeler.yml
Labels: pr/ready-to-merge, contribution/core

#4162 chore(superchain): maven version, docs: CONTRIBUTING.md
  CONTRIBUTING.md
  superchain/Dockerfile
Labels: pr/ready-to-merge

#4163 chore(github-actions): added stale discussion workflow
  .github/workflows/handle-stale-discussions.yml
Labels: pr/ready-to-merge

#4174 chore(docs): documentation enhancements
  gh-pages/content/overview/features.md
  gh-pages/content/specification/3-kernel-api.md
  gh-pages/content/user-guides/lib-author/.pages.yml
  gh-pages/content/user-guides/lib-author/hints.md
  gh-pages/content/user-guides/lib-author/typescript-restrictions.md
Labels: pr/ready-to-merge, contribution/core

#4177 chore: use node 16 in upgrade workflows
  .github/workflows/yarn-upgrade.yml
Labels: pr/ready-to-merge, contribution/core

#4180 chore(release): 1.85.0
  .github/dependabot.yml
  .github/workflows/close-stale-issues.yml
  .github/workflows/docker-images.yml
  .github/workflows/gh-pages.yml
  .github/workflows/handle-stale-discussions.yml
  .github/workflows/main.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  CONTRIBUTING.md
  gh-pages/content/overview/features.md
  gh-pages/content/specification/3-kernel-api.md
  gh-pages/content/user-guides/lib-author/.pages.yml
  gh-pages/content/user-guides/lib-author/hints.md
  gh-pages/content/user-guides/lib-author/typescript-restrictions.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Verifiers/DiagnosticVerifier.cs
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/deprecationwarning.go
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/kernel/src/api.ts
  packages/@jsii/kernel/src/link.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/bin/jsii-runtime.ts
  packages/@jsii/runtime/lib/host.ts
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/package.json
  superchain/Dockerfile
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4168 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/lib/benchmark.ts
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-diff/lib/types.ts
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/enum.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type.ts
  packages/jsii-pacmak/lib/targets/go/types/type-member.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/lib/util.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/lib/tree.ts
  packages/jsii-rosetta/bin/jsii-rosetta.ts
  packages/jsii-rosetta/lib/jsii/jsii-utils.ts
  packages/jsii-rosetta/lib/languages/target-language.ts
  packages/jsii-rosetta/lib/snippet-selectors.ts
  packages/jsii-rosetta/lib/snippet.ts
  packages/jsii-rosetta/lib/translate.ts
  packages/jsii-rosetta/lib/typescript/types.ts
  packages/jsii-rosetta/package.json
  packages/jsii-rosetta/test/commands/transliterate.test.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/compiler.ts
  packages/jsii/lib/docs.ts
  packages/jsii/lib/transforms/deprecated-remover.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/src/ascii-tree.ts
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4184 chore(merge-back): 1.85.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4185 chore(kernel): use ES private fields
  packages/@jsii/kernel/src/disk-cache/disk-cache.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/objects.ts
  packages/@jsii/kernel/src/serialization.test.ts
Labels: contribution/core

#4115 fix(jsii-pacmak): handles 'default' doc component for go
  .all-contributorsrc
  README.md
  packages/jsii-pacmak/lib/targets/go/documentation.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-reflect/lib/docs.ts
Labels: pr/ready-to-merge

#4186 feat(python): deprecation message when using Python <= 3.7
  packages/@jsii/python-runtime/src/jsii/__init__.py
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
Labels: pr/ready-to-merge, contribution/core

#4187 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4181 feat: faster, lazy-friendly runtime loading
  CONTRIBUTING.md
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/link.ts
  packages/@jsii/kernel/src/objects.ts
  packages/@jsii/kernel/src/serialization.test.ts
  packages/@jsii/kernel/src/serialization.ts
  packages/@jsii/kernel/src/serialization.ux.test.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/process.py
  packages/@jsii/runtime/bin/jsii-runtime.ts
  packages/@jsii/runtime/lib/host.ts
  packages/@jsii/runtime/lib/program.ts
  packages/@scope/jsii-calc-lib/lib/deprecation-removal.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/test/jsii/assemblies.test.ts
  tsconfig-base.json
Labels: pr/ready-to-merge, contribution/core

#4193 fix(jsii-pacmak): comment lines should not contain comment ending
  packages/jsii-calc/bin/run.ts
  packages/jsii-calc/lib/documented.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
Labels: pr/ready-to-merge
