Repository aws/jsii, pull requests merged in 2023-05, with the labels that each got.

#4077 chore: silence node end of life warning in tests
  packages/@jsii/check-node/src/index.ts
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
Labels: pr/ready-to-merge, contribution/core

#4081 fix(pacmak): go docs overview displays repeating description
  packages/codemaker/src/codemaker.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4076 feat(jsii-diff): allow external stability to be treated as error
  packages/jsii-diff/README.md
  packages/jsii-diff/bin/jsii-diff.ts
  packages/jsii-diff/lib/diagnostics.ts
  packages/jsii-diff/test/diagnostics.test.ts
Labels: pr/ready-to-merge, contribution/core

#4087 chore(release): 1.81.0
  .github/workflows/yarn-upgrade.yml
  .mergify/config.yml
  CHANGELOG.md
  README.md
  gh-pages/content/compiler-and-rosetta-maintenance.md
  gh-pages/content/overview/toolchain.md
  gh-pages/mkdocs.yml
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/check-node/src/index.ts
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/codemaker/src/codemaker.ts
  packages/jsii-diff/README.md
  packages/jsii-diff/bin/jsii-diff.ts
  packages/jsii-diff/lib/diagnostics.ts
  packages/jsii-diff/test/diagnostics.test.ts
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/targets/go/package.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/build-test.sh
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/json.ts
  packages/jsii-rosetta/lib/tablets/tablets.ts
  packages/jsii-rosetta/lib/upgrade-prompt.ts
  packages/jsii-rosetta/package.json
  packages/jsii/lib/index.ts
  packages/jsii/lib/upgrade-prompt.ts
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4090 chore(merge-back): 1.81.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4092 chore: suppress extraneous upgrade prompts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/suppress-jsii-upgrade-prompts.ts
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/upgrade-prompt.ts
Labels: pr/ready-to-merge, contribution/core

#4073 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4095 fix(jsii-pacmak): emit correct `@return` tag for JavaDocs
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4082 feat(superchain): switch to JDK 20
  superchain/Dockerfile
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core

#4103 fix(jsii-pacmak): disable `doclint`
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4094 fix(pacmak): _ is not treated as a keyword in Java
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4104 feat(go): register exported properties as callbacks
  packages/@jsii/go-runtime-test/project/callbacks_test.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/manage-object.go
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4096 fix(jsii-pacmak): escape documentation in all positions
  packages/jsii-calc/lib/documented.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4105 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4114 chore(release): 1.82.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/callbacks_test.go
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/callbacks.go
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/manage-object.go
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/package.json
  packages/@scope/jsii-calc-lib/lib/index.ts
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/lib/documented.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/suppress-jsii-upgrade-prompts.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/harness.ts
  packages/jsii-pacmak/test/generated-code/python-pyright.test.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
  packages/jsii-rosetta/lib/index.ts
  packages/jsii-rosetta/lib/upgrade-prompt.ts
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  superchain/Dockerfile
  superchain/README.md
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4119 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4120 chore(merge-back): 1.82.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4079 chore(Dockerfile): use AWS CLI v2
  superchain/Dockerfile
  superchain/README.md
Labels: pr/ready-to-merge
