Repository aws/jsii, pull requests merged in 2023-08, with the labels that each got.

#4195 chore: multi-build super chain image with several Debian releases
  .github/workflows/docker-images.yml
  .mergify/config.yml
  superchain/Dockerfile
  superchain/README.md
  superchain/build-local.sh
Labels: pr/ready-to-merge, contribution/core

#4200 chore(merge-back): 1.86.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4204 fix(kernel): incorrectly scoped FQN resolutions
  packages/@jsii/kernel/src/objects.test.ts
  packages/@jsii/kernel/src/objects.ts
Labels: contribution/core

#4201 fix: pip, black, setuptools, twine, wheel, and aws-sam-cli incorrectly installed in superchain
  superchain/Dockerfile
  superchain/build-local.sh
Labels: contribution/core

#4205 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4209 fix(python): type object 'InterfaceDynamicProxy' has no attribute '__jsii_type__'
  packages/@jsii/python-runtime/src/jsii/_reference_map.py
Labels: pr/ready-to-merge, contribution/core

#4212 fix(kernel): fast module loading fails on Windows (EPERM)
  packages/@jsii/kernel/src/link.ts
Labels: pr/ready-to-merge, contribution/core

#4214 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-config/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4219 chore(superchain): replace pyenv with pipx
  superchain/Dockerfile
  superchain/build-local.sh
Labels: pr/ready-to-merge, contribution/core

#4216 chore: cut down on Docker Images built, drop Node 14
  .github/workflows/docker-images.yml
Labels: pr/ready-to-merge, contribution/core

#4224 fix(superchain): add openssh-client back
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#4226 chore(release): 1.87.0
  .github/workflows/close-stale-issues.yml
  .github/workflows/docker-images.yml
  CHANGELOG.md
  lerna.json
  package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/kernel/src/disk-cache/disk-cache.ts
  packages/@jsii/kernel/src/link.ts
  packages/@jsii/kernel/src/tar-cache/index.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/src/jsii/_reference_map.py
  packages/jsii-config/package.json
  packages/jsii-pacmak/package.json
  superchain/Dockerfile
  superchain/build-local.sh
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4227 chore(merge-back): 1.87.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4247 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4250 chore(release): 1.88.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4251 chore(merge-back): 1.88.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4246 chore: Add author mikewrighton to mergify config
  .mergify/config.yml
Labels: pr/ready-to-merge

#4240 chore: Update node support table for 16. EOL
  gh-pages/partials/node-support-table.md
Labels: pr/ready-to-merge
