Repository aws/jsii, pull requests merged in 2024-11, with the labels that each got.

#4687 chore: npm-check-updates && yarn upgrade
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4696 ci: allow manual dispatch of superchain build
  .github/workflows/docker-images.yml
Labels: pr/ready-to-merge, contribution/core

#4698 feat(pacmak): support jsii-rosetta 5.6
  .github/workflows/main.yml
  packages/jsii-pacmak/package.json
Labels: pr/ready-to-merge, contribution/core

#4697 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4700 chore(merge-back): 1.105.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4708 chore: npm-check-updates && yarn upgrade
  package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4714 chore: revert "npm-check-updates && yarn upgrade"
  package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: contribution/core

#4713 chore: move superchain to new repo
  .devcontainer.json
  .github/workflows/docker-images.yml
  .mergify/config.yml
  CONTRIBUTING.md
  gh-pages/content/specification/5-new-language-intake.md
  gh-pages/content/user-guides/language-support/index.md
  superchain/.dockerignore
  superchain/Dockerfile
  superchain/README.md
  superchain/amazon-ssm-agent.json
  superchain/build-local.sh
  superchain/gpg/corretto.asc
  superchain/gpg/docker.asc
  superchain/gpg/mono.asc
  superchain/gpg/nodesource.asc
  superchain/gpg/yarn.asc
  superchain/m2-settings.xml
  superchain/ssh_config
Labels: contribution/core

#4715 chore: fix matrix build results are not actually checked
  .github/workflows/main.yml
  .mergify/config.yml
Labels: pr/ready-to-merge, contribution/core
