Repository aws/jsii, pull requests merged in 2024-01, with the labels that each got.

#4389 fix(pacmak): invokeBinScript fails when using symlinked cache
  gh-pages/content/overview/runtime-architecture.md
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4394 chore(superchain): fix maven downloads failing due to outdated urls
  superchain/Dockerfile
Labels: pr/ready-to-merge, contribution/core

#4395 chore(release): 1.94.0
  CHANGELOG.md
  gh-pages/content/overview/runtime-architecture.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/internal/kernel/process/process.go
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  superchain/Dockerfile
Labels: pr/ready-to-merge, pr/no-squash

#4397 chore(merge-back): 1.94.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4392 fix(jsii-pacmak): show custom pack-command in timer label
  packages/jsii-pacmak/lib/index.ts
Labels: pr/ready-to-merge

#4381 chore(docs): fix typo in go helper function Doc Comment
  packages/@jsii/go-runtime/jsii-runtime-go/helpers.go
  packages/@jsii/go-runtime/jsii-runtime-go/jsii.go
Labels: pr/ready-to-merge
