Repository aws/jsii, pull requests merged in 2024-05, with the labels that each got.

#4500 chore(superchain): explicitly list supported images
  .github/workflows/docker-images.yml
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core

#4499 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/integ-test/package.json
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@jsii/spec/src/name-tree.ts
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/package.json
  packages/oo-ascii-tree/package.json
  tools/jsii-build-tools/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4511 chore(java-runtime): fix spelling in comment
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
Labels: pr/ready-to-merge

#4514 chore: fix typo in error message - `delcaration`
  gh-pages/content/specification/2-type-system.md
  gh-pages/content/specification/3-kernel-api.md
  jest.config.mjs
  packages/jsii-rosetta/lib/languages/go.ts
  packages/jsii-rosetta/lib/submodule-reference.ts
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/validator.ts
  packages/jsii/test/__snapshots__/negatives.test.js.snap
Labels: pr/ready-to-merge

#4515 fix(jsii-config): update jsii-config and docs with latest settings
  gh-pages/content/user-guides/lib-author/configuration/index.md
  gh-pages/content/user-guides/lib-author/index.md
  gh-pages/content/user-guides/lib-author/toolchain/jsii.md
  gh-pages/partials/tsconfig-rulesets.md
  packages/jsii-config/lib/prompt.ts
  packages/jsii-config/lib/questions.ts
  packages/jsii-config/lib/schema.ts
  packages/jsii-config/package.json
  packages/jsii-config/test/index.test.ts
Labels: pr/ready-to-merge, contribution/core

#4518 chore: small fixes to docs for user-provided tsconfig
  gh-pages/content/user-guides/lib-author/configuration/index.md
  gh-pages/partials/tsconfig-rulesets.md
Labels: pr/ready-to-merge, contribution/core
