Repository aws/jsii, pull requests merged in 2024-04, with the labels that each got.

#4475 chore(release): 1.97.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/test/targets/version-utils.test.ts
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4476 chore(merge-back): 1.97.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4488 chore: bump mkdocs-material
  gh-pages/requirements-dev.txt
Labels: pr/ready-to-merge, contribution/core

#4489 feat: node22 support
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  CONTRIBUTING.md
  gh-pages/partials/node-support-table.md
  packages/@jsii/check-node/src/constants.ts
  superchain/Dockerfile
  superchain/README.md
  superchain/gpg/nodesource.asc
Labels: pr/ready-to-merge, contribution/core

#4487 fix(pacmak): jsii-pacmak uses incompatible version of jsii-rosetta
  .github/workflows/main.yml
  gh-pages/content/overview/toolchain.md
  gh-pages/content/user-guides/language-support/index.md
  packages/jsii-pacmak/.eslintrc.yaml
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/suppress-jsii-upgrade-prompts.ts
  packages/jsii-pacmak/lib/target.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/documentation.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/targets/go.test.ts
  packages/jsii-reflect/lib/class.ts
  scripts/align-version.js
Labels: pr/ready-to-merge, contribution/core

#4491 fix(reflect): additional type predicates for `isXyzType` methods
  packages/jsii-reflect/lib/enum.ts
  packages/jsii-reflect/lib/interface.ts
Labels: pr/ready-to-merge, contribution/core

#4497 chore(release): 1.98.0
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  CHANGELOG.md
  CONTRIBUTING.md
  gh-pages/content/overview/toolchain.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/partials/node-support-table.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/.eslintrc.yaml
  packages/jsii-pacmak/bin/jsii-pacmak.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/suppress-jsii-upgrade-prompts.ts
  packages/jsii-pacmak/lib/target.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/go/documentation.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-pacmak/test/targets/go.test.ts
  packages/jsii-reflect/lib/class.ts
  packages/jsii-reflect/lib/enum.ts
  packages/jsii-reflect/lib/interface.ts
  scripts/align-version.js
  superchain/Dockerfile
  superchain/README.md
  superchain/gpg/nodesource.asc
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4498 chore(merge-back): 1.98.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve
