Repository aws/jsii, pull requests merged in 2024-10, with the labels that each got.

#4659 fix: Python constructs do not implement a compatible interface
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4648 chore(pacmak): fix typo in python.ts
  packages/jsii-pacmak/lib/targets/python.ts
Labels: pr/ready-to-merge, hacktoberfest-invalid

#4660 chore(release): 1.104.0
  .github/dependabot.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4640 chore: modified bug issue template to add checkbox to report potential regression
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/issue-regression-labeler.yml
Labels: pr/ready-to-merge

#4644 fix(rosetta): python identifiers mishandle identifier translations with capital letters
  packages/jsii-rosetta/lib/languages/python.ts
  packages/jsii-rosetta/test/translate.test.ts
Labels: pr/ready-to-merge, contribution/core

#4637 chore: npm-check-updates && yarn upgrade
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4661 chore(merge-back): 1.104.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4670 chore(mergify): move deprecated parameters from `pull_request_rules` to `queue_rules`
  .mergify/config.yml
Labels: pr/ready-to-merge, contribution/core

#4671 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4681 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-rosetta/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve
