Repository aws/jsii, pull requests merged in 2024-03, with the labels that each got.

#4437 fix(jsii-pacmak): different packages sharing a namespace fail in Bazel
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4427 chore(release): 1.95.0
  .github/workflows/docker-images.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/Converters/FrameworkToJsiiConverterTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Deputy/Converters/JsiiToFrameworkConverterTests.cs
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/helpers.go
  packages/@jsii/go-runtime/jsii-runtime-go/jsii.go
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  yarn.lock
Labels: pr/no-squash

#4446 revert(deps): Update pytest requirement from ~=8.1 to ~=8.0 in /packages/@jsii/python-runtime
  packages/@jsii/python-runtime/requirements.txt
Labels: pr/ready-to-merge, contribution/core

#4443 chore(merge-back): 1.95.0
  .github/workflows/docker-images.yml
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4463 chore(release): 1.96.0
  .github/workflows/close-stale-issues.yml
  .github/workflows/closed-issue-message.yml
  .mergify/config.yml
  CHANGELOG.md
  gh-pages/content/compiler-and-rosetta-maintenance.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/src/jsii/_kernel/providers/base.py
  packages/@jsii/python-runtime/src/jsii/_kernel/types.py
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/python-runtime/tests/test_invoke_bin.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4464 chore(merge-back): 1.96.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4462 fix(jsii-pacmak): fully support the Python Version Identification part of PEP440
  packages/jsii-pacmak/lib/targets/version-utils.ts
  packages/jsii-pacmak/test/targets/version-utils.test.ts
Labels: pr/ready-to-merge
