Repository aws/jsii, pull requests merged in 2024-06, with the labels that each got.

#4528 chore(release): 1.99.0
  .github/workflows/docker-images.yml
  CHANGELOG.md
  gh-pages/content/specification/2-type-system.md
  gh-pages/content/specification/3-kernel-api.md
  gh-pages/content/user-guides/lib-author/configuration/index.md
  gh-pages/content/user-guides/lib-author/index.md
  gh-pages/content/user-guides/lib-author/toolchain/jsii.md
  gh-pages/partials/tsconfig-rulesets.md
  gh-pages/requirements-dev.txt
  jest.config.mjs
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/integ-test/package.json
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
  packages/@jsii/kernel/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/@jsii/spec/src/name-tree.ts
  packages/codemaker/package.json
  packages/jsii-calc/package.json
  packages/jsii-config/lib/prompt.ts
  packages/jsii-config/lib/questions.ts
  packages/jsii-config/lib/schema.ts
  packages/jsii-config/package.json
  packages/jsii-config/test/index.test.ts
  packages/jsii-diff/package.json
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  packages/jsii-rosetta/lib/languages/go.ts
  packages/jsii-rosetta/lib/submodule-reference.ts
  packages/jsii-rosetta/package.json
  packages/jsii/lib/assembler.ts
  packages/jsii/lib/jsii-diagnostic.ts
  packages/jsii/lib/validator.ts
  packages/jsii/package.json
  packages/jsii/test/__snapshots__/negatives.test.js.snap
  packages/oo-ascii-tree/package.json
  superchain/README.md
  tools/jsii-build-tools/package.json
  tools/jsii-compliance/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4530 chore(merge-back): 1.99.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4538 fix(python): incorrect escaped characters cause warnings
  packages/@jsii/python-runtime/tests/README.md
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4542 chore(release): 1.100.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/tests/README.md
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, pr/no-squash

#4543 chore(merge-back): 1.100.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4554 fix(pacmak): Twine 5.1.0 not found
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
Labels: pr/ready-to-merge, contribution/core

#4555 chore: upgrade lerna to fix CVE with tar dependency
  package.json
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#4556 chore(release): 1.101.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash
