Repository aws/jsii, pull requests merged in 2024-08, with the labels that each got.

#4594 chore(release): 1.102.0
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  CHANGELOG.md
  CONTRIBUTING.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/check-node/package.json
  packages/@jsii/check-node/src/constants.ts
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/tests/test_compliance.py
  packages/@jsii/runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/python-pyright.test.ts
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-rosetta/package.json
  packages/jsii/package.json
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4595 chore(merge-back): 1.102.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4603 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4607 chore: fix incorrect debian codenames in superchain support table
  superchain/README.md
Labels: pr/ready-to-merge, contribution/core

#4619 fix(pacmak): support jsii-rosetta 5.5
  .github/workflows/main.yml
  CONTRIBUTING.md
  gh-pages/content/overview/toolchain.md
  gh-pages/content/user-guides/language-support/index.md
  packages/@jsii/go-runtime/build-tools/package.sh
  packages/jsii-pacmak/package.json
Labels: pr/ready-to-merge, contribution/core

#4610 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/index.ts
  packages/@jsii/benchmarks/scripts/snapshot-package.ts
  packages/@jsii/integ-test/utils/index.ts
  packages/@jsii/kernel/src/api.ts
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/recording.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/spec/package.json
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/lib/erasures.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/lib/util.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/util.test.ts
  packages/jsii-reflect/lib/_memoized.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/lib/o-tree.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/transforms/deprecated-remover.ts
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4611 feat(pacmak): allow `typeguard==3.x` and `typeguard==4.x`
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_python.py
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4620 chore(release): 1.103.0
  .github/workflows/main.yml
  CHANGELOG.md
  CONTRIBUTING.md
  gh-pages/content/overview/toolchain.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/benchmarks/lib/suite/aws-cdk-lib/index.ts
  packages/@jsii/benchmarks/scripts/snapshot-package.ts
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/build-tools/package.sh
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/integ-test/utils/index.ts
  packages/@jsii/kernel/src/api.ts
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/recording.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_python.py
  packages/@jsii/python-runtime/tests/test_runtime_type_checking.py
  packages/@jsii/spec/package.json
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/lib/erasures.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/lib/util.ts
  packages/jsii-pacmak/lib/builder.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/lib/targets/python/type-name.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-pacmak/test/util.test.ts
  packages/jsii-reflect/lib/_memoized.ts
  packages/jsii-rosetta/lib/languages/csharp.ts
  packages/jsii-rosetta/lib/languages/record-references.ts
  packages/jsii-rosetta/lib/o-tree.ts
  packages/jsii/lib/symbol-id.ts
  packages/jsii/lib/transforms/deprecated-remover.ts
  superchain/README.md
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4621 chore(merge-back): 1.103.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4625 fix(python): user defined `__jsii_proxy_class` attributes are not preserved
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_python.py
Labels: pr/ready-to-merge, contribution/core

#4624 chore: npm-check-updates && yarn upgrade
  .github/workflows/yarn-upgrade.yml
  package.json
  packages/@jsii/python-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4628 chore(release): 1.103.1
  CHANGELOG.md
  lerna.json
  packages/@jsii/python-runtime/src/jsii/_runtime.py
  packages/@jsii/python-runtime/tests/test_python.py
Labels: pr/ready-to-merge, contribution/core, pr/no-squash

#4631 chore(merge-back): 1.103.1
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve
