Repository aws/jsii, pull requests merged in 2025-03, with the labels that each got.

#4788 chore(release): 1.109.0
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  CHANGELOG.md
  CONTRIBUTING.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/runtime/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4789 chore(merge-back): 1.109.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4790 fix: python packages are incompatible with the binary distribution format specification
  packages/@jsii/python-runtime/requirements.txt
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge

#4792 feat(pacmak): support jsii-rosetta 5.8
  .github/workflows/main.yml
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
  yarn.lock
Labels: pr/ready-to-merge, contribution/core

#4803 fix(java-runtime): `ErrorStreamSink` crashes with `NullPointerException`
  packages/@jsii/java-runtime/project/src/main/java/software/amazon/jsii/JsiiRuntime.java
  packages/@jsii/java-runtime/project/src/test/java/software/amazon/jsii/JsiiRuntimeTest.java
Labels: pr/ready-to-merge, contribution/core
