Repository aws/jsii, pull requests merged in 2025-05, with the labels that each got.

#4827 chore: fix the Python build for Python >= 3.12
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
Labels: pr/ready-to-merge, contribution/core

#4826 fix(jsii-pacmak): CS0108 <static property> hides inherited member
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4829 chore(release): 1.112.0
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/runtime/bin/jsii-runtime.ts
  packages/@jsii/runtime/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/compliance.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-config/lib/questions.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/go/types/class.ts
  packages/jsii-pacmak/lib/targets/go/types/go-type-reference.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-reflect/lib/assembly.ts
  packages/jsii-reflect/lib/type-system.ts
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/tree.test.ts
  tools/jsii-build-tools/bin/diff-test
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4830 chore(merge-back): 1.112.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4828 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/check-node/package.json
  packages/@jsii/dotnet-runtime/package.json
  packages/@jsii/runtime/package.json
  packages/@scope/jsii-calc-base-of-base/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/package.json
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/package.json
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/package.json
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: dependencies, contribution/core, auto-approve
