Repository aws/jsii, pull requests merged in 2025-09, with the labels that each got.

#4898 feat: prepare support for intersection types
  packages/@jsii/kernel/src/kernel.test.ts
  packages/@jsii/kernel/src/kernel.ts
  packages/@jsii/kernel/src/serialization.ts
  packages/@jsii/spec/src/assembly-utils.ts
  packages/@jsii/spec/src/assembly.ts
  packages/jsii-pacmak/lib/index.ts
  packages/jsii-pacmak/lib/rosetta-assembly.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnettyperesolver.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-reflect/lib/type-ref.ts
Labels: pr/ready-to-merge, contribution/core

#4899 chore: fix build problems
  packages/@jsii/kernel/package.json
  packages/@jsii/runtime/package.json
  packages/jsii-config/package.json
  packages/jsii-diff/package.json
  packages/jsii-pacmak/package.json
  packages/jsii-reflect/package.json
Labels: pr/ready-to-merge, contribution/core

#4914 fix: jsii-pacmak errors if new targets in package.json
  packages/jsii-pacmak/lib/npm-modules.ts
  packages/jsii-pacmak/lib/packaging.ts
  packages/jsii-pacmak/test/npm-modules.test.ts
Labels: pr/ready-to-merge, contribution/core

#4916 feat(dotnet): update TargetFramework to net6.0
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/ComplianceTests.cs
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
  packages/jsii-pacmak/lib/targets/dotnet.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4926 chore: changelog entry points to non existing release
  CHANGELOG.md
Labels: pr/ready-to-merge, contribution/core

#4922 feat(jsii-pacmak): document union types in JavaDoc
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4927 fix(pacmak): python classes are generated out of order
  packages/jsii-calc/lib/index.ts
  packages/jsii-calc/lib/pascal-case-name/index.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-go.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-java.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
  packages/jsii-reflect/test/__snapshots__/jsii-tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/tree.test.js.snap
  packages/jsii-reflect/test/__snapshots__/type-system.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4924 feat: declare support for new feature `class-covariant-overrides`
  packages/@jsii/spec/src/assembly.ts
Labels: pr/ready-to-merge, contribution/core

#4928 feat(jsii-pacmak): document union types for C#
  packages/@jsii/spec/src/assembly.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetdocgenerator.ts
  packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts
  packages/jsii-pacmak/lib/targets/java.ts
  packages/jsii-pacmak/lib/type-utils.ts
  packages/jsii-pacmak/lib/type-visitor.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-dotnet.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4938 chore: prevent dependabot from updating the golang version
  .github/dependabot.yml
Labels: pr/ready-to-merge, contribution/core, queued

#4940 chore(merge-back): 1.115.0
  CHANGELOG.md
  lerna.json
Labels: pr/ready-to-merge, contribution/core, pr/no-squash, auto-approve, queued
