Repository aws/jsii, pull requests merged in 2025-02, with the labels that each got.

#4758 chore: upgrade `actions/upload-artifact` to v4
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
Labels: contribution/core

#4762 chore(deps): upgrade actions/download-artifact to v4
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
Labels: pr/ready-to-merge, contribution/core

#4759 chore: use nullish coalescing instead of the ternary operator
  packages/jsii-calc/lib/calculator.ts
Labels: pr/ready-to-merge, contribution/core

#4756 chore: npm-check-updates && yarn upgrade
  package.json
  packages/@jsii/python-runtime/package.json
  packages/jsii-pacmak/package.json
  yarn.lock
Labels: pr/ready-to-merge, dependencies, contribution/core, auto-approve

#4771 fix(java-runtime): raise Jackson version bound to 2.19.0
  packages/@jsii/java-runtime/pom.xml.t.js
Labels: pr/ready-to-merge, contribution/core

#4772 chore(release): 1.107.0
  .github/workflows/closed-issue-message.yml
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  .github/workflows/yarn-upgrade.yml
  .mergify/config.yml
  CHANGELOG.md
  gh-pages/requirements-dev.txt
  lerna.json
  package.json
  packages/@jsii/Directory.Build.targets
  packages/@jsii/java-runtime/pom.xml.t.js
  packages/@jsii/python-runtime/package.json
  packages/@jsii/python-runtime/requirements.txt
  packages/@jsii/python-runtime/setup.py
  packages/@jsii/runtime/package.json
  packages/@scope/jsii-calc-base-of-base/test/assembly.jsii
  packages/@scope/jsii-calc-base/test/assembly.jsii
  packages/@scope/jsii-calc-lib/test/assembly.jsii
  packages/jsii-calc/lib/calculator.ts
  packages/jsii-calc/test/assembly.jsii
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
  packages/jsii-pacmak/package.json
  packages/jsii-pacmak/test/generated-code/requirements-dev.txt
  packages/jsii-reflect/lib/callable.ts
  packages/jsii-reflect/lib/module-like.ts
  yarn.lock
Labels: pr/ready-to-merge, pr/no-squash

#4773 chore(merge-back): 1.107.0
  CHANGELOG.md
  lerna.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
Labels: pr/ready-to-merge, pr/no-squash, auto-approve

#4776 fix: Python publishing fails on some Python distributions
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
Labels: pr/ready-to-merge, contribution/core

#4777 chore(release): 1.108.0
  CHANGELOG.md
  lerna.json
  packages/@jsii/go-runtime-test/project/go.mod
  packages/@jsii/go-runtime-test/project/go.sum
  packages/@jsii/go-runtime/jsii-runtime-go/go.mod
  packages/@jsii/go-runtime/jsii-runtime-go/go.sum
  packages/jsii-pacmak/lib/targets/python/requirements-dev.txt
Labels: pr/ready-to-merge, pr/no-squash

#4780 feat: switch to python 3.9
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
  CONTRIBUTING.md
  gh-pages/content/user-guides/language-support/index.md
  gh-pages/content/user-guides/lib-author/configuration/targets/python.md
  gh-pages/content/user-guides/lib-author/index.md
  packages/@jsii/python-runtime/pyproject.toml
  packages/@jsii/python-runtime/setup.py
  packages/jsii-pacmak/lib/targets/python.ts
  packages/jsii-pacmak/test/generated-code/__snapshots__/examples.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/prerelease-identifiers.test.js.snap
  packages/jsii-pacmak/test/generated-code/__snapshots__/target-python.test.js.snap
Labels: pr/ready-to-merge, contribution/core

#4782 fix(dotnet-windows): specify versions for dotnet packages to prevent errors in Windows
  packages/@jsii/dotnet-runtime-test/test/Amazon.JSII.Runtime.IntegrationTests/Amazon.JSII.Runtime.IntegrationTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers.UnitTests/Amazon.JSII.Analyzers.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Analyzers/Amazon.JSII.Analyzers.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime.UnitTests/Amazon.JSII.Runtime.UnitTests.csproj
  packages/@jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Amazon.JSII.Runtime.csproj
Labels: pr/ready-to-merge, contribution/core

#4781 docs(contributing): provide example instruction for using jsii-superchain docker image
  CONTRIBUTING.md
Labels: pr/ready-to-merge, contribution/core
